.changeset/moody-tools-fold.md
.changeset/shiny-peas-call.md
packages/components/breadcrumb/src/breadcrumb.tsx

Related #193   
> Nothing.
> Nothing.
No.

fix: Breadcrumb changed className

---

.changeset/gorgeous-adults-leave.md
packages/components/markdown/src/markdown.tsx

Related #193 
> Changed `className`
> Nothing.
> Nothing.
No.

fix: Markdown  changed className

---

.changeset/swift-dolphins-fetch.md
packages/theme/src/components/drawer.ts

Closes #264
When I specified full for the Drawer size, I expected that the height would be dynamic (dvh) on mobile browsers, but it is fixed (vh) and is cut off depending on the mobile browser.
changed from `100vh` to `100dvh`
No

fix: changed drawer height

---

.changeset/heavy-geese-complain.md
packages/components/autocomplete/src/multi-autocomplete.tsx

Closes #390 
> The bug causing the placeholder to disappear in MultiAutocomplete has been fixed.
> The placeholder is disapper.
> The placeholder is apper.
No.
https://github.com/hirotomoyamada/yamada-ui/assets/60034520/054b26c0-c004-4c2f-b83f-52ffc9c34cb8

fix: fixed placeholder in `MultiAutocomplete`

---

.changeset/lucky-trains-compete.md
packages/hooks/use-controllable-state/src/index.ts

Closes #398 #388
> DatePicker and MonthPicker value can't be cleared
> DatePicker and MonthPicker value can be cleared
No.

Fixed `DatePicker` and `MonthPicker` value can't be cleared

---

.changeset/odd-parrots-deliver.md
packages/components/table/src/thead.tsx

Closes #263
Fixed add `className` to `Tr` component.
Currently, can not be add `className` to `Tr` component.
No

fix(table): fixed `className` prop in `Tr` component

---

.changeset/swift-hornets-buy.md
packages/components/slider/src/range-slider.tsx
packages/components/slider/src/slider.tsx

Closes #372
Fixed an issue where the element was active even though `SliderThumb` input was disabled when `focusThumbOnChange` was set to `false`.
No

feat(slider): improved focus handling for sliders

---

.changeset/silly-oranges-move.md
packages/core/src/styles/interactivity.ts

Closes #419 
> Support `accent-color` property
> Nothing.
> able to use `accentColor`.
No.

feat: add `accent-color` property

---

.changeset/healthy-badgers-sparkle.md
packages/components/button/src/button.tsx
packages/components/close-button/src/close-button.tsx
packages/components/pagination/src/pagination-item.tsx
packages/components/ripple/src/use-ripple.ts
packages/components/tabs/src/tab.tsx

Closes #466
The behavior of ripple effects such as `Button` components is strange.
When you set a synchronous process such as `confirm` to `onClick` and click a `Button` component, the ripple effect is executed after confirmation.
Replace `onClick` with `onPointerDown`.
No

refactor(components): replace `onClick` with `onPointerDown`

---

.changeset/chatty-camels-ring.md
packages/components/autocomplete/src/autocomplete.tsx
packages/components/autocomplete/src/multi-autocomplete.tsx
packages/components/calendar/src/date-picker.tsx
packages/components/calendar/src/month-picker.tsx

Closes #484
`MultiAutocomplete` component tries to close the list every time I select from it.
When I click on an item in a list in a `MultiAutocomplete` component, I expected the list not to close, but the list tries to close on every click
Disabled `Portal` props by default.
No

fix(autocomplete/calendar): disabled `Portal` props by default

---

.changeset/lazy-garlics-brush.md
packages/theme/src/components/close-button.ts

Closes #488
`CloseButton` focus outline not working.
`CloseButton` component focus outline is not reflected correctly after sharing a theme with the `Button` component
Added focusVisible style to `CloseButton` component theme.
No

feat(theme): added `focusVisible` style to `CloseButton`

---

.changeset/ten-vans-enjoy.md
packages/components/indicator/src/indicator.tsx

Closes #493
Add `containerProps` to `Indicator` component
Currently, no way to customize elements of the `Indicator` component wrapper.
Added `containerProps` to `Indicator` component.
No

feat(indicator): added `containerProps` support

---

scripts/generate-css/check.ts
scripts/generate-css/layout-props.ts
scripts/generate-css/styles.ts

Closes #521
Added validation in generating CSS properties
Currently, we are automatically generating CSS properties, but we are not checking for shorthand duplicates.
Added validation in generating CSS properties
No

feat(scripts): add prop validation in CSS generation

---

.changeset/happy-turkeys-sing.md
packages/core/src/styles.ts
scripts/generate-css/shorthand-props.ts
scripts/generate-css/ui-props.ts

Added shorthand props
- `zIndex`: `z`
- `accentColor`: `accent`
- `caretColor`: `caret`
- `letterSpacing`: `tracking`
- `lineHeight`: `leading`
- `gap`: `g`
- `columnGap`: `gapX`, `gx`
- `rowGap`: `gapY` , `gy`
No

Added shorthand props

---

.changeset/smart-bulldogs-joke.md
packages/core/src/styles.ts
scripts/generate-css/config.ts
scripts/generate-css/exclude-props.ts
scripts/generate-css/styles.ts
scripts/generate-css/ui-props.ts

Closes #534
`colorScheme` type is incorrect
The type is an intersection type because the Yamada UI `colorScheme` and the CSS property `colorScheme` have duplicate names.
Added `colorMode` property.
No

Fix `colorScheme` type

---

.changeset/itchy-bulldogs-approve.md
.changeset/perfect-needles-sin.md
packages/core/src/components/use-component-style.tsx
packages/core/src/css/breakpoint.ts
packages/core/src/css/css.ts
packages/core/src/theme.ts
packages/core/src/theme.types.ts
packages/hooks/use-breakpoint/src/index.ts
packages/theme/src/config.ts

Closes #166
Allow `breakpoint` settings to be defined in the `config`.
Currently, Yamada UI's responsive design has a breakpoint set at max-width. Depending on the project you should be able to choose the min-width.
Added `breakpoint` to config.
No

Allow `breakpoints` to be selected up and down

---

.changeset/seven-phones-smile.md
.changeset/witty-gifts-exist.md
packages/components/button/src/button.tsx
packages/components/button/tests/button.test.tsx
packages/theme/src/components/button.ts

Closes #554
An error occurs when pressing the `Button` component repeatedly.
When keep clicking the `Button` component, the update frequency is too high and an error occurs on the React side.
Fixed a bug where the state was updated excessively in the ref of the `Button` component.
No

Fix `Button` component state.

---

.changeset/four-lobsters-help.md
.changeset/twenty-olives-brake.md
packages/components/segmented-control/src/segmented-control.tsx
packages/theme/src/components/segmented-control.ts

Closes #558
cursor element of `SegmentedControl` is hidden
When setting a `background` to the container element of `SegmentedControl`, the cursor element is hidden. This is a problem with the `z-index` of the cursor element.
Added `zIndex` to label element.
Update `zIndex` of cursor element.
No

Adjusted `SegmantedControl` component `zIndex`

---

.changeset/cool-kangaroos-hope.md
packages/components/rating/src/use-rating.tsx

Closes #573
`Rating` must only use allowed ARIA attributes
When setting `isReadonly` to `Rating` components, `aria-readonly` is assigned to unnecessary elements.
Removed unnecessary `aria-readonly`.
No

Fixed `aria-readonly` of `Rating`

---

.changeset/cool-parrots-exercise.md
packages/components/card/src/card.tsx

Closes #577
The rendered element of the `Card` component is incorrect.
The documentation explains that the `section` element is rendered in the `Cart` component, but in reality, the `div` element is rendered.
Fixed element type for Card component.
No

Fixed element type for Card component

---

.changeset/real-zebras-smash.md
.changeset/rotten-paws-perform.md
packages/cli/package.json
packages/cli/src/utils/prettier.ts
packages/core/src/generated-theme.types.ts
pnpm-lock.yaml

Closes #579
`Prettier` config is not referenced.
The config reference logic has changed since `Prettier` version 3.1.0, so it is always null.
Fixed a bug where `Prettier` config was not being referenced.
No

Fixed a bug where `Prettier` config was not being referenced.

---

.changeset/hip-dodos-type.md
packages/components/slider/src/range-slider.tsx
packages/components/slider/src/slider.tsx

Closes #583
`Slider` and `RangeSlider` must only use allowed ARIA attributes.
When setting `isReadonly` to `Slider` or `RangeSlider` components, `aria-readonly` is assigned to unnecessary elements.
Removed unnecessary `aria-readonly`.
No

Fixed `aria-readonly` of `Slider` and `RangeSlider`

---

packages/components/tooltip/src/tooltip.tsx

Closes #603 
> Fix bug . Tooltip should be not closed when click on trigger element. 
> Currently, when click on trigger element the tooltip will be hidden
> Tooltip not being hidden when click trigger element.
> no 
https://github.com/hirotomoyamada/yamada-ui/assets/78476413/1704638a-18f1-4543-91ea-1807967f4c7a

fix: not close tooltip on click

---

.changeset/early-planets-repair.md
.changeset/seven-apples-sleep.md
packages/components/calendar/src/multi-date-picker.tsx
packages/components/calendar/src/use-calendar-picker.ts
packages/components/calendar/src/use-range-date-picker.ts
stories/components/forms/date-picker.stories.tsx
stories/components/forms/multi-date-picker.stories.tsx
stories/components/forms/range-date-picker.stories.tsx

Close #619
Close #618
`hiddenOutsideDays` can not be set with `DatePicker` or `MultiDatePicker`.
Added `hiddenOutsideDays` to `getCalendarProps` in `useCalendarPicker`.
No

Fixed a bug in `RangeDatePicker`

---

.changeset/afraid-candles-carry.md
packages/components/tooltip/src/tooltip.tsx

Closes #630
fixed(tooltip) : Tooltip component onClose prop triggers on both open and close
Tooltip component onClose triggers on both open and close
Tooltip component onClose triggers only on close
No

fix(tooltip): Tooltip onClose prop triggers on both open and close #630

---

.changeset/thin-buttons-decide.md
packages/components/avatar/src/avatar.tsx

Closes #629
> Avatar component renders img internally but does not support crossOrigin.
> Avatar component don't have 'crossOrigin'
> Avatar component have 'crossOrigin'
No

fix: crossOrigin does not exist in Avatar

---

.changeset/serious-insects-develop.md
packages/theme/src/components/color-picker.ts
packages/theme/src/components/date-picker.ts
packages/theme/src/components/native-select.ts

Closes #665
When set `isReadOnly` to `ColorPicker` component, the placeholder style is reset.
`important!` was used in the placeholder style.
Removed `important!`.
No

Fixed `ColorPicker` component `isReadOnly` style

---

.changeset/purple-paws-peel.md
packages/components/color-picker/src/use-color-picker.ts

Closes #671
Alpha value is not displayed even if defaultColor is set
`calcFormat` return `hex` when only defaultColor is set
Pass the `defaultColor` as an argument to `calcFormat` when `defaultColor` is set
No

fix(color-picker): alpha value is displayed when default-color is set

---

.gitignore

Closes #690 
Added `.idea` to `.gitignore` file
When using WebStorm by JetBrains, it creates some project settings in the `.idea` folder, which should not be added to staged changes.
`.idea` folder is now ignored by git.

chore: add .idea to .gitignore

---

.changeset/tasty-avocados-bake.md
packages/theme/src/components/avatar.ts

Closes #631 
Fixed a bug where fontSize of excessive numbers in AvatarGroup is not set to theme sizes.
No

Fix : Fixed a bug where fontSize of excessive numbers in AvatarGroup is not set to theme sizes.

---

.changeset/shy-geese-return.md
packages/components/button/src/button.tsx

Closes #763 
Yamada UI allows you to use components without applying a theme. It is a mistake to use theme tokens inside components.
```ts
merge(styles._focus ?? {}, { zIndex: "yamcha" })
```
```ts
gap: "2",
```
```ts
merge(styles._focus ?? {}, { zIndex: 1 })
```
```ts
gap: "0.5rem",
```
No

fix:  `Button` component

---

.changeset/feat-is-rounded.md
packages/components/button/src/button.tsx
packages/components/button/src/icon-button.tsx

Closes #759
> I added `isRounded` to the `ButtonOptions` type.
> I added the appropriate css style.
> I removed `isRounded` from `IconButton`, because it inherited from `Button`
> `IconButton` has the `isRounded` props.
> `isRounded` inherited from the `Button`
No

feat: added isRounded to the button

---

packages/components/pin-input/tests/pin-input.test.tsx

Applied the following three fixes to the asynchronous tests in `@yamada-ui/pin-input`:
1. Added the necessary `await act(async() => {...})` where updates to React's state were missing.
3. Added the missing `await waitFor(() => {...})` for assertions in`test(async () => {})` statements.
4. Replaced with `getByXXXX` with `findByXXXX` for asynchronous tests.

fix(pin-input): some fixes about the asynchronous tests

---

packages/components/popover/tests/popover.test.tsx

Applied the following three fixes to the asynchronous tests in @yamada-ui/pin-input:
1. Added the necessary `await act(async() => {...})` where updates to React's state were missing.
2. Replaced with `getByXXXX` with `findByXXXX` for asynchronous tests.

fix(popover): some fixes about the asynchronous tests

---

.changeset/grumpy-windows-mate.md
packages/components/close-button/src/close-button.tsx

Closes #760 
> I added `isRounded` to the `CloseButtonOptions` type.
> I added the appropriate css style. 
```ts
...(isRounded
? { borderRadius: "9999px", border: "1px solid #000" }
: {}),
```
> `CloseButton` does not have `isRounded`.
> `CloseButton has `isRounded`.
No

feat: added isRounded to the close-button

---

.changeset/odd-squids-tell.md
packages/components/slider/src/range-slider.tsx

Closes #812 
Corrected an issue where range slider thumb icons were not shown.
Icons are not applied
Icons are applied
No

Fixed a bug where range slider thumb was not being applied

---

.changeset/spicy-tools-rule.md
packages/components/accordion/src/accordion.tsx

Closes #762
Fixed a bug where theme tokens were used in components.
No

Fixed a bug where theme tokens were used in components.

---

.changeset/tall-sheep-repeat.md
packages/utils/src/color.ts

Closes #829
Changed to correctly recognize `hex` values without `#`.
No

Changed to correctly recognize `hex` values without `#`.

---

.changeset/hot-donuts-clean.md
packages/theme/src/components/input.ts

Closes #814
Fixed a bug where when in dark mode, the focus border color of `Input` becomes thinner.
No

Fixed a bug where when in dark mode, the focus border color of `Input` becomes thinner

---

.changeset/spicy-tools-rule.md
.changeset/young-camels-drum.md
packages/components/color-picker/src/alpha-slider.tsx
packages/components/color-picker/src/color-selector-body.tsx
packages/components/color-picker/src/color-selector-swatches.tsx
packages/components/color-picker/src/color-swatch.tsx
packages/components/color-picker/src/hue-slider.tsx
packages/components/color-picker/src/saturation-slider.tsx

Closes #842 
ColorPickerのtokensを具体値に修正しました。
```
w: "full",
h: "full",
```
```
w: "100%",
h: "100%",
```

Fix/color picker/tokens

---

.changeset/good-crews-sip.md
packages/components/calendar/src/calendar-header.tsx
packages/components/calendar/src/date-picker.tsx
packages/components/calendar/src/month.tsx

Closes #841
fullとなっていた幅設定を100％に修正しました
`packages/components/calendar/src/calendar-header.tsx`
```tsx
const css: CSSUIObject = {
display: 'flex',
alignItems: 'center',
w: 'full',
...styles.header,
};
```
`packages/components/calendar/src/date-picker.tsx`
```tsx
<ui.input
ref={mergeRefs(ref, inputRef)}
className='ui-date-picker__field__input'
display='inline-block'
w='full'
{...computedInputProps}
/>
```
`packages/components/calendar/src/month.tsx`
```tsx
<ui.th
key={index}
__css={{
fontWeight: 'normal',
...styles.cell,
}}
{...thProps}>
<ui.div
className='ui-calendar__month__weekday'
__css={{
w: 'full',
display: 'flex',
...styles.weekday,
}}
{...computedWeekdayProps}>
{customWeekday({ weekday, index })}
</ui.div>
</ui.th>
```
`packages/components/calendar/src/calendar-header.tsx`
```tsx …
```

fix(calendar): fixed a bug where theme tokens were used in components

---

.changeset/wicked-colts-taste.md
packages/components/input/src/input-element.tsx

Hi, this is the PR for fixing one of the theme token bug.
Closes #839 
Fixed a bug where theme tokens were used in components.
Replace full to 100%.
No

fix(inputelement): fixed theme token usage in styles

---

.changeset/fifty-impalas-press.md
packages/components/reorder/src/reorder.tsx

Closes #852
Fixed a bug where `onCompleteChange` is executed even though no changes have been made.
No

Fixed a bug where `onCompleteChange` is executed even though no changes have been made

---

.changeset/purple-adults-draw.md
packages/components/indicator/src/indicator.tsx

<retry>
Hi!
Thanks for posting on Twitter!
I'm happy to try to contribute to this OSS for the first time.
We hope Yamada UI will be a success.
Closes:#840
I fixed a bug where theme tokens were used in components.
I replace from "full" to "100%".
No

fix:(Indicator) : theme token usage in styles 

---

packages/test/src/accessibility.tsx

* An unused type parameter was found in a statement extending Vitest matchers.
See: https://github.com/chaance/vitest-axe?tab=readme-ov-file#with-typescript

test(a11y): remove unused type parameter

---

.changeset/silent-windows-talk.md
.changeset/tidy-ads-unite.md
packages/components/autocomplete/src/autocomplete.tsx

Closes #832  
Autocompleteのtokensを具体的な値に変更しました
```
w: "full",
```
```
w: "100%"
```

fix(autocomplete): theme tokens bug

---

.changeset/stupid-deers-exercise.md
packages/components/color-picker/src/color-picker.tsx

Closes https://github.com/hirotomoyamada/yamada-ui/issues/862
Fixed colorPicker component to be displayed only in browsers that support eyedropper.
| safari (unsupported) | Chrome(supported) |
|--------|--------|
| <img width="891" alt="image" src="https://github.com/hirotomoyamada/yamada-ui/assets/83756829/4ea441e0-9413-4616-8257-d37ed50b3f93"> | <img width="891" alt="image" src="https://github.com/hirotomoyamada/yamada-ui/assets/83756829/ce7f6962-a31b-4447-92bf-a18cb866b914"> | 
| safari (unsupported) | Chrome(supported) |
|--------|--------|
|<img width="889" alt="貼り付けた画像_2024_02_29_23_45" …

fix: use eyeDropperSupported for color-picker

---

package.json
pnpm-lock.yaml

No packages depend on `@swc/core` directly, so I removed it.

build: remove `@swc/core` from workspace-root

---

package.json
pnpm-lock.yaml

* Removed `ts-node` because this package is no longer used.

build: remove `ts-node` (no longer used)

---

.changeset/cyan-glasses-pretend.md
.changeset/tame-terms-turn.md
packages/components/autocomplete/src/autocomplete-option.tsx
packages/components/autocomplete/src/use-autocomplete.tsx
packages/components/select/src/multi-select.tsx
packages/components/select/src/option.tsx
packages/components/select/src/select.tsx
packages/components/select/src/use-select.ts

Closes #882 
Closes #881 
Closes #880 
- Supported `ReactNode` in `label` of `items` and `Option` children.
- Fixed a bug where when a string was set to `icon` of `optionProps` or `Option`, the string was inserted into the input value.
No

Supported `ReactNode` and fixed a bug where inserted into the input value

---

vitest.config.mts

*  Glob patterns in `test.coverage.exclude` is fixed in this PR.
For example, we want `@vitest/coverage-v8` not to collect coverages of `packages/components/resizable/tests`.

test(vitest): fix glob patterns in `test.coverage.exclude`

---

.changeset/strange-students-hammer.md
packages/components/reorder/src/reorder.tsx

Closes #926
Fixed a bug where the sort order was not updated even if the `children` of `Reorder` were changed.
No

Fixed a bug where the sort order was not updated even if the `children` of `Reorder` were changed.

---

.changeset/forty-dragons-learn.md
packages/components/autocomplete/src/use-autocomplete.tsx

Closes #895
Fixed a bug where `defaultValue` or `value` was not inserted into input value when `allowFree` was `true`.
No

Fixed `allowFree` of `Autocomplate` and `MultiAutocomplete`

---

.changeset/dirty-owls-notice.md
packages/components/reorder/src/reorder.tsx

Closes #909 
Fixed a bug where theme tokens were used in the Reorder component.
No

fix(reorder): fixed theme token usage in styles

---

.changeset/afraid-adults-smoke.md
packages/components/modal/src/drawer.tsx

Fixed a bug where `placement` of types.
No

Fixed `placement` type exclusion in props

---

.changeset/curly-carrots-exist.md
.changeset/witty-falcons-run.md
packages/components/color-picker/src/alpha-slider.tsx
packages/components/color-picker/src/color-swatch.tsx
packages/components/layouts/src/stack.tsx
packages/components/snacks/src/snacks.tsx
packages/core/src/config.ts
packages/core/src/styles.ts
packages/theme/src/components/indicator.ts
packages/theme/src/components/stat.ts
scripts/generate-css/ui-props.ts

Closes #969
Fixed a bug where styles were not applied when the prefix of a css variable was changed.
No

Added `__prefix` to `var` props.

---

.changeset/blue-rings-care.md
packages/core/src/styles.ts
scripts/generate-css/tokens.ts
scripts/generate-css/transform-props.ts

Closes #983
Fixed a bug where `minBoxSize` and `maxBoxSize` do not refer to theme sizes tokens.
No

Fixed `minBoxSize` and `maxBoxSize` theme references

---

packages/components/file-input/src/file-input.tsx

* Added the missing `key` prop when executing `cloneElement`

fix(file-input): added the missing `key` prop when executing `cloneElement`

---

packages/components/button/src/button.tsx
packages/components/button/tests/button.test.tsx

Closes #979
fix _loading style is not applied.
styles not to be applied during loading,
styles to be applied during loading,
No

fix: Button component's_loading style is not applied.

---

.changeset/good-frogs-mate.md
packages/components/button/src/icon-button.tsx

Closes #980
Remove Unnecessary comment 
No

Remove Unnecessary comment

---

.changeset/healthy-spies-mix.md
packages/components/skeleton/src/skeleton.tsx

Closes #918 
Fixed a bug where theme tokens were used in components.
No

Fixed theme token usage in `Skeleton`

---

.github/workflows/quality.yml

There are many files with coverage not exceeding 80%, so we are not fully benefiting from Codecov. On the contrary, it is having a negative impact on the development speed. I would like to suspend the uploads of coverage to Codecov until the tests are adequately in place.

Stop uploading test coverages to Codecov temporarily

---

.changeset/eleven-scissors-breathe.md
packages/theme/src/components/line-chart.ts

Closes #1069 
以前の挙動が以下の画像の通りでしたが、
次のように折り返されるようになりました。
凡例が多い場合、挙動が変になる
たくさん凡例があってもきれいに表示されることを確認しました。
No

fix: made the legend wrap around

---

.changeset/swift-humans-approve.md
packages/components/input/src/input-element.tsx

Closes #1091 
used zIndex: 9
used zIndex: var(...)
No

fix: fixed zIndex default value for input-element

---

packages/components/calendar/tests/calendar.test.tsx

Closes #1115 
I specify the date, because `minDateUnderBtn` is null.
No
None

test(`Calendar`): specify the date

---

.changeset/tough-steaks-attack.md
packages/components/notice/src/notice-provider.tsx

Closes https://github.com/yamada-ui/yamada-ui/issues/1099
Apply theme's token to NoticeProvider component.
zIndex:160 and gap:1rem
zIndex:160 and gap:1rem changed to var(...)
No

Apply theme's token to NoticeProvider component

---

packages/hooks/use-os/tests/use-os.test.tsx

Closes #1052
Add tests for `useOS` (@yamada-ui/hooks).
Many of the UserAgents used in the test cases were picked from [this Gist](https://gist.github.com/pzb/b4b6f57144aea7827ae4?permalink_comment_id=4897643#gistcomment-4897643).

Add tests for `useOS`

---

.changeset/two-ears-listen.md
packages/components/reorder/src/reorder.tsx

Closes #1095
The Reorder component was previously ignoring theme tokens when applying  styling values. This commit address the issue by ensuring that theme tokens are used when a theme is applied.
The Reorder component was previously ignoring theme tokens when applying styling values.
Yamada UI's style system's fallback functions are utilized. If the value of the token in the first argument does not exist, it falls back to the second argument, which serves as the fallback value.
No

fix: fixed Use theme tokens for styling values in Reorder component

---

.changeset/thick-bottles-teach.md
packages/components/link/src/link-box.tsx

Closes #1086
Use the theme's token in the `LinkBox` component.
`zIndex` in the `LinkBox` component has been ignoring theme tokens.
Use the theme's token in the `LinkBox` component when a theme is applied.
No.

Use the theme's token in the LinkBox component.

---

packages/components/alert/src/alert.tsx
packages/components/markdown/package.json
packages/components/markdown/src/markdown.tsx
packages/components/markdown/src/patterns.ts
packages/components/markdown/src/remark-ui-component.ts
packages/components/markdown/src/utils.ts
packages/components/markdown/tests/with-note-components.test.tsx
pnpm-lock.yaml

Closes #379 
This PR will enable the Note syntax to be rendered as an Alert component even when line breaks are used within it.
When I wrote Markdown like the following, it did not render correctly as an Alert component.
```markdown
:::note 
This is the first text.
This is the second text.
:::
```
The above Markdown renders as intended;
Yes

[Markdown] Ensure rendering Alert component

---

.changeset/purple-olives-clean.md
packages/components/breadcrumb/src/breadcrumb.tsx

Closes #1093 
Use the theme's token in the `Breadcrumb` component if a theme is applied.
The theme's token in the `Breadcrumb` component is ignored.
The theme's token in the `Breadcrumb` component will properly be used when a theme is applied.
N/A

Use the theme's token in the `Breadcrumb` component

---

.changeset/six-ducks-remain.md
packages/components/toggle/src/toggle.tsx

Closes #1082 
> If a theme is applied, change to use the theme tokens
> styling values in components ignore theme tokens
>  If the value of the token in the first argument does not exist, it returns the second argument, the fallback value.
> No

fix: bugs where theme is not applied

---

.changeset/new-terms-refuse.md
packages/components/number-input/src/number-input.tsx

Closes #1085 
> use the theme's token in the number-input component
> z-index is described by number
> z-index is described by the theme's token
> No

fix: use the theme's token in the number-input component

---

.changeset/red-jeans-divide.md
packages/components/color-picker/src/color-swatch.tsx

Closes #1084
If a theme is applied, that use the theme's token.
If the value of the token in the first argument does not exist, it returns the second argument, the fallback value.
If the value of the token in the first argument does not exist, it returns the second argument, the fallback value.
No

fix: theme token in ColorSwatch

---

packages/hooks/use-eye-dropper/tests/index.test.ts

Closes #1046
Added tests for `useEyeDropper` hook.
No

Added tests for `useEyeDropper` hook

---

.eslintrc

Related #1119 
Add [`testing-library/no-await-sync-queries`](https://github.com/testing-library/eslint-plugin-testing-library/blob/main/docs/rules/no-await-sync-queries.md) to `.eslintrc`
There are no changes to the test code, but the aim is to prevent any inappropriate descriptions in the test code that will likely be added in the future.

test(eslintrc): add testing-library/no-await-sync-queries

---

examples/hono/src/client.tsx
examples/hono/src/index.tsx

Closes #1186 
Fixed `examples/hono` flashes in color mode.
`Hono` example flashes when reloading.
`Hono` example no longer flashes when reloading.
No

fixed `examples/hono` flashes in color mode

---

.changeset/calm-zebras-fix.md
packages/components/menu/src/menu-option-group.tsx

Closes #1197
Fixed `defaultValue` in `MenuOptionGroup`.
No

Fixed `defaultValue` in `MenuOptionGroup`

---

.changeset/small-foxes-care.md
packages/theme/src/components/menu.ts

Closes #1200
Fixed disabled `MenuItem` hover/focus styles.
No

Fixed disabled `MenuItem` hover/focus styles

---

.changeset/late-scissors-retire.md
packages/components/card/src/card.tsx
packages/components/card/tests/card.test.tsx

Closes #1237
Changed the tag of the Card component from section to article.
- `Card` rendered by section tag.
-  `CardHeader` and `CardFooter` rendered div tags.
- `Card` render by article tag.
-  `CardHeader` render by header tag.
-  `CardFooter` render by footer tag.
No
None

Changed the tag of the Card component from section to article

---

.changeset/blue-lemons-repair.md
.changeset/lemon-needles-tickle.md
.changeset/tiny-countries-push.md
.eslintrc
packages/core/src/generated-theme.types.ts
packages/core/src/theme.ts
packages/core/tests/merge-style.test.ts
packages/utils/src/object.ts
packages/utils/tests/object.test.ts

Closes #1284
Supported for nested keys in `pickObject` and `omitObject`.
No

Supported for nested keys in `pickObject` and `omitObject`

---

.changeset/ten-hotels-yawn.md
packages/core/src/theme.types.ts

Closes #1303  
Fixed a bug where TextStyles and LayerStyles have more types than necessary.
Fixed the type of TextStyles and LayerStyles so that only objects should be accepted according to issue.

fix: fixed type of TextStyles and LayerStyles

---

stories/components/overlay/menu.stories.tsx

Closes #1250 
In `Menu` component's Storybook cases, withIcon and withCommand, `MenuButton` lacked discernible text, causing an a11y violation. To address this issue, I added the `aria-label` attribute to provide a text alternative for screen readers.
`With Command`
1 Violations
`With Icon`  
1 Violations  
`With Command`  
0 Violations  
`With Icon`
0 Violations  
No

fix: add `aria-label` to `menu` in storybook for a11y

---

.changeset/twenty-tips-push.md
packages/components/calendar/src/month.tsx

Closes #1254 
If a custom component was a not displayed element (e.g. null, undefined, boolean), there was no identifiable text in the button (calendar__month__day), causing an a11y violation. To address this issue, the custom component now sets `display: none` when the element is not displayed.
`Custom Day Button`
`Custom Day Button`
No

fix: hidden button(calendar__month__day) if the custom component is a not displayed element for a11y

---

.changeset/tricky-papayas-occur.md
packages/core/src/theme.ts

Closes #1311
Updated `omitThemeProps` to support custom keys.
No

Updated `omitThemeProps` to support custom keys.

---

stories/components/forms/color-picker.stories.tsx

Closes #1241 
In Menu component's Storybook 15 cases, `colorPicker` lacked discernible text, causing an a11y violation. To address this issue, I added the `placeholder` attribute to provide a text alternative for screen readers.
Here are the test results when running test-storybook limited to
`stories/components/forms/color-picker.stories.tsx:`
(Error details are omitted. Issue: #1241  )
```
$ pnpm test-storybook
The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
FAIL   browser: chromium  stories/components/forms/color-picker.stories.tsx (19.835 s)
● Components / Forms / ColorPicker › withDefaultValue › smoke-test
● Components / Forms / ColorPicker › withFallbackValue › smoke-test
● Components / …
```

fix: add `placeholder` to `colorPicker` in storybook for a11y

---

packages/hooks/use-resize-observer/tests/index.test.tsx

Closes #1054  
This teste is that useResizeOver returns rect correctly when used on a component with useResizeOver's ref.
Since global.ResizeObserver is mock, I confirmed that Rect refers to the value of ResizeObserverEntry.contentRect

test(useResizeObserver): enhanced test coverage

---

.changeset/large-wombats-dream.md
packages/components/file-input/src/file-input.tsx

Closes #1320
Fixed a bug where `aria-readonly` was assigned to an element even though the `readOnly` attribute was not assigned.
No

Removed incorrect `aria-readonly` attribute

---

.changeset/tidy-years-reflect.md
packages/components/image/src/image.tsx

Closes #1321 
- https://github.com/yamada-ui/yamada-ui/issues/1321
This PR updates the `Image` component, refining the handling of fallback images based on image load states and errors. It specifically adjusts property handling in the `useImage` hook and modifies the conditional prop spreading in the image rendering logic.
Currently, the `Image` component might not correctly handle `crossOrigin` attributes when determining image statuses, and its conditional prop spreading logic in the rendering phase can be misleading, causing `onError` and `onLoad` to be omitted unpredictably.
- **Include `crossOrigin` in `useImage` Hook:** Ensures that `crossOrigin` is considered in the image loading process, enhancing adherence to security and access policies.
- **Adjusted Conditional Rest Spread …

refactor: delete the redundant the omitObject function

---

.changeset/wild-windows-refuse.md
packages/components/table/src/paging-table.tsx

Closes #1326 
Integrate `omitObject` handling with `omitThemeProps`.
No

Integrate `omitobject` handling with `omitthemeprops`

---

scripts/observe-pull-requests.ts

Closes #1522
With this PR, assigning reviews will be less biased as it will cycle through maintainers who doesn't have a PR to review.
Some maintainers are not getting review assigned due to how we pick reviewers randomly.
Excludes maintainer if they already have a PR to review.
No

Exclude maintainer if already has a PR to review

---

.changeset/tough-apricots-fly.md
packages/components/markdown/src/remark-ui-component.ts
packages/components/markdown/tests/with-note-components.test.tsx

With this PR, the following Markdown will render as shown in the following image.
```markdown
:::note status=error
Status is **error**.
:::
```

feat(markdown): enable use of strong syntax (`**`) within note syntax

---

.changeset/six-waves-switch.md
packages/components/menu/src/menu-option-group.tsx

Closes #1328  
Removed unnecessary `omitObject` in the `MenuOptionGroup` component to integrate its handling with `omitThemeProps`. 
No

refactor(menuoptiongroup): integrate `omitObject` handling with `omitThemeProps`

---

packages/hooks/use-clickable/tests/index.test.tsx

Closes # #1041 
Add test for `use-clickable`
none
none

Add Test for `@yamada-ui/use-clickable`

---

packages/hooks/use-outside-click/tests/index.test.tsx

Closes #1469
Added tests for `useOutsideClick` hook.
No

Added tests for `useOutsideClick` hook

---

.changeset/sweet-items-try.md
packages/theme/src/components/multi-select.ts

Closes #1582
Corrected readOnly behavior in `MultiSelect`.
No

Corrected readOnly behavior in `MultiSelect`

---

packages/hooks/use-size/tests/index.test.tsx

Closes #1470
Add tests for `useSizes` and `useSize` hooks.
No

Add tests for `useSizes` and `useSize` hooks

---

packages/components/icon/tests/icon.test.tsx

Fix: `packages/components/icon/tests/icon.test.tsx(2,10): error TS2724: '"react-icons/md"' has no exported member named 'Md3dRotation'. Did you mean 'Md3DRotation'?`

test(icon): replace `Md3dRotation` with `FaMarkdown`

---

scripts/coverage-issues.ts

Closes #1624
Fixed incorrect percentage of coverage issue.
`TARGET_COVERAGE` is now displayed.
NIL
NIL
No

Fixed incorrect percentage of coverage issue

---

docs/components/navigation/tabs.tsx

Closes #1661
Fixed document `Tabs` active indicator.
Fixed to show active indicator even with query.
No

Fixed document `Tabs` active indicator

---

.changeset/fresh-emus-press.md
docs/contents/components/disclosure/tabs/props.ja.mdx
docs/contents/components/disclosure/tabs/props.mdx
packages/components/tabs/DOCS.json
packages/components/tabs/src/tabs.tsx

Closes #1664
This PR fixes the full-width spaces to be half-width.
There were full-width spaces in English sentences.
It is now half-width spaces.
No

Made full-width spaces a half-width in `Tabs` documentation

---

packages/components/slider/tests/range-slider.test.tsx

Closes #1648 
There is a cleanup in the range-slider test code. We think that cleanup should be removed since it is now in the library.
remove `cleanup` and add `rerender` 
No

fix: remove `cleanup` & add `rerender`

---

packages/components/toggle/tests/toggle-group.test.tsx

Closes #1649
There is a cleanup in the `toggle-group` test code. We think that cleanup should be removed since it is now in the library.
No.

Remove `cleanup` in `toggle-group` test code

---

packages/components/pin-input/tests/pin-input.test.tsx

Closes #1687
warning happened below. remove act.
```
stderr | packages/components/pin-input/tests/pin-input.test.tsx > <PinInput /> > allows alphanumeric input when type is "alphanumeric"
Warning: The current testing environment is not configured to support act(...)
Warning: The current testing environment is not configured to support act(...)
```

fix: remove act

---

packages/components/color-picker/tests/color-picker.test.tsx

Closes #1452 
I tested that when 'disabled' is provided, ColorPicker becomes disabled, and when 'isOpen' is provided, the popover is initially displayed.

Updated `color-picker` test

---

.changeset/friendly-lemons-suffer.md
packages/components/tooltip/src/tooltip.tsx
packages/theme/src/components/tooltip.ts

Closes #1912 
Make tooltip component headless.
The current `@yamada-ui/tooltip` component has minimal styles defined within its source code. These styles are applied directly within the component, which limits the flexibility of UI customization across different projects. The styles are primarily defined by a CSSUIObject and set to a prop named `__css`.
This PR refactors the `@yamada-ui/tooltip` component to be headless, transferring the internal styles to the theme package. The styles previously defined within the component are now moved to `packages/theme/src/components`, allowing for more flexible and project-specific UI customization. This change ensures that the component can be styled through the theme, promoting a more consistent and adaptable design approach across various …

Make tooltip component headless

---

.changeset/funny-ducks-stare.md
.changeset/mighty-apples-ring.md
packages/components/table/src/table.tsx
packages/theme/src/components/table.ts

Closes #1907 
Currently, the `@yamada-ui/table` component has minimal styles set within the component's source code.
We want to make this style transferable to the theme and make the component headless, enabling more flexible UI customization.
No

Make the `table` component headless

---

.changeset/tasty-laws-joke.md
packages/components/menu/src/menu-button.tsx
packages/components/menu/src/menu-item.tsx
packages/theme/src/components/menu.ts

Closes #1881
Currently, the `@yamada-ui/menu` component has minimal styles set within the component's source code.
We want to make this style transferable to the theme and make the component headless, enabling more flexible UI customization.
No.

Make the `menu` component headless

---

.changeset/rare-rivers-doubt.md
packages/components/pin-input/src/pin-input.tsx
packages/theme/src/components/pin-input.ts

Closes #1889 
Currently, the `@yamada-ui/pin-input` component has minimal styles set within the component's source code.
We want to make this style transferable to the theme and make the component headless, enabling more flexible UI customization.
No

refactor: make the `pin-input` component headless

---

.changeset/polite-pens-joke.md
packages/hooks/use-pan-event/src/index.ts

Closes #1953
Fixed a bug that caused event processing to not occur due to incorrect usage of `cancelSync`.
In rare cases, `onStart`, `onEnd`, etc. may not work.
No.
`cancelSync` is a function to cancel processing during processing registered with `sync.update`, etc.
```ts
import sync, { cancelSync } from 'framesync';
let count = 0;
const process = sync.render(() => {
count++;
if (count >= 10) cancelSync.render(process);
}, true);
```

fix(use-pan-event): remove unnecessary `cancelSync`

---

docs/contents/components/data-display/list/index.mdx

Closes #2183 
Fix typo `check` to `Check`.
No
None

Fix a typo about `check` in `List` component

---

docs/contents/components/forms/dropzone/index.ja.mdx
docs/contents/components/forms/dropzone/index.mdx

Closes #2185
This PR makes the description use \`\` for `Dropzone`.
The documentation did not have \` around the word `Dropzone` properly.
Makes them \`Dropzone\`.
No

docs(dropzone): added ` to description

---

scripts/report-insights.ts

Closes #2295
I have made the report insights script work properly with `publish` option.
It tried to send discord message regardless of `publish` option.
It will console.log the report if `publish` is false.
No

refactor(report-insights): made `publish` option work in report insight script

---

vitest.config.mts

When you do a test that expects an error to be thrown, the error is what you expect, but the error is displayed in the console and the log is tainted.Use `onConsoleLog` to disable the display of errors.
No

Added `onConsoleLog` filter for stderr

---

packages/components/close-button/tests/close-button.test.tsx

The name of test folder is not `tests` but `test` in `@yamada-ui/close-button`.

test(close-button): rename `test` to `tests`

---

packages/hooks/use-size/tests/index.test.tsx

Closes #2360 
Enhance Test Coverage for `@yamada-ui/use-size` up to about 98%  and  Refactor.
I defined a mock of ResizeObserver.
I successed in enhancing test coverage, but I couldn't define the mock entirely. So there is a test which is skipped in  `packages/hooks/use-size/tests/index.test.tsx`

Enhance Test Coverage for `@yamada-ui/use-size`

---

docs/pages/insights/index.page.tsx

Updated default start date calculation.
Currently, the default value is 1 week, but 8 days have been selected.
No

Updated default start date calculation

---

.changeset/bright-tigers-lick.md
.changeset/green-berries-leave.md
packages/components/autocomplete/src/autocomplete-list.tsx
packages/components/select/src/select-list.tsx

Closes #2443
Fixed a bug where the width was not changed even if `width` etc. was set in `listProps` of `Select` and `MultiSelect`.
No

Fixed a bug where the width was not changed even if `width` etc. was set in `listProps` of `Select` and `MultiSelect`.

---

packages/components/menu/tests/menu.test.tsx

Closes #2489
This pull request addresses an issue where deprecated `size` props were being used in the `Menu` component's test code. The `size` prop has been replaced with `fontSize` to align with the current API standards.
Currently, the `Menu` component's test code uses the deprecated `size` prop, which is no longer supported and should be replaced with `fontSize`.
The `Menu` component's test code now uses the `fontSize` prop instead of the deprecated `size` prop, ensuring compatibility with the current API.
No
No additional information.

Fix deprecated `size` prop usage in `Menu` test code

---

stories/components/feedback/loading.stories.tsx

Closes #2485 
Replaced the deprecated `size` prop with fontSize in the Storybook `Loading` page.
Currently, the `Loading` component uses the deprecated `size` prop in the Storybook `Loading` page.
The `Loading` component now uses the `fontSize` prop in the Storybook `Loading` page.
No
None

Fix deprecated `size` props usage in the Storybook `Loading` page

---

stories/system/theme/loading.stories.tsx

Closes https://github.com/yamada-ui/yamada-ui/issues/2508
- As the subject suggests, I have changed the deprecated size prop in the Loading component to fontSize.
- None
- None
- No
- None

refactor: Deprecated props are being used in the Storybook Theme/Loadingpage.

---

.changeset/two-fishes-juggle.md
packages/core/src/config.ts
packages/core/src/constant.ts
packages/core/src/css/css.ts
packages/core/src/css/var.ts

Closes #2548
Add support for CSS variable parsing with `$` symbol.
No

Add support for CSS variable parsing with `$` symbol

---

docs/pages/examples/music/content.tsx

Remove 'size' from CarouselItem props.
```
Run pnpm docs:content
> yamada-ui@1.0.0 docs:content /home/runner/work/yamada-ui/yamada-ui
> pnpm --prefix docs gen:content
> yamada-docs@1.0.0 gen:content /home/runner/work/yamada-ui/yamada-ui/docs
> tsx scripts/mdx/builder
generated 967 files
> yamada-ui@1.0.0 docs:typecheck /home/runner/work/yamada-ui/yamada-ui
> pnpm --prefix docs typecheck
> yamada-docs@1.0.0 typecheck /home/runner/work/yamada-ui/yamada-ui/docs
> tsc --noEmit
Error: pages/examples/music/content.tsx(334,44): error TS2322: Type 'UIValue<string>' is not assignable to type '(UIValue<string> & ("sm" | "md")) | undefined'.
Type 'string' is not assignable to type '(UIValue<string> & ("sm" | "md")) | undefined'.
 ELIFECYCLE  Command failed with exit code 2.
 ELIFECYCLE  Command …
```

Remove 'size' from CarouselItem props

---

.github/workflows/quality.yml

Removed `changeset-release/docs` branch trigger.
Pull requests directed to `changeset-release/docs` will not be created and are not required.
No

Removed `changeset-release/docs` branch trigger

---

packages/components/popover/tests/popover.test.tsx

Closes https://github.com/yamada-ui/yamada-ui/issues/2070
Add tests for animation for the Popover component
Target: [packages/components/popover/src/popover-content.tsx](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/popover/src/popover-content.tsx)
- [L37](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/popover/src/popover-content.tsx#L37)
- [L42](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/popover/src/popover-content.tsx#L42)
- [L47](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/popover/src/popover-content.tsx#L47)
- [L52](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/popover/src/popover-content.tsx#L52)
No
I accidentally closed the …

test: add tests for popover animation

---

docs/contents/components/overlay/popover/index.ja.mdx
docs/contents/components/overlay/popover/index.mdx

Closes #2666 
I have replaced `Menu` with `Popover` in the `Popover` docs.
No

docs: replace `Menu` with `Popover` in `Popover`

---

docs/components/navigation/table-of-contents.tsx

Closes #2684
Fixed a bug where the right navigation item was not clickable.
`pointerEvent` was set to `none`, which prevented the click.
Cannot click on right navigation item.
The right navigation item has been modified to be clickable.
No

Fixed a bug where the right navigation item was not clickable

---

.changeset/spicy-donkeys-appear.md
packages/components/infinite-scroll-area/src/infinite-scroll-area.tsx

Closes #2701
Removed unnecessary `tabIndex` attribute.
No

Removed unnecessary `tabIndex` attribute

---

.changeset/warm-socks-live.md
packages/components/popover/src/popover-content.tsx
packages/theme/src/components/menu.ts

Closes #2837
Fixed outline display on focus for menu elements.
No

Fixed outline display on focus for menu elements

---

.changeset/curvy-sloths-sing.md
packages/components/textarea/src/textarea.tsx

Closed #2911
The component "@yamada-ui/textarea" uses forwardRef, but displayName is not set, making it difficult to see the display in [React Developer Tools](https://github.com/facebook/react/tree/main/packages/react-devtools).
Set displayName.
No

fix: set display-name in `textarea` component

---

.changeset/few-squids-exercise.md
packages/components/modal/src/modal-overlay.tsx

Closes #2918 
fix ModalOverlay height.
changed css from
h: "100vh",
changed css to
h: "100dvh",
No

fix: fix ModalOverlay height

---

.changeset/unlucky-balloons-cheer.md
packages/components/tooltip/src/tooltip.tsx

Closes #2913
add displayName and ui to tooltip component.

fix: add displayName and __ui__ to tooltip component

---

.changeset/loud-toys-clean.md
packages/components/scroll-area/src/scroll-area.tsx

Closes #2899 
Set `displayName` and `__ui__`.

feat: set display name and UI for scroll-area

---

.changeset/nasty-cobras-divide.md
packages/components/focus-lock/src/focus-lock.tsx

Closes #2866 
Set `displayName` and `__ui__` after focus-lock and add import from `@yamada-ui/core`

feat: set display name and UI for focus-lock

---

.changeset/chilly-spies-approve.md
packages/components/checkbox/src/checkbox-group.tsx
packages/components/checkbox/src/checkbox.tsx

Closes #2859 
Set displayName and __ui__ after each component for checkbox

fix: set displayname and __ui__ to checkbox

---

.eslint/testing-library.ts
packages/components/file-button/tests/file-button.test.tsx
packages/components/pin-input/tests/pin-input.test.tsx
packages/components/snacks/tests/snacks.test.tsx
packages/components/table/tests/table.test.tsx

Closes https://github.com/yamada-ui/yamada-ui/issues/2719
We are introducing the ESLint rule testing-library/no-wait-for-multiple-assertions to automate a check that we currently perform manually during code reviews.
This rule prevents multiple assertions within a single waitFor call in our tests.
No
Ran `pnpm lint` and `pnpm test` and confirmed all checks passed successfully.

Add `testing-library/no-wait-for-multiple-assertions` to ESLint rules

---

.changeset/mighty-elephants-own.md
packages/components/highlight/src/highlight.tsx

Closes #2869  
Set the `displayName` and `__ui__` for `@yamada-ui/highlight`
No

fix: set the `displayName` and `__ui__` for `@yamada-ui/highlight`

---

.changeset/honest-bulldogs-end.md
packages/components/segmented-control/src/segmented-control.tsx

Closes #2900 
Set `displayName` and `__ui__` for the `@yamada-ui/segmented-control` component to make debugging easier.
This change improves the ability to identify the component name in development tools.

Feat/set display name and UI for segmented control

---

packages/create-yamada-app/src/templates/gatsby/package.json
packages/create-yamada-app/src/templates/hono/package.json
packages/create-yamada-app/src/templates/next/app/package.json
packages/create-yamada-app/src/templates/remix/package.json
packages/create-yamada-app/src/templates/vite/package.json

Closes # nothing
`@yamada-ui/lucide` was missing from `package.json` of each template.
Added `@yamada-ui/lucide` to each template.

(create-yamada-app)updated `package.json` add `@yamada-ui/lucide`

---

.changeset/early-gorillas-lay.md
packages/components/color-picker/src/hue-slider.tsx
packages/components/color-picker/src/saturation-slider.tsx

Closes https://github.com/yamada-ui/yamada-ui/issues/2830
Incorrect JSDoc Comment Placement in SaturationSlider and HueSlider
The JSDoc Comment Placement in SaturationSlider and HueSlider is at the wrong spot.
I have moved the JSDoc comments to the component definitions
No

refactor(color-picker): move JSDoc comments to component definitions

---

.changeset/fluffy-avocados-mix.md
packages/components/autocomplete/src/use-autocomplete-option.ts
packages/components/select/src/use-select.ts
stories/components/forms/select.stories.tsx

Closes #2826 
Closes #2827
When the option `value` is not set, the value of `children` is automatically set.
No

When the option `value` is not set, the value of `children` is automatically set

---

packages/utils/src/color.ts

Removed `"mono"` from SEMANTIC_COLOR_SCHEMES.
The `"mono"` value is not needed because it is not yet implemented.
No

Removed `"mono"` from SEMANTIC_COLOR_SCHEMES

---

.changeset/soft-games-unite.md
packages/components/layouts/src/aspect-ratio.tsx
packages/components/layouts/src/box.tsx
packages/components/layouts/src/center.tsx
packages/components/layouts/src/container.tsx
packages/components/layouts/src/divider.tsx
packages/components/layouts/src/flex.tsx
packages/components/layouts/src/grid.tsx
packages/components/layouts/src/spacer.tsx
packages/components/layouts/src/stack.tsx

Closes #2876
Added displayName and __ui__ to layout components 
No

fix: add displayName and __ui__ to layout components

---

packages/create-yamada-app/src/templates/next/pages/next.config.mjs
packages/create-yamada-app/src/templates/next/pages/package.json

Closes # nothing
next pages project specify the version in package.json as "workspace:*"

(create-yamada-app)next pages project specify the version in package.json as `workspace:*`

---

docs/contents/components/forms/file-button/accessibility.ja.mdx

Closes #3103
Accessibility tab of FileButton component in ja page is written in english.
`ARIA Roles and Attributes` and table columns should be japanese.
Accessibility tab of FileButton component in ja page is written in english.
`ARIA Roles and Attributes` and table columns are now using japanese.
No

docs(fileButton): use japanese translation on accessibility section

---

packages/components/icon/tests/icon.test.tsx

Closes #3270
Enhance test coverage for `icon` component
There are not enough tests covering for `icon` component
Add a new test case to ensure `CheckIcon`, `InfoIcon`, `WarningIcon`, `CloseIcon`, `ChevronIcon` are rendering correctly and pass the a11y test
No

test(icon): enhance test coverage for icon

---

.changeset/shy-moles-own.md
packages/components/icon/src/icon.tsx

Closes #3258
Enhanced a11y in the Icon component by setting role="img" and applying aria-hidden="true" as defaults.
No

feat: enhance Icon component a11y

---

packages/hooks/use-async-callback/tests/index.test.tsx

Closes #3307
Add `waitFor` to async tests.
No

Add `waitFor` to async tests

---

.changeset/rich-trains-run.md
packages/components/select/src/use-select.tsx
packages/components/select/tests/select.test.tsx

Related https://github.com/yamada-ui/yamada-ui/issues/2059
It is written in `multiSelect` issue, but actually relates to `select` and `multiSelect`.
- Alt + ArrowUp
If the popup has focus, returns focus to the combobox, otherwise it closes the popup.
- Alt + ArrowDown
If the popup is available but not displayed, displays the popup without moving focus.
Other accessibility support will be provided in a separate PR.
No

improve keyboard navigation and accessibility

---

.changeset/itchy-bottles-allow.md
packages/components/rating/package.json

Closes #3325
Error occurs in Next.js 15 because `Rating` component does not have `"use client"`.
`Rating` component does not have `"use client"`.
Added `"use client"` to `Rating` component.
No

Added `"use client"` to `Rating`

---

.changeset/famous-melons-call.md
packages/components/color-picker/src/alpha-slider.tsx
packages/components/color-picker/src/hue-slider.tsx
packages/components/color-picker/src/use-color-slider.ts

Closes #2085 
Add aria-valuetext to hueSlider to eliminate accessibility issues.
In implementing aria-textvalue, we implemented the colorName function to get the name of the color.

refactor: Update HueSlider accessibility 

---

examples/next/pages/pages/index.tsx

Related #3072 
Remove the `Slider' and `RangeSlider' test code that remains in the next-pages example.
No

Remove unnecessary code in next pages example

---

.changeset/brave-years-train.md
packages/components/color-picker/src/color-picker.tsx
packages/components/color-picker/src/use-color-picker.ts
packages/components/color-picker/tests/color-picker.test.tsx

Closes #2924
Added role and aria-controls to ColorPicker
The `input` tag in the `ColorPicker` component doesn't have the `combobox` role and `aria-controls`.
The `input` tag in the `ColorPicker` component have the `combobox` role and `aria-controls`.
No

fix(colorPicker): added necessary aria attribute to ColorPicker

---

.changeset/proud-doors-shake.md
.changeset/sweet-chicken-begin.md
package.json
packages/components/alert/package.json
packages/components/alert/src/alert.tsx
packages/components/alert/tests/alert.test.tsx
packages/components/icon/src/icon.tsx
pnpm-lock.yaml

Closes #3474
Since it is difficult to improve the content of the current issue, I have ported only the necessary icon data from `@yamada-ui/lucide` to `@yamada-ui/icon`.
I will improve this in `v2.0`.
No

Replaced lucide icon to internal icon

---

.changeset/stale-singers-joke.md
packages/components/link/src/link-box.tsx
packages/components/link/src/link.tsx
packages/components/link/tests/link.test.tsx
stories/components/data-display/table.stories.tsx
stories/components/navigation/link-box.stories.tsx
stories/components/navigation/link.stories.tsx

Closes #3522 
Removing all is prefix from is*.
Before: `isExternal`
After: `external`
No

`Link`: remove is prefix in props

---

.changeset/neat-suns-pay.md
packages/components/highlight/src/highlight.tsx

Closes #3544
Removing all is prefix from is*.
Before: `isFragment`
Aefore: `fragment`
No

feat(highlight): remove is prefix in props

---

.changeset/tricky-gifts-hear.md
packages/components/tabs/src/tab-panel.tsx
packages/components/tabs/src/tab-panels.tsx
packages/components/tabs/src/tab.tsx
packages/components/tabs/src/tabs-context.tsx
packages/components/tabs/src/tabs.tsx
packages/components/tabs/tests/tabs.test.tsx
packages/hooks/use-clickable/src/index.ts
stories/components/disclosure/tabs.stories.tsx

Closes #3498 
Removing all `is` prefix from `is*`
Before: isFitted, isLazy, isManual
After: fitted, lazy, manual
No

`Tabs`: remove `is` prefix in props

---

docs/scripts/component/props.ts

Closes #3667
I have fixed the props docs generation script that was not working properly for Windows.
It did not replace `\` with `/`.
The script replaces `\` with `/` when it runs `path.join`.
No
N/A

Fix props doc generation script for windows

---

.changeset/tame-hornets-argue.md
packages/hooks/use-animation/src/index.ts

Closes #3805
Removing all is prefix from is*.
No

feat(use-animation): remove is prefix from props

---

.changeset/shiny-ghosts-burn.md
packages/components/charts/src/chart.types.ts

Closes #3607
Fixed wrong `ChartTooltip` type.
Attempted to get `fill` prop from `payload` in chart tooltip, type error occurred.
No

fix(charts): fixed types

---

.changeset/itchy-dryers-burn.md
packages/utils/src/color.ts

Closes #3831  
Refactor `convertColor` to replace lookbehind in regular expression
Replaced the lookbehind assertion in the `convertColor` function's `hexa.replace` logic with a more compatible regular expression pattern. The original lookbehind `/(?<=^#([0-9a-fA-F]{6}))[0-9a-fA-F]{2}$/` was not supported in some environments, causing compatibility issues. The updated pattern `/^#(?:[0-9a-fA-F]{6})[0-9a-fA-F]{2}$/` uses a non-capturing group and matches the entire string without relying on lookbehind. This change ensures broader compatibility across different JavaScript engines.

Refactor `convertColor` to replace lookbehind in regular expression.

---

.changeset/rare-sloths-exist.md
packages/theme/src/components/menu.ts
packages/theme/src/components/select.ts

Closes #3571 
Change `background color` for `disabled` items in `Select` when hovered and focused.
`Autocomplete` inherits `Select` `theme`, so `Select` `theme` is modified
When hovering over `focusable` with `disabled`, the `background color` on focus is lost.
https://github.com/user-attachments/assets/d276687f-806d-4e5b-8ebd-c48cb462b55b
When hovering over `focusable` with `disabled`, the same background color is applied as for normal focus.
https://github.com/user-attachments/assets/bd5227a5-04bb-4d94-ad1b-8e3244fab58a
No

fix: adjust hover background colors for disabled/focus item

---

.changeset/nervous-ways-heal.md
packages/components/resizable/src/resizable.tsx
packages/components/resizable/src/use-resizable.ts
packages/theme/src/components/resizable.ts

Closes #3516 
- Rename direction to orientation in yamada-ui/resizable
- add deprecate to direction
No

feat: rename `direction` to `orientation` in `yamada-ui/resizable`

---

packages/components/stat/src/stat-icon.tsx
packages/theme/src/components/stat.ts

Closes #3532 
Replace `StatIcon` with `TriangleIcon` from `@yamada-ui/lucide`.
The theme was also modified to match the current icon look and feel.
No

Replace `StatIcon` with `TriangleIcon` from `@yamada-ui/lucide`

---

docs/contents/components/overlay/dialog/index.ja.mdx
docs/contents/components/overlay/dialog/index.mdx

Closes #3769 
The part using `map` was rewritten as `For`.
No
Since I was told last time that there is no need to use `For` forcibly in `useTheme`, I use `For` only in the parts where `map` was used. I didn't think it was necessary to use a loop for the other parts.

Use `For` in `dialog` documentation

---

packages/react/src/components/autocomplete/autocomplete-create.tsx
packages/react/src/components/autocomplete/autocomplete-empty.tsx
packages/react/src/components/autocomplete/autocomplete-icon.tsx
packages/react/src/components/autocomplete/autocomplete-option.tsx

Closes #3534  
Replaced by `LucideIcon`

fix: replaced icon in `Autocomplete`

---

packages/react/src/components/avatar/avatar.stories.tsx
packages/react/src/components/avatar/avatar.tsx

Closes #3852 
This PR is to rename internal variables (remove `is` prefix) and fix storybook typo only, since there are no deprecated props.
No

`avatar`: remove deprecated props

---

.changeset/great-turkeys-sparkle.md
.changeset/silly-moose-fetch.md
.changeset/young-tigers-warn.md
packages/components/layouts/src/stack.tsx
packages/components/markdown/src/markdown.tsx
packages/components/motion/src/motion.types.ts
packages/components/popover/src/popover-anchor.tsx
packages/components/popover/src/popover-trigger.tsx
packages/components/tooltip/src/tooltip.tsx
packages/core/src/components/component.types.ts
packages/utils/src/react.tsx

Closes #3248
Closes #3835
- I have solved the `ref` problem in React.Specifically, we implemented a process to switch ref references in React's 18 and 19.
- Updated type definitions to reflect the updated React types.
No

Supported React 19.

---

packages/react/src/components/breadcrumb/breadcrumb.tsx

Closes #3854 
This PR is to remove deprecated props `isEllipsisPage`, `isCurrentPage` and `isLastChild`
No

`breadcrumb`: remove deprecated props

---

packages/react/src/components/file-input/file-input.stories.tsx
packages/react/src/components/file-input/file-input.test.tsx
packages/react/src/components/file-input/file-input.tsx

Closes #3866 
Removed `isReadOnly`, `isInvalid`, `isDisabled` from `form-control` package
No

`file-input`: remove deprecated props

---

packages/react/src/components/input/input-element.tsx
packages/react/src/components/input/input-group.tsx
packages/react/src/components/input/input.stories.tsx
packages/react/src/components/input/input.test.tsx

Closes #3873 
Removed `isClick`, `isClickable` props
No

`input`: remove deprecated props

---

packages/react/src/components/password-input/password-input.stories.tsx
packages/react/src/components/password-input/use-password-input.tsx

Closes #3962 
Removed `defaultIsVisible` and `isVisible` props
Replaced `form-control` props
No

`password-input`: remove deprecated props

---

.changeset/fifty-mugs-appear.md
packages/components/modal/src/drawer.tsx
packages/theme/src/components/drawer.ts

Closes #4278 
Fixed the bug that `fullHeight` prop did not work in `Drawer`
`fullHeight` won't occupy the viewport height.
`fullHeight` will occupy the viewport height.
No

`<Drawer />`: `fullHeight` did not work

---

packages/react/src/components/progress/circle-progress.stories.tsx
packages/react/src/components/progress/circle-progress.test.tsx
packages/react/src/components/progress/circle-progress.tsx
packages/react/src/components/progress/progress.stories.tsx
packages/react/src/components/progress/progress.test.tsx
packages/react/src/components/progress/progress.tsx

Closes #3966 
Closes #3501
Closes #3341
Removed `isRounded`, `isAnimation` and `isStripeAnimation` and its uncessary logic
Removed `size` from circle-progress
No

`progress`: remove deprecated props

---

.changeset/chilly-bears-leave.md
packages/core/src/components/component.types.ts

Closes #3835
Removed unused `ComponentArgs` properties.
No

Removed unused `ComponentArgs` properties

---

docs/contents/components/data-display/list/index.ja.mdx
docs/contents/components/data-display/list/index.mdx

Fixed `List` component documentation.
The display of  [List - Other Lists](https://yamada-ui.com/components/data-display/list#other-lists) is incorrect.
No

Fixed `List` component documentation

---

packages/react/src/hooks/use-clipboard/index.test.ts

This PR improves the erratic tests in `use-clipboard` hook.

test(use-clipboard): refine test suite mocking timer

---

packages/react/src/components/textarea/textarea.test.tsx

Closes https://github.com/yamada-ui/yamada-ui/issues/4598
In v1 series, row was 1, but from v2.0 onwards, it seems that row has become 2.
https://github.com/yamada-ui/yamada-ui/blob/v2.0/packages/react/src/components/textarea/textarea.tsx#L30

test: fix test for autosize textarea

---

packages/components/snacks/tests/snacks.test.tsx

Closes #2457 
This PR enhances the test coverage for the `@yamada-ui/snacks` package by adding comprehensive tests for the `use-snacks.tsx`. The changes focus on improving test coverage to meet the target of 95% or higher.
- The `@yamada-ui/snacks` package has test coverage below 95%
- Missing tests for various property
- Added test cases for uncovered scenarios in `use-snacks`
No

test: increased coverage for snacks

---

packages/components/data-list/tests/data-list.test.tsx

Closes #3651
This PR enhances the test coverage for the `@yamada-ui/data-list` package by adding comprehensive tests for the `DataList` component. The changes focus on improving test coverage to meet the target of 95% or higher.
- The `@yamada-ui/data-list` package has test coverage below 95%
- Missing tests for various property
- Added test cases for the following scenarios:
- Testing for null description cases
- Testing for array description cases
- Testing column property updates
- Testing items property updates
No

test: increased coverage for data-list

---

.changeset/easy-windows-jam.md
packages/hooks/use-focus-visible/src/index.ts

Closes #4711 
I have fixed the issue where storybook would crash with the following error.
```
Cannot redefine property: focus
```
Storybook crashed with 
```
Cannot redefine property: focus
```
No longer crashes.
https://github.com/user-attachments/assets/60ae3b70-1f0a-4e5e-938b-e41a6c7bf795
No

fix(use-focus-visible): make focus property configurable to fix "Cannot redefine property: focus"

---

www/app/[locale]/docs/sidebar.tsx
www/app/[locale]/mobile-menu.tsx

Closes #4728 
I have fixed the current page checking logic.
If you were on `Format*` page, it would also select `For` component.
I added to check the length to make sure `For` is not being considered as the same as `Format*`.

fix(sidebar): improve pathname matching logic in mobile menu and sidebar components

---

www/app/[locale]/color-mode-button.tsx

Closes # 
I have fixed color mode button showing wrong mode on initial mode due to client side rendering.
It used client side hook that would dynamically change the icon being displayed, which had delays in initial load.
I am now using CSS to switch the icon.

fix(color-mode-button): fix color mode button icon on initial load

---

.changeset/loose-actors-push.md
packages/hooks/use-clickable/src/index.ts

Closes #4703 
This fixes the error where there would be a "Client Side Exception" when clicking `clickable`s too quickly. This error was resulted by a loose if condition which triggered multiple state updates between each click. 
This has been tested by building the docs and running a macro to quickly switch between the docs tabbings. 
This PR now adds a check to see if the `button` state is available which no longer causes the client side exception. 
No
It was recommended to possible use a `ref` instead of `state`, although this change may affect related components. 
- https://github.com/yamada-ui/yamada-ui/issues/4703#issuecomment-3061689273

fix(use-clickable): button state update in ref callback

---

www/i18n/routing.ts

Closes #4772 
Avoid prefixing the default locale in `next-intl` routing so `localePrefix: as-needed` works correctly. This resolves the bug where users who land on a Japanese page first cannot switch to English until after viewing an English page.
- Visiting a Japanese page first prevents switching to English via the language button.
- Switching from English to Japanese works; after visiting English once, switching becomes possible.
- Users can switch between Japanese and English in both directions, even on the first visit.
- Default locale is no longer incorrectly prefixed, ensuring correct locale resolution.
No

fix(www-i18n): allow switching from ja to en on first visit

---

www/contents/components/(components)/alert.ja.mdx
www/contents/components/(components)/alert.mdx
www/contents/hooks/use-notice.ja.mdx
www/contents/hooks/use-notice.mdx

Closes #4938
I have migrated `useNotice` documentation.
It had empty documentation.
I have added actual examples to both English and Japanese.
No

docs(use-notice): migrate `use-notice` documentation with updated examples
