components/navigation/src/breadcrumb.tsx, components/navigation/src/index.ts, stories/components/navigation/breadcrumb.stories.tsx, theme/src/components/breadcrumb.ts, theme/src/components/index.ts
=> created Breadcrumb

.changeset/lovely-kids-give.md, packages/components/button/src/button.tsx, packages/components/button/src/icon-button.tsx
Related #193
> Fix `className`
> Nothing.
> Nothing.
No.
=> fix: Button changed className

.changeset/nervous-planes-film.md, .changeset/twelve-falcons-develop.md, packages/components/avatar/src/avatar-badge.tsx, packages/components/avatar/src/avatar-group.tsx, packages/components/avatar/src/avatar-icon.tsx, packages/components/avatar/src/avatar-name.tsx, packages/components/avatar/src/avatar.tsx
Related #193  
> Changed `className`
> Nothing.
> Nothing.
No.
=> fix: Avatar className Changed

.changeset/wet-tips-drive.md, packages/components/alert/src/alert.tsx
Related #193
> Changed ClassName.
> Nothing.
> Nothing.
No.
=> fix: Alert className Changed

.changeset/thin-socks-act.md, packages/components/accordion/src/accordion-item.tsx, packages/components/accordion/src/accordion-label.tsx, packages/components/accordion/src/accordion-panel.tsx
Related #193
> Changed `className`
> Nothing.
> Nothing.
No.
=> fix: Accordion className Changed

.changeset/heavy-phones-crash.md, packages/components/card/src/card.tsx
Related #193
> fix `className` By BEM
> Nothing.
> Nothing.
No.
=> fix: Card className Changed

.changeset/nervous-hotels-swim.md, packages/components/editable/src/editable.tsx
Related #193
> Changed `className`
> Nothing.
> Nothing.
No.
=> fix: Editable classname changed

.changeset/grumpy-singers-dress.md, .changeset/heavy-lizards-breathe.md, packages/components/form-control/src/form-control.tsx
Related #193
> Changed `className` by BEM.
> Nothing.
> Nothing.
No.
=> fix: FormControl changed className

.changeset/breezy-shirts-sin.md, .changeset/ten-zoos-float.md, packages/components/dropzone/src/dropzone.tsx
Related #193
> Changed `className` by BEM.
> Nothing.
> Nothing.
No.
=> fix: Dropzone changed className

.changeset/calm-kings-occur.md, packages/components/image/src/image.tsx
Related #193
> Nothing.
> Nothing.
No.
=> fix: Image changed className

.changeset/fluffy-adults-cheat.md, .changeset/serious-donuts-rhyme.md, packages/components/carousel/src/carousel-control.tsx, packages/components/carousel/src/carousel-indicators.tsx, packages/components/carousel/src/carousel-slide.tsx, packages/components/carousel/src/carousel.tsx
Related #193
> Nothing.
> Nothing.
No.
=> fix: Carousel changed className

.changeset/flat-eels-judge.md, .changeset/red-apricots-remember.md, README.md, packages/components/calendar/src/calendar-header.tsx, packages/components/calendar/src/calendar.tsx, packages/components/calendar/src/date-picker-field.tsx, packages/components/calendar/src/date-picker-icon.tsx, packages/components/calendar/src/date-picker.tsx, packages/components/calendar/src/month-list.tsx, packages/components/calendar/src/month-picker.tsx, packages/components/calendar/src/month.tsx, packages/components/calendar/src/use-calendar.ts, packages/components/calendar/src/year-list.tsx, stories/components/data-display/markdown.stories.tsx
Related #193
> Changed `className` and `calender` -> `calendar`
> Nothing.
> Nothing.
No.
=> fix: Calendar changed className and name fixed

.changeset/little-foxes-complain.md, .changeset/poor-knives-compete.md, packages/components/autocomplete/src/autocomplete-create.tsx, packages/components/autocomplete/src/autocomplete-empty.tsx, packages/components/autocomplete/src/autocomplete-icon.tsx, packages/components/autocomplete/src/autocomplete-list.tsx, packages/components/autocomplete/src/autocomplete-option-group.tsx, packages/components/autocomplete/src/autocomplete-option.tsx, packages/components/autocomplete/src/autocomplete.tsx, packages/components/autocomplete/src/multi-autocomplete.tsx
Related #193
> Change className.
> Nothing.
> Nothing.
No.
=> fix: Autocomplete className changed

.changeset/rude-ties-compete.md, packages/components/indicator/src/indicator.tsx
Related #193
> Nothing.
> Nothing.
No.
=> fix: Indicator className changed

.changeset/metal-seals-retire.md, packages/components/loading/src/loading-provider.tsx
Related #193
> Changed `clasName`
> Nothing.
> Nothing.
No.
=> fix: loading changed className

.changeset/tidy-poems-clean.md, packages/components/link/src/linkBox.tsx
Related #193
> Nothing.
> Nothing.
No.
=> fix: Link changed className

.changeset/empty-ties-walk.md, .changeset/old-insects-scream.md, packages/components/native-select/src/native-select.tsx, packages/components/number-input/src/number-input.tsx
Related #193
> Changed `className` in `NumberInput` and `NativeSelect`.
> Nothing.
> Nothing.
No.
=> Changed className NumberInput and NativeSelect

.changeset/fifty-lobsters-dream.md, packages/components/menu/src/menu-button.tsx, packages/components/menu/src/menu-divider.tsx, packages/components/menu/src/menu-group.tsx, packages/components/menu/src/menu-item.tsx, packages/components/menu/src/menu-list.tsx, packages/components/menu/src/menu-option-group.tsx
Related #193
> Changed `className` in `Menu`.
> Nothing.
> Nothing.
No.
=> fix: changed className in Menu

.changeset/breezy-tools-perform.md, .changeset/kind-chairs-invent.md, .changeset/moody-cheetahs-tie.md, .changeset/nasty-ghosts-rhyme.md, packages/components/modal/src/dialog.tsx, packages/components/modal/src/drawer.tsx, packages/components/modal/src/modal-body.tsx, packages/components/modal/src/modal-close-button.tsx, packages/components/modal/src/modal-footer.tsx, packages/components/modal/src/modal-header.tsx, packages/components/modal/src/modal-overlay.tsx, packages/components/native-table/src/native-table.tsx, packages/components/native-table/src/table-caption.tsx, packages/components/native-table/src/table-container.tsx, packages/components/native-table/src/tbody.tsx, packages/components/native-table/src/td.tsx, packages/components/native-table/src/tfoot.tsx, packages/components/native-table/src/th.tsx, packages/components/native-table/src/thead.tsx, packages/components/native-table/src/tr.tsx, packages/components/notice/src/notice-provider.tsx, packages/components/notice/src/notice.tsx, packages/components/pagination/src/pagination-item.tsx, packages/components/pagination/src/pagination.tsx
Related #193
> Changed `className` in `Modal` and `Notice` and `Pagination` and `NativeTable` by `BEM`.
> Nothing.
> Nothing.
No.
=> Changd className  Modal Notice NativeTable Pagination

.changeset/blue-eggs-hear.md, .changeset/bright-wasps-draw.md, .changeset/flat-fans-collect.md, .changeset/four-moose-clap.md, .changeset/grumpy-timers-applaud.md, .changeset/shaggy-pans-bathe.md, packages/components/pin-input/src/pin-input.tsx, packages/components/popover/src/popover-body.tsx, packages/components/popover/src/popover-close-button.tsx, packages/components/popover/src/popover-content.tsx, packages/components/popover/src/popover-footer.tsx, packages/components/popover/src/popover-header.tsx, packages/components/radio/src/radio-group.tsx, packages/components/radio/src/radio.tsx, packages/components/reorder/src/reorder-item.tsx, packages/components/reorder/src/reorder-trigger.tsx, packages/components/scroll-area/src/scroll-area.tsx, packages/components/segmented-control/src/segmented-control.tsx
Related #193
> Changed `className` in `PinInput` & `Popover` & `Radio` & `Reorder` & `Scrollarea`.
> Nothing.
> Nothing.
No.
=> Fix PinInput Popover Radio Reorder Scrollarea

.changeset/wise-humans-watch.md, packages/components/loading/src/loading-provider.tsx
=> fix: changed height loading animation

.changeset/fluffy-dolphins-mix.md, .changeset/red-carrots-prove.md, .changeset/warm-coins-think.md, packages/components/alert/src/alert.tsx, packages/components/autocomplete/src/autocomplete-option-group.tsx, packages/components/autocomplete/src/autocomplete-option.tsx, packages/components/autocomplete/src/autocomplete.tsx, packages/components/autocomplete/src/multi-autocomplete.tsx, packages/hooks/use-controllable-state/src/index.ts
Related None
> changed `??` to `??=`
> Nothing.
> Nothing.
No.
@hirotomoyamada もし必要なさそうだったらクローズしてもらって大丈夫です。
=> refactor: changed `??` to `??=`

packages/components/input/tests/input.test.tsx
Closes #337
> Add test in `Input`.
> Nothing.
> Nothing.
No.
=> test: add test in `Input`

packages/components/avatar/tests/avatar-group.test.tsx, packages/components/avatar/tests/avatar.test.tsx
Closes #311
Related #74 
> Add test of `Avatar`.
> Nothing.
> Nothing.
No.
=> add Test `Avatar`

packages/components/textarea/tests/textarea.test.tsx
Closes None
> Enhanced test code.
> Nothing.
> Nothing.
No.
=> Enhancement Test in `Textarea`

packages/components/kbd/test/kbd.test.tsx
Closes #338
Related #74
> Add test
> Nothing
> Nothing
No
=> test: add test in `Kbd`

packages/components/loading/tests/loading.test.tsx
Closes #342
Related #74
> Add test
> Nothing
> Nothing
No
=> test: add test in `Loading`

packages/components/accordion/tests/accordion.test.tsx
Closes #308
Related #74
> Add test for `Accordion`
> Nothing
> Nothing
No
=> test: add test in `Accordion`

packages/components/native-table/tests/native-table.test.tsx
Closes #348
Related #74
> Add test for `NativeTable`
> Nothing
> Nothing
No
=> test: add test in `NativeTable`

packages/components/native-select/tests/native-select.test.tsx
Closes #347
Related #74
> Add test for `NativeSelect`
> Nothing
> Nothing
No
=> test: add test in `NativeSelect`

packages/components/checkbox/tests/checkbox.test.tsx
Closes #298
Related #74
> Add test for `Checkbox`
> Nothing.
> Nothing.
No
=> test: add test in `Checkbox`

packages/components/skeleton/tests/skeleton.test.tsx
Closes #361 
Related #74
> Add test for `Skeleton`
> Nothing.
> Nothing.
No
=> test: add test in `Skeleton`

packages/components/menu/tests/menu.test.tsx
Closes #344
Related #74
> Add test for `Menu`
> Nothing.
> Nothing.
No
=> test: add test in `Menu`

packages/components/editable/tests/editable.test.tsx
Closes #301
Related #74
> Add test for `Editable`
>Nothing.
> Nothing.
No
=> test: add test in `Editable`

.changeset/grumpy-gorillas-cough.md, packages/components/select/package.json, packages/components/select/src/multi-select.tsx, packages/components/select/src/select.tsx, pnpm-lock.yaml
Closes #417
Added `Portal` component to allow `PopoverContent` transfer.
No
=> feat(select): added `Portal` for `PopoverContent`

.changeset/eleven-bikes-cough.md, .changeset/grumpy-humans-tie.md, packages/components/autocomplete/package.json, packages/components/autocomplete/src/autocomplete.tsx, packages/components/autocomplete/src/multi-autocomplete.tsx, packages/components/calendar/package.json, packages/components/calendar/src/date-picker.tsx, packages/components/calendar/src/month-picker.tsx, pnpm-lock.yaml
Closes #417 
Added `Portal` component to allow `PopoverContent` transfer.
No
=> feat(autocomplete): added Portal for PopoverContent

packages/components/indicator/tests/indicator.test.tsx
Closes #336 
> Add test for Indicator.
> Nothing.
> Nothing.
No
=> test: add test in `Indicator`

.changeset/many-coins-impress.md, packages/components/ripple/src/use-ripple.ts
Set default props for `useRipple`
No
=> Set default props for `useRipple`

packages/components/close-button/test/close-button.test.tsx, packages/components/file-button/tests/file-button.test.tsx
Closes #302  
> Add test `FileButton` & `CloseButton`
> Nothing.
> Nothing.
No.
=> Add test in `FIleButton` & `CloseButton`

.changeset/smart-bananas-fetch.md, packages/core/src/css/css.ts, packages/hooks/use-breakpoint/src/index.ts
Closes #529
Incorrect breakpoint style.
The order of the generated media queries changes depending on the order of the keys of the object that defines the breakpoint, so a style different from the expected value may be applied.
Set styles in order with correct breakpoints no matter how they are defined.
Yes
=> refactor(core): optimized breakpoint resolution logic

packages/components/tabs/tests/tabs.test.tsx
Closes #366
> Add test for `Tabs`
> Nothing.
> Nothing.
No
=> test: add test for `Tabs`

.changeset/honest-brooms-love.md, packages/components/autocomplete/src/autocomplete.tsx, packages/components/autocomplete/src/multi-autocomplete.tsx, packages/components/native-select/src/native-select.tsx, packages/components/native-table/src/native-table.tsx, packages/components/select/src/multi-select.tsx, packages/components/slider/src/range-slider.tsx
Closes #551
Fixed to correct ThemeProps.
No
=> Fixed to correct ThemeProps

.changeset/many-fireants-tap.md, packages/core/src/config.ts, packages/core/src/css/css.ts, packages/core/src/styles.ts, scripts/generate-css/styles.ts, scripts/utils.ts
Closes #585
CSS variable generation is incorrect
=> Fixed `var` props

.changeset/orange-spiders-grin.md, .changeset/proud-ants-report.md, .changeset/slimy-pears-jump.md, packages/components/form-control/src/form-control.tsx, packages/components/radio/src/radio.tsx, packages/components/slider/src/range-slider.tsx, packages/components/slider/src/slider.tsx
Closes #589
Closes #588
Closes #587
Fixed `reaonly` styles.
No
=> Fixed `readonly` styles

packages/components/radio/src/radio-group.test.tsx, packages/components/radio/src/radio.test.tsx
Closes #356 
Add unit test for radio and radio group component.
> Nothing
> Nothing
No
=> feat: add test for radio component

packages/components/pagination/tests/pagination.test.tsx
Closes #351 
> Add unit test for pagination component
> no
> no
> no
=> test: add unit test for pagination component

packages/components/carousel/tests/carousel.test.tsx
Closes #297 
> none
> none
> no
=> test: add test for carousel component

.changeset/gold-mice-invent.md, packages/core/src/pseudos.ts, stories/components/data-display/list.stories.tsx
Closes #634 
> Supported `::marker` pseudo.
> Nothing.
> Nothing.
No.
=> Supported `::marker` pseudo.

.changeset/wicked-maps-behave.md, packages/utils/src/react.tsx
Closes #632
add defaultValue to createContext
createContextに初期値を設定できるようになりました
No
=> feat: add defaultValue to createContext

.changeset/slimy-students-think.md, packages/core/src/pseudos.ts
Closes #633  
> Add `_firstLetter` & `_firstLine`.
> Nothing.
> Nothing.
No.
=> feat: add `_firstLetter` & `_firstLine`

stories/components/other/ripple.stories.tsx
Closes None
> Add Storybook Ripple with isDisabled.
> None.
> None.
No.
=> Add Storybook Ripple with isDisabled

packages/components/pin-input/tests/pin-input-field.test.tsx, packages/components/pin-input/tests/pin-input.test.tsx
Closes #352 
Added tests for pin-input component
=> test(pin-input): add tests

packages/components/charts/src/area-chart.tsx, packages/components/charts/src/use-area-chart.ts, packages/theme/src/components/area-chart.ts, stories/components/feedback/area-chart.stories.tsx
implementation of features of areachart and addition of stories
NIL
Area-chart features available.
Style, legend and tooltip not yet implemented.
=> feat(area-chart): implementation of features of areachart and addition of stories

packages/components/resizable/tests/resizable.test.tsx, packages/components/resizable/tests/utils.ts
See: https://github.com/bvaughn/react-resizable-panels/blob/main/packages/react-resizable-panels/src/Panel.test.tsx
=> test(Resizable): add tests

packages/components/charts/src/bar-chart.tsx, stories/components/feedback/bar-chart.stories.tsx
=> feat(bar-chart): added bar-chart custom story

.changeset/cuddly-garlics-cry.md, .changeset/modern-bags-smell.md, .changeset/rare-queens-bathe.md, .changeset/thin-lobsters-jump.md, packages/core/src/providers/color-mode-provider.tsx, packages/hooks/use-breakpoint/src/index.ts, packages/hooks/use-token/src/index.ts, packages/hooks/use-value/src/index.ts
Added `getValue`, `getToken`, `getBreakpointValue` and `getColorModeValue`.
No
=> Added `getValue`, `getToken`, `getBreakpointValue` and `getColorModeValue`

.changeset/six-elephants-march.md, packages/components/color-picker/src/color-picker.tsx, packages/components/color-picker/src/color-selector.tsx, packages/components/color-picker/src/use-color-picker.ts, stories/components/forms/color-picker.stories.tsx, stories/components/forms/color-selector.stories.tsx
Added `children` prop support.
No
=> Supported `children` in `ColorSelector` and `ColorPicker`

packages/components/charts/src/area-chart.tsx, packages/components/charts/src/index.ts, packages/components/charts/src/use-area-chart.ts, stories/components/feedback/area-chart.stories.tsx
Added the ability to receive Props containing CSS parameters and apply styles.
The style is stored in the head with the useCSS hook and applied with className.
NIL
CSS parameters can be specified for each Props.
=> feat(area-chart): applied style in CSSUIObject

.changeset/late-books-grin.md, packages/core/src/css/css.ts, packages/core/src/css/use-css.ts
=> Added `getCSS` function

packages/components/markdown/tests/markdown.test.tsx
Closes #343 
I understand that I'm supposed to write tests. However, I'm struggling because react-markdown, which @yamada-ui/markdown depends on, is an ESM-only module and doesn't play well with Jest. Therefore, I'd like to close the issue once I've created the test files, and then open a separate issue to actually write the tests and improve the coverage.
=> feat(markdown): add `markdown.test.tsx`

.changeset/stale-poets-think.md, packages/components/color-picker/src/use-color-picker.ts, packages/components/color-picker/src/use-color-selector.ts
Closes #807
Closes #808
Fixed a bug where the value was inserted when the `format` prop was changed and a bug where the input value was not updated when the value was changed using `setState` etc.
No
=> Fixed format and setState update bugs

.changeset/four-kings-march.md, .changeset/mean-islands-shake.md, packages/components/autocomplete/package.json, packages/components/autocomplete/src/use-autocomplete.tsx, packages/components/calendar/package.json, packages/components/calendar/src/use-calendar-picker.ts, packages/components/color-picker/package.json, packages/components/color-picker/src/use-color-picker.ts, packages/components/select/package.json, packages/components/select/src/use-select.ts, pnpm-lock.yaml
Closes #810
Enabled `Popover` component control
No
=> Enabled `Popover` component control

.changeset/clever-trains-act.md, .changeset/quiet-grapes-shop.md, packages/components/modal/src/dialog.tsx, packages/components/modal/src/drawer.tsx, packages/components/modal/src/modal.tsx, packages/components/transitions/src/collapse.tsx, packages/components/transitions/src/fade.tsx, packages/components/transitions/src/scale-fade.tsx, packages/components/transitions/src/slide-fade.tsx, packages/components/transitions/src/slide.tsx
Closes #816
Closes #815
Fixed a bug where animation was not executed when `as` was set.
No
=> Fixed a bug where animation was not executed when `as` was set.

.changeset/brave-dots-love.md, packages/core/src/styles.ts, scripts/generate-css/ui-props.ts
Make the var token of `StyleProps` optional.
No
=> Make the var token of `StyleProps` optional.

packages/components/charts/src/area-chart.tsx, packages/components/charts/src/area-split.tsx, packages/components/charts/src/chart.types.ts, packages/components/charts/src/legend.tsx, packages/components/charts/src/tooltip.tsx, packages/components/charts/src/use-area-chart.ts, packages/components/charts/src/use-chart.ts, packages/theme/src/components/area-chart.ts, stories/components/feedback/area-chart.stories.tsx
refactoring and implementation of area-chart.ts
NIL
NIL
=> feat(area-chart):  theme implementation

packages/components/charts/src/area-chart.tsx, packages/components/charts/src/chart.types.ts, packages/components/charts/src/legend.tsx, packages/components/charts/src/use-area-chart.ts, packages/theme/src/components/area-chart.ts, stories/components/feedback/area-chart.stories.tsx
=> refactor(area-chart): fixed theme

CONTRIBUTING.ja.md, CONTRIBUTING.md
Closes #820
Corrected the link to "commit-convention" in CONTRIBUTING(.ja).md.
No
=> docs: corrected links in CONTRIBUTING(.ja).md

.changeset/cool-laws-sit.md, packages/components/link/src/link-box.tsx
Closes #823
Fixed a bug where theme tokens were used in `LinkBox`.
No
=> Fixed a bug where theme tokens were used in `LinkBox`

.changeset/shy-oranges-judge.md, packages/components/number-input/src/number-input.tsx
Closes #822 
Fixed a bug where theme tokens were used in `NumberInput`.
No
=> Fixed a bug where theme tokens were used in `NumberInput`

plop/component/package-multi/tests/{{dashCase packageName}}.test.tsx.hbs, plop/component/package/tests/{{dashCase packageName}}.test.tsx.hbs
> generate test when gen:component run
> it does'nt generate test when gen:component run
> generate test when gen:component run
No
=> feat(test): generate test when gen:component run

packages/components/card/tests/card.test.tsx
Closes #778 
Enhance test coverage for components with less than 80% coverage to meet or exceed 80%.
No
=> test(card): enhance test coverage

.changeset/many-clouds-hang.md, packages/components/skeleton/src/skeleton-circle.tsx, packages/components/skeleton/src/skeleton-text.tsx, packages/components/skeleton/src/skeleton.tsx
Closes #834 
Fixed a bug where theme tokens were used in the Skeleton component.
No
=> fix(skeleton): fixed theme token usage in styles

packages/components/progress/tests/circle-progress.test.tsx
Closes #796  
I've made the test statement coverage 100% !
No
I tried to achieve 100% branch coverage, but the following lines are not executed because interval does not become undefined when isAnimation is false. 
https://github.com/hirotomoyamada/yamada-ui/blob/3f64d157b490f36e773731e5b5a8ab3b3fdf3812/packages/components/progress/src/circle-progress.tsx#L107
https://github.com/hirotomoyamada/yamada-ui/blob/3f64d157b490f36e773731e5b5a8ab3b3fdf3812/packages/components/progress/src/circle-progress.tsx#L143
Therefore, the branch coverage is 94%, but I believe all branches are covered.
=> test(progress): enhance test coverage

packages/components/loading/tests/loading.test.tsx
Closes #788  
I improved the test coverage for @yamada-ui/loading.
Before
After
No
=> test(loading): enhance test coverage

packages/components/charts/src/bar-chart.tsx, packages/components/charts/src/chart.types.ts, packages/components/charts/src/use-bar-chart.ts, packages/theme/src/components/bar-chart.ts, stories/components/feedback/bar-chart.stories.tsx
=> refactor(bar-chart): Updated useBarChart

packages/components/snacks/tests/snacks.test.tsx
Closes #802 
Enhance test coverage for components with less than 80% coverage to meet or exceed 80%.
No
=> test(snacks): enhance test coverage

packages/components/charts/src/area-chart.tsx, packages/components/charts/src/use-area-chart.ts
refactor getAreaProps() and getCSSvariables
NIL
NIL
=> refactor(area-chart): refactor getAreaProps()

packages/components/charts/src/legend.tsx, packages/components/charts/src/tooltip.tsx, packages/theme/src/components/area-chart.ts
refactor of chart tooltip and legend
NIL
NIL
=> refactor(chart): applied styles tooltip and legend

packages/components/highlight/tests/highlight.test.tsx
Closes #785 
Enhance test coverage for components with less than 80% coverage to meet or exceed 80%.
No
This is my first pull request for OSS, so if you have any suggestions for improvement, I would appreciate it.
=> test(highlight): enhance test coverage

.github/workflows/quality.yml, codecov.yml, package.json
* Integrated [codecov](https://about.codecov.io/)
* When you want to know `codecov.yml`, please see the [document](https://docs.codecov.com/docs/codecov-yaml).
=> Integrate Codecov

.changeset/sharp-readers-train.md, packages/components/notice/src/notice.tsx
Closes #911 
Fixed a bug where theme tokens were used in Notice.
No
=> Fixed a bug where theme tokens were used in Notice

.changeset/eighty-cherries-float.md, packages/components/snacks/src/snacks.tsx
Closes #910 
set 1rem for gap
No
=> Fixed Snacks theme token usage in styles

.changeset/twenty-feet-bathe.md, packages/utils/src/object.ts, packages/utils/src/react.tsx, scripts/generate-docs.ts
Added `LegacyRef` to `ReactRef`.
No
=> Fixed `LegacyRef`

.changeset/tiny-olives-fold.md, packages/core/src/pseudos.ts
Added `_target`, `_notTarget`, `_focusWithin` pseudo properties.
No
=> Added pseudo properties

packages/components/charts/src/bar-chart.tsx, packages/theme/src/components/bar-chart.ts, stories/components/feedback/bar-chart.stories.tsx
=> refactor(bar-chart): update bar-chart

.changeset/fair-schools-juggle.md, packages/core/src/styles.ts, scripts/generate-css/ui-props.ts
Closes #971
Allowed to define any values for `_media` and `_container`.
No
=> Allowed dynamic keys in style props

.changeset/tasty-mayflies-juggle.md, packages/components/color-picker/package.json, packages/components/resizable/package.json, packages/components/ripple/package.json, packages/components/snacks/package.json, packages/components/stat/package.json
Added `"use client"` to source code.
No
=> Added "use client" banner to packages

.changeset/flat-eggs-impress.md, packages/components/button/src/icon-button.tsx
Closes #981 
fix to check children presence first.
No
=> Fix Priority presence of props

packages/components/infinite-scroll-area/DOCS.json, packages/components/menu/DOCS.json, packages/components/modal/DOCS.json, packages/components/motion/DOCS.json, packages/components/popover/DOCS.json, packages/components/ripple/DOCS.json, packages/components/snacks/DOCS.json, packages/components/toggle/DOCS.json, packages/components/transitions/DOCS.json, packages/core/src/generated-theme.types.ts
Updated `docs` and `tokens`
No
=> Updated `docs` and `tokens`

.changeset/eighty-colts-confess.md, packages/components/toggle/src/toggle-group.tsx, packages/components/toggle/src/toggle.tsx, stories/components/forms/toggle.stories.tsx
Changed prop name `isReadonly` to `isReadOnly`.
No
=> Renamed prop to `isReadOnly`

packages/components/carousel/src/carousel-indicators.tsx
Closes #1102
This is a modified comment within the carousel indicator component.
No
=> fix: typo carousel indicators component

.eslintrc
* In this PR, I'm adding ESLint rules from [eslint-plugin-testing-library](https://github.com/testing-library/eslint-plugin-testing-library) that can be introduced without fixing the test codes.
* ESLint rules that require modifications to the test codes will be handled in separate PRs.
=> [Eslint/Testing-library] Add eslint rules for testing library without fixing codes

packages/hooks/use-hover/tests/use-hover.test.tsx
Closes #1048
Add a test for `useHover` (@yamada-ui/hooks)
=> Add a test for `useHover`

.changeset/brown-icons-heal.md, .changeset/eleven-starfishes-turn.md, packages/components/modal/src/drawer.tsx, packages/components/motion/src/motion.types.ts
Fixed a bug where `@yamada-ui/react` was being imported.
No
=> Fixed a bug where `@yamada-ui/react` was being imported.

packages/hooks/use-idle/tests/index.test.ts
Closes #1049
Add tests for `useIdle`.
No
=> Add tests for `useIdle`

packages/components/modal/tests/dialog.test.tsx, packages/utils/tests/react.test.tsx
Closes #1179 
Closes #1180 
I fixed fail tests which were after runnning `pnpm test`.
No
No
=> Fix fail test in `Dialog` component and `utils`

packages/components/avatar/tests/avatar.test.tsx
Closes #1023
Add tests for `AvatarBadge` component.
No
=> Add tests for `AvatarBadge` component

packages/hooks/use-animation/tests/index.test.tsx
Closes #1039
Add `useAnimation` and `useDynamicAnimation` hook tests.
No
=> Add `useAnimation` and `useDynamicAnimation` hook tests

packages/theme-tools/tests/extend-config.test.ts, packages/theme-tools/tests/extend-theme.test.ts, packages/theme-tools/tests/with-default.test.ts
Closes #1057
Add theme tool tests.
No
=> Add theme tool tests

packages/hooks/use-window-event/tests/index.test.ts
Closes #1056 
Added `useWindowEvent` tests.
No
=> Added `useWindowEvent` tests

packages/components/tabs/tests/tabs.test.tsx
Closes #1037
Add keyboard navigation tests.
No
=> Add keyboard navigation tests in `Tabs`

.changeset/tasty-toes-hang.md, packages/core/src/providers/color-mode-manager.ts, packages/core/src/providers/color-mode-script.tsx, packages/core/src/providers/theme-manager.ts, packages/core/src/providers/theme-script.tsx
Closes #1189
Made cookie parameter optional in ssr methods.
No
=> Made cookie parameter optional in ssr methods.

.changeset/eight-kangaroos-bathe.md, packages/components/charts/src/use-chart-tooltip.ts
Closes #1193
className is  assigned to Cursor in chart
className is  assigned to Cursor
No
=> Fix assigned cursor

.changeset/brown-planes-enjoy.md, .changeset/sour-ducks-drum.md, packages/components/menu/src/menu-item.tsx, packages/hooks/use-clickable/src/index.ts
Closes #1202
Closes #1199
Fixed a bug where `MenuItem` event handlers were not working.
No
=> Fixed a bug where `MenuItem` event handlers were not working.

.github/ISSUE_TEMPLATE/bug_report.ja.yml, .github/ISSUE_TEMPLATE/bug_report.yml
Closes #1198
Added `@yamada-ui/charts` to bug report templates
No
=> Added `@yamada-ui/charts` to bug report templates

.changeset/famous-ducks-give.md, .changeset/fuzzy-forks-knock.md, packages/components/loading/package.json, packages/components/loading/src/loading.tsx, packages/components/loading/src/oval.tsx, packages/theme/src/components/index.ts, packages/theme/src/components/loading.ts, pnpm-lock.yaml
Closes #1218
Supported theme system for `Loading` component.
No
=> Supported theme system for `Loading` component

.changeset/ninety-suits-compete.md, packages/components/ripple/src/ripple.tsx
Closes #1223 
Add JSDoc to Ripple component
No
=> docs: jsdoc to rippe component

.storybook/preview.tsx
Simplified a11y rules configuration.
No
=> Simplified a11y rules configuration

.storybook/main.ts
Related #1229
Force reload when specific folder is updated.
This is a temporary measure. :(
No
=> Force reload when specific folder is updated

.changeset/smart-moons-give.md, packages/components/portal/src/portal.tsx
Closes https://github.com/yamada-ui/yamada-ui/issues/1220 
JSDoc is  missing from the `Portal` component.
I have added JSDoc for the `Portal` component.
No
=> docs(portal): add component documentation

.changeset/plenty-avocados-provide.md, packages/components/menu/package.json, packages/components/menu/src/menu-button.tsx, pnpm-lock.yaml
Closes #1282
Added icon dependency and fixed bug.
No
=> Added icon dependency and fixed bug

packages/hooks/use-value/tests/index.test.tsx
Update test descriptions to English.
No
=> Update test descriptions to English

CONTRIBUTING.md
Corrected typo in CONTRIBUTING.md.
No
=> Corrected typo in CONTRIBUTING.md

package.json, pnpm-lock.yaml, scripts/report-insights.ts
=> Fixed report insights

.github/pull_request_template.md, scripts/observe-pull-requests.ts
Updated terminology to 'maintainers'.
No
=> Updated terminology to 'maintainers'

.changeset/forty-buckets-dress.md, packages/components/calendar/src/month.tsx, packages/utils/src/assertion.ts
Added `isBoolean` function and updated usage.
No
=> Added `isBoolean` function and updated usage

.changeset/young-onions-lie.md, packages/components/pagination/src/pagination.tsx, packages/components/pagination/src/use-pagination.ts
Streamlined prop and state handling.
No
=> Streamlined prop and state handling

.changeset/light-bananas-tickle.md, packages/components/segmented-control/src/segmented-control.tsx
Closes #1249
Fixed `aria-readonly` assignment issue.
No
=> Fixed `aria-readonly` assignment issue

scripts/report-insights.ts
Updated date handling in report insights.
No
=> Updated date handling in report insights

.eslintignore, .eslintrc.base.json, .eslintrc.json, .github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/documentation_report.ja.yml, .github/ISSUE_TEMPLATE/documentation_report.yml, .github/ISSUE_TEMPLATE/documentation_request.ja.yml, .github/ISSUE_TEMPLATE/documentation_request.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/sync.yml, CONTRIBUTING.ja.md, CONTRIBUTING.md, README.ja.md, README.md, docs/constant/sns.ts, docs/contents/community/contributing.ja.mdx, docs/contents/community/contributing.mdx, docs/package.json, package.json, packages/react/README.md, pnpm-lock.yaml, stories/components/data-display/markdown.stories.tsx
Related #1355
Added issue template and fixed a bug where ESLint config.
No
=> Added issue template and fixed a bug where ESLint config

.github/composite-actions/check-modified-files/action.yml, .github/workflows/quality.yml
Added composite action to check modified files.
No
=> Added composite action to check modified files

.changeset/pretty-roses-lay.md, docs/@types/contentlayer.d.ts, docs/components/layouts/header.tsx, docs/components/navigation/link-card.tsx, docs/components/navigation/tree.tsx, docs/contexts/page-context.tsx, docs/next.config.js, docs/package.json, docs/pages/404.page.tsx, docs/pages/examples/[slug].page.tsx, docs/pages/index.page.tsx, docs/scripts/changelog.ts, docs/scripts/component-props.ts, docs/scripts/contributors.ts, docs/scripts/style-props.ts, docs/scripts/theme-component.ts, docs/utils/contentlayer.ts, docs/utils/next.ts, docs/utils/path.ts, packages/core/src/config.ts, packages/core/src/css/css.ts, packages/core/src/css/var.ts, packages/core/src/index.ts, packages/core/tests/config.test.ts, packages/hooks/use-animation/src/index.ts, pnpm-lock.yaml
Fxied display version and build process.
No
=> Fxied display version and build process

.changeset/ten-falcons-dress.md, packages/components/rating/src/use-rating.tsx
Optimized prop handling in useRating
No
=> Optimized prop handling in useRating

.changeset/dry-llamas-tease.md, packages/components/pin-input/src/pin-input.tsx
Closes #1383
Update pin-input handling and props.
No
=> Update pin-input handling and props

README.ja.md, README.md
Added codecov badges to README files.
No
=> Added codecov badges to README files

.changeset/pink-eels-camp.md, packages/theme/src/components/menu.ts
Closes #1385
Fixed zIndex inconsistency in Menu component.
No
=> Fixed zIndex inconsistency in Menu component

packages/components/button/package.json, packages/components/button/tests/button-group.test.tsx, packages/components/button/tests/icon-button.test.tsx, pnpm-lock.yaml
Closes #1024
Added `ButtonGroup` and `IconButton` tests.
No
=> Added `ButtonGroup` and `IconButton` tests.

packages/components/resizable/tests/resizable.test.tsx
Closes #1034
Update tests and cleanup code.
No
=> Update tests and cleanup code

packages/components/menu/tests/menu.test.tsx
Closes #1031
Add keyboard interaction tests.
No
=> Add keyboard interaction tests

packages/components/stepper/tests/use-steps.test.ts
Closes #1035
Added `useSteps` hook tests.
No
=> Added `useSteps` hook tests.

packages/utils/tests/color.test.ts
Expand tests and add new color utils.
No
=> Expand tests and add new color utils

packages/utils/tests/string.test.ts
Added more `antonym` test cases.
No
=> Added more `antonym` test cases

.changeset/early-items-beg.md, packages/components/table/src/table.tsx
Closes #1329 
This PR updates the `Table` component, integrating additional features such as row selection highlights, footer visibility, and enhanced customization of table styles and behaviors. It also refines the internal handling of props, ensuring a more streamlined and efficient setup.
The existing `Table` component does not support certain customization options such as displaying a footer or managing borders for columns directly through props. The component's prop handling was also less efficient, requiring multiple passes to filter and apply settings.
- **Enhanced Customization:** Added options to control row highlight behaviors on selection and hover, toggle borders around the table and columns, and optionally include a footer section.
- **Optimized Prop Handling:** Streamlined …
=> refactor: integrate omitObject handling with omitThemeProps

packages/components/charts/tests/area-chart.test.tsx, stories/components/feedback/area-chart.stories.tsx
Closes #1307 
Add tests for `area-chart`
No
=> Add tests for `area-chart`

packages/hooks/use-clipboard/tests/index.test.ts
Closes #1042
Add tests for useClipboard hook.
No
=> Add tests for useClipboard hook

scripts/report-insights.ts
Updated date handling in queries
No
=> Updated date handling in queries

.changeset/strong-planets-divide.md, packages/hooks/use-descendant/src/index.ts, packages/hooks/use-descendant/tests/index.test.tsx
Closes #1044
Added tests for `useDescendant`.
No
=> Added tests for `useDescendant`

docs/contents/components/data-display/dockable/index.ja.mdx, docs/contents/components/data-display/dockable/index.mdx, docs/contents/components/data-display/split-panel/index.ja.mdx, docs/contents/components/data-display/split-panel/index.mdx
Related #989
Add and remove component docs.
No
=> Add and remove component docs

codecov.yml, scripts/coverage-issues.ts
Updated coverage thresholds and scripts.
No
=> Updated coverage thresholds and scripts

packages/hooks/use-event-listener/tests/index.test.ts
=> Add `use-event-listener` test

.changeset/sweet-cameras-explode.md, packages/components/editable/src/editable.tsx
Closes #1318
Refactor props handling in `useEditable`.
No
=> Refactor props handling in `useEditable`

.changeset/chilled-vans-care.md, packages/theme-tools/src/extend-config.ts
Renamed parameter in `extendConfig` function.
No
=> Renamed parameter in `extendConfig` function

packages/hooks/use-token/tests/index.test.tsx
Closes #1471
Add tests for theme token retrieval.
No
=> Add tests for theme token retrieval

.changeset/chilly-hats-play.md, .changeset/little-countries-glow.md, packages/components/color-picker/src/use-color-selector.ts, packages/components/color-picker/tests/color-selector.test.tsx, packages/components/file-input/src/file-input.tsx, packages/components/native-select/tests/native-select.test.tsx, packages/components/number-input/tests/number-input.test.tsx, packages/components/pagination/tests/pagination.test.tsx, packages/components/switch/tests/switch.test.tsx, packages/components/tag/src/tag.tsx, packages/components/tag/tests/tag.test.tsx
Capitalize `aria-label` texts.
No
=> Capitalize `aria-label` texts.

packages/components/number-input/tests/number-input.test.tsx
Closes #1458
Added tests for keyboard and wheel events
No
=> Added tests for keyboard and wheel events

docs/contents/getting-started/frameworks/nextjs/app-router.ja.mdx, docs/contents/getting-started/frameworks/nextjs/app-router.mdx, docs/contents/styled-system/color-mode.ja.mdx, docs/contents/styled-system/color-mode.mdx
Closes #1554
Updated colorMode documentation and examples.
No
=> Updated colorMode documentation and examples

.changeset/tasty-moose-turn.md, packages/hooks/use-pan-event/src/index.ts, packages/hooks/use-pan-event/tests/index.test.tsx
Closes #1053
Add test for `usePanEvent`.
No
=> Add test for `usePanEvent`

.changeset/hot-keys-brake.md, packages/components/file-button/src/file-button.tsx
Closes #1316
Extracted props and updated callbacks.
No
=> Extracted props and updated callbacks

packages/components/native-select/tests/native-select.test.tsx
Closes #1457
Updated test ids and added tests.
No
=> Updated test ids and added tests

packages/hooks/use-token/tests/index.test.tsx
Closes #1595 
It changed from Japanese to English on test for use-token.
no
none
=> test: fix test for use-token

packages/components/table/tests/table.test.tsx
Closes #1463   
Added test for Thead
No
Added test for nested headers.
I think we need to add a table with nested headers for stories and documents as well.
=> Enhance table test coverage

.changeset/thick-ducks-carry.md, packages/components/select/src/option-group.tsx, packages/components/select/src/option.tsx
Closes #1598 
isuueの指示通りにclassNameを変更しました。
=> fix: changed className

.changeset/nervous-shirts-tie.md, packages/components/resizable/src/resizable-trigger.tsx, packages/components/resizable/tests/resizable.test.tsx
Closes #1597
Changed `Resizable` component className methodology to BEM.
No change in beavior.
No change in beavior.
No.
Nothing.
=> Fix `Resizable` className to BEM

packages/components/modal/tests/drawer.test.tsx
Closes #1456 
Added test for drawer.tsx
The following section has not been fixed. The reason is that I couldn't successfully implement the drag emulation.
I would like to try any effective method if you have suggestions.
[L350](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/modal/src/drawer.tsx#L350)
[L387](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/modal/src/drawer.tsx#L387)
[L394](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/modal/src/drawer.tsx#L394)
=> Add Test for drawer

packages/components/editable/tests/editable.test.tsx
Closes #1453
Update tests and add `useEditableControl` tests.
No
=> Update tests and add `useEditableControl` tests

packages/components/carousel/tests/carousel.test.tsx
Closes #1450
Added `orientation` and `indicator` tests
NIL
NIL
No
=> Enhance Test Coverage for `@yamada-ui/carousel`

packages/hooks/use-focus/tests/index.test.tsx
Closes #1467
Added tests for focus hooks.
No
=> Added tests for focus hooks

docs/contexts/i18n-context.tsx
Enhance translation function flexibility.
No
=> Enhance translation function flexibility

packages/components/checkbox/tests/checkbox.test.tsx, packages/components/icon/tests/icon.test.tsx
=> fix some tests

.changeset/brave-planets-rescue.md, packages/components/charts/README.md, packages/components/color-picker/README.md, packages/components/infinite-scroll-area/README.md, packages/components/rating/README.md, packages/components/resizable/README.md, packages/components/ripple/README.md, packages/components/snacks/README.md, packages/components/stat/README.md, packages/components/toggle/README.md, packages/hooks/use-clipboard/README.md, packages/hooks/use-eye-dropper/README.md, packages/hooks/use-hover/README.md, packages/hooks/use-idle/README.md, packages/hooks/use-infinite-scroll/README.md, packages/hooks/use-local-storage/README.md, packages/hooks/use-media-query/README.md, packages/hooks/use-os/README.md, packages/hooks/use-window-event/README.md, plop/component/package-multi/README.md.hbs, plop/component/package/README.md.hbs, plop/hook/package/README.md.hbs, stories/components/data-display/markdown.stories.tsx
Closes #1644
Updated contribution guide links.
No
=> Updated contribution guide links

docs/contents/components/forms/year-picker/index.ja.mdx, docs/contents/components/forms/year-picker/index.mdx
Added label to `YearPicker` documentation.
No
=> Added label to `YearPicker` documentation

docs/contents/styled-system/text-and-layer-styles.mdx
Closes #1659 
The example code was not supposed to be translated.
`亀` was translated to `Turtle`, causing overflow.
Use `亀` for text content in both Japanese and English.
No
=> Updated example in layer styles

.changeset/forty-trees-care.md, packages/components/scroll-area/src/scroll-area.tsx
Closes #1620
Fixed error that occurred when using `ScrollArea` in `Next.js`.
Error occurred when using `ScrollArea` in `Next.js`.
Error does not occur.
No
=> Fixed error with `useLayoutEffect` in `ScrollArea`

.changeset/tiny-garlics-bow.md, packages/components/textarea/tests/textarea.test.tsx
Closes #1464
Added Textarea tests for enhance test coverage.
NIL
NIL
No
=> test(textarea): added rows textarea test and autosize textarea test

docs/components/mdx/index.tsx, docs/components/mdx/linked-heading.tsx, docs/theme/styles/mdx-styles.ts
Closes #1675 
Updated mdx component tag types and styles.
No
=> Updated mdx component tag types and styles

packages/components/radio/tests/radio-group.test.tsx, packages/components/radio/tests/radio.test.tsx
* I have rewritten the tests for the `Radio` component to be more resilient and easier to read.
=> Update tests for `Radio`

docs/ignored-build-step.sh
Closes #1689
Added check for docs directory existence.
No
=> Added check for docs directory existence

packages/hooks/use-pan-event/tests/index.test.tsx
Closes #1683
Fixed problem with `usePanEvent` tests failing occasionally.
No
=> Fixed problem with `usePanEvent` tests failing occasionally

packages/components/select/tests/select.test.tsx
Closes #1462
Added `select` tests for enhance test coverage.
No
=> added `select` tests

packages/components/avatar/tests/avatar-group.test.tsx
Closes # 
Modified Tesco code to split assignment based on the last study session.
=> Fix to destructuring assignment.

.gitignore, docs/contentlayer.config.example.json, docs/contentlayer.config.ts, docs/contents/community/contributing.ja.mdx, docs/contents/community/contributing.mdx, docs/utils/contentlayer.ts
Closes #1690
Supports `contentDirInclude` and `contentDirExclude`.
No
=> Supports `contentDirInclude` and `contentDirExclude`

docs/components/forms/search.tsx
Updated element refs and components in search modal.
No
=> Updated element refs and components in search modal

docs/contents/components/forms/color-picker/index.mdx, docs/contents/styled-system/theming/component-styles.mdx
Removed redundant codeblock placeholders.
No
=> Removed redundant codeblock placeholders

.changeset/selfish-glasses-brush.md, .changeset/seven-zoos-trade.md
related #1684
related #1711
Fix wrong `changeset` to `patch.
No
=> Fixed changeset to `patch`

packages/components/native-select/tests/native-select.test.tsx, packages/components/native-table/tests/native-table.test.tsx
Closes # 
Remove render and container.
=> fix: remove render and container

packages/components/file-button/tests/file-button.test.tsx
* I have rewritten the tests for the `FileButton` component to be more resilient and easier to read.
=> Update `FileButton` Tests

scripts/observe-pull-requests.ts
Updated reviewer count in script.
No
=> Updated reviewer count in script

scripts/create-issues.ts, scripts/utils.ts
Added create issues script.
No
=> Added create issues script

.changeset/swift-eggs-talk.md, packages/components/switch/src/switch.tsx, packages/theme/src/components/switch.ts
Closes #1906
Make the component headless.
No
=> Make the component headless

.changeset/chatty-monkeys-flash.md, packages/components/card/src/card.tsx, packages/theme/src/components/card.ts
Closes #1856 
made the card component headless
Nil
Nil
No
=> refactor: made the component headless

.changeset/nice-walls-boil.md, packages/components/segmented-control/src/segmented-control.tsx, packages/theme/src/components/segmented-control.ts
Closes #1899
Make the `segmented-control` component headless.
No.
=> Make the `segmented-control` component headless

packages/components/tabs/tests/tabs.test.tsx
* I have rewritten the tests for the `Tab` component to be more resilient and easier to read.
=> Update `Tabs` tests

packages/components/rating/tests/rating.test.tsx
Closes #1955
- one test case failed in `rating.test.tsx`
- delete one test case for rating component
=> fix: rating test

.changeset/famous-pears-worry.md, packages/components/stat/src/stat.tsx, packages/components/stat/tests/stat.test.tsx, packages/theme/src/components/stat.ts
This PR for https://github.com/yamada-ui/yamada-ui/issues/1904
Na
Na
No
=> refactor: stat-headless

packages/components/table/tests/table.test.tsx
Related #1952 
- remove `render` and `container` at `a11y`
- remove `data-testid`
- add test `enableRowSelection`
=> test(table): improved test code

.changeset/fair-hornets-allow.md, packages/components/breadcrumb/src/breadcrumb.tsx
Closes #1996
Fixed theme container style application.
No
=> Fixed theme container style application

.changeset/twelve-deers-wait.md, packages/components/skeleton/src/skeleton.tsx, packages/theme/src/components/skeleton.ts
Closes # #1901
make the skeleton component headless
No
=> refactor: make the skeleton component headless

.changeset/small-coins-rule.md, packages/components/tag/src/tag.tsx
Closes #1974
Simplified component structure.
No
=> Simplified component structure

docs/contents/hooks/use-breakpoint-effect.ja.mdx, docs/contents/hooks/use-breakpoint-effect.mdx, docs/contents/hooks/use-breakpoint-state.ja.mdx, docs/contents/hooks/use-breakpoint-state.mdx, docs/contents/hooks/use-update-breakpoint-effect.ja.mdx, docs/contents/hooks/use-update-breakpoint-effect.mdx, docs/contents/hooks/use-update-effect.ja.mdx
Closes #1976 
Added `useBreakpointEffect` documentation pages.
No
=> Added `useBreakpointEffect` documentation pages

.changeset/bright-phones-serve.md, packages/utils/src/assertion.ts, packages/utils/src/color.ts, packages/utils/src/dom.ts, packages/utils/src/function.ts, packages/utils/src/object.ts, packages/utils/src/react.tsx
Updated import paths for clarity.
No
=> Updated import paths for clarity

.changeset/quick-donkeys-push.md, packages/components/slider/src/range-slider.tsx, packages/components/slider/src/slider.tsx, packages/theme/src/components/slider.ts
Closes #1902
Made the Slider component headless
No
=> Make the Slider component headless

scripts/report-insights.ts
Updated report generation logic.
No
=> Updated report generation logic

.changeset/slimy-coats-flow.md, packages/components/number-input/src/number-input.tsx, packages/theme/src/components/number-input.ts
Closes #1887
make number-input component headless
No
=> refactor: make number-input component headless

.changeset/two-experts-compare.md, packages/components/resizable/src/resizable-item.tsx, packages/components/resizable/src/resizable-trigger.tsx, packages/components/resizable/src/resizable.tsx, packages/theme/src/components/resizable.ts
Closes #1896
Made the `Resizable` component headless
No
=> Make the `Resizable` component headless

.changeset/smooth-spiders-prove.md, .changeset/twelve-ties-wonder.md, packages/components/infinite-scroll-area/src/infinite-scroll-area.tsx, packages/core/src/generated-theme.types.ts, packages/theme/src/components/index.ts, packages/theme/src/components/infinite-scroll-area.ts
Closes #2030
Added theming to `InfiniteScrollArea` component.
No
=> Theming the `InfiniteScrollArea` component

examples/create-react-app/package.json, examples/hono/package.json, examples/nextjs-app/package.json, examples/nextjs-pages/package.json, examples/remix/package.json, examples/vite/package.json, pnpm-lock.yaml
Added new packages to examples.
No
=> Added new packages to examples

README.ja.md, README.md, packages/react/README.md, stories/components/data-display/markdown.stories.tsx
Updated README files with lucide component info
No
=> Updated README files with lucide component info

codecov.yml, scripts/coverage-issues.ts
Updated coverage thresholds in config and script.
No
=> Updated coverage thresholds in config and script

docs/pages/icons/list.tsx
Closes #2053
Swapped tooltip and aspectRatio wrappers.
No
=> Swapped tooltip and aspectRatio wrappers

.changeset/bright-lobsters-behave.md, .changeset/red-beers-explain.md, packages/components/infinite-scroll-area/src/infinite-scroll-area.tsx, packages/theme/src/components/infinite-scroll-area.ts
Closes #1873 
Make `infinite-scroll-area` component headless.
No
=> Make infinite-scroll-area component headless

.changeset/kind-crabs-teach.md, packages/components/tooltip/src/tooltip.tsx
Closes #2053
Improved accessibility and refactoring code.
No
=> Improved accessibility and refactoring code

.changeset/small-cycles-shout.md, packages/components/select/src/use-select.ts
Closes #2086
Simplified value handling in `Select`.
No
=> Simplified value handling in `Select`

docs/theme/semantics.ts
Closes #2092 
Updated color codes in themes.
No
=> Updated color codes in themes

docs/contexts/i18n-context.tsx, docs/utils/i18n.ts
Centralized i18n data handling functions.
No
=> Centralized i18n data handling functions

.changeset/clever-wombats-leave.md, packages/components/calendar/src/use-calendar.ts
Closes #2094
Fixed value update in calendar component.
No
=> Fixed value update in calendar component

.changeset/serious-candles-camp.md, packages/core/src/theme.ts
Closes #2097
Fixed object contamination in theme management.
No
=> Fixed object contamination in theme management

scripts/observe-issues.ts, scripts/observe-pull-requests.ts, scripts/report-insights.ts
Closes #2099
Updated discord notification groups in scripts.
No
=> Updated discord notification groups in scripts

.github/ISSUE_TEMPLATE/bug_report.ja.yml, .github/ISSUE_TEMPLATE/bug_report.yml
Added new os options to bug report forms.
No
=> Added new os options to bug report forms

packages/components/skeleton/tests/skeleton.test.tsx
Closes #2073 
add skeleton test with isLoaded
Nil
Nil
No
=> test(skeleton): add skeleton test with isLoaded

.changeset/hip-hornets-decide.md, packages/components/input/src/input-addon.tsx, packages/components/input/src/input-element.tsx, packages/components/input/src/input-group.tsx, packages/theme/src/components/input.ts
Closes #1874 
make input component headless
Nil
Nil
Nil
No
=> refactor(input): make input component headless

packages/components/progress/tests/circle-progress.test.tsx, packages/components/progress/tests/progress.test.tsx
=> fix: improved test code

.changeset/itchy-donuts-sleep.md, packages/components/modal/src/modal.tsx, packages/components/modal/tests/modal.test.tsx
=> Enhance `Modal` compoennt accessibility

stories/system/styles/breakpoint.stories.tsx
Updated breakpoint text descriptions.
No
=> Updated breakpoint text descriptions

stories/components/data-display/list.stories.tsx
Update icon imports and usage.
No
=> Update icon imports and usage

packages/components/button/tests/button-group.test.tsx, packages/components/button/tests/button.test.tsx, packages/components/button/tests/icon-button.test.tsx, packages/components/carousel/tests/carousel.test.tsx, packages/components/file-button/tests/file-button.test.tsx, packages/components/highlight/tests/highlight.test.tsx, packages/components/icon/tests/icon.test.tsx, packages/components/pagination/tests/pagination.test.tsx, packages/components/radio/tests/radio-group.test.tsx, packages/components/radio/tests/radio.test.tsx, packages/components/stepper/tests/stepper.test.tsx, packages/components/tooltip/tests/tooltip.test.tsx
Closes #2193  
Standardized self-closing tags by adding space
=> Standardized self-closing tags by adding space

.changeset/weak-dots-invite.md, packages/utils/src/assertion.ts
Expanded unit validation regex in isUnit.
No
=> Expanded unit validation regex in isUnit

packages/components/skeleton/tests/skeleton.test.tsx
Closes #2226 
- We have done refactor that passes the component directly within the a11y function
- Added test to see if doms in Skeleton are rendered correctly.
=> refactor: improve Skeleton test code

docs/components/mdx/editable-code-block.tsx
Closes #2236
Enhanced iframe theming support.
No
=> Enhanced iframe theming support

.changeset/twelve-pens-arrive.md, packages/components/indicator/tests/indicator.test.tsx, packages/components/progress/src/progress.tsx, packages/theme/src/components/progress.ts
Closes #1892
Make `Progress` component headless
No
=> Make `Progress` component headless

.changeset/giant-pears-lie.md, packages/components/calendar/src/use-date-picker.ts, packages/components/calendar/src/use-month-picker.ts, packages/components/calendar/src/use-multi-date-picker.ts, packages/components/calendar/src/use-range-date-picker.ts, packages/components/calendar/src/use-year-picker.ts
Closes #2232
Updated value propagation in pickers.
No
=> Updated value propagation in pickers

packages/components/list/tests/list.test.tsx
=> [List] rewrote unittests

.changeset/hungry-rocks-shake.md, packages/components/motion/package.json, packages/components/motion/tests/motion.test.tsx, packages/components/transitions/tests/slide-fade.test.tsx, packages/components/transitions/tests/slide.test.tsx, pnpm-lock.yaml
=> Updated dependencies

packages/components/layouts/tests/layouts.test.tsx
=> fix test of layouts

packages/components/motion/tests/motion.test.tsx, packages/components/transitions/tests/collapse.test.tsx, packages/components/transitions/tests/fade.test.tsx, packages/components/transitions/tests/scale-fade.test.tsx, packages/components/transitions/tests/slide-fade.test.tsx, packages/components/transitions/tests/slide.test.tsx
Refactoring of `motion` and `transitions` tests.
NIL
NIL
No
=> refactoring of `motion` and `transitions` tests

docs/contents/components/feedback/area-chart/index.ja.mdx, docs/contents/components/feedback/area-chart/index.mdx, docs/contents/components/feedback/bar-chart/index.ja.mdx, docs/contents/components/feedback/bar-chart/index.mdx, docs/contents/components/feedback/donut-chart/index.ja.mdx, docs/contents/components/feedback/donut-chart/index.mdx, docs/contents/components/feedback/line-chart/index.ja.mdx, docs/contents/components/feedback/line-chart/index.mdx, docs/contents/components/feedback/pie-chart/index.ja.mdx, docs/contents/components/feedback/pie-chart/index.mdx
Related #2254
Related #2223  
Added documentation of new features.
NIL
NIL
No
=> added charts documention

.changeset/large-students-cover.md, packages/components/calendar/src/multi-date-picker.tsx, packages/components/calendar/src/use-month.tsx, packages/components/calendar/src/use-multi-date-picker.ts
Closes #1919 
Enhance the accessibility of `MultiDatePicker` component
=> Enhance the accessibility of `MultiDatePicker` component

.changeset/mighty-scissors-run.md, packages/components/calendar/src/range-date-picker.tsx, packages/components/calendar/src/use-month.tsx
Closes #2266 
Incorrect Placement of aria-multiselectable in `RangeDatePicker` Component
=> Incorrect Placement of aria-multiselectable in `RangeDatePicker` Component

.changeset/proud-guests-complain.md, packages/components/calendar/src/date-picker.tsx, packages/components/calendar/src/use-date-picker.ts
Closes #1731 
Enhance the accessibility of `DatePicker`
=> Enhance the accessibility of `DatePicker`

package.json, packages/components/accordion/src/accordion.tsx, packages/components/portal/src/default-portal.tsx, packages/hooks/use-descendant/src/index.ts, packages/hooks/use-event-listener/src/index.ts, pnpm-lock.yaml, scripts/generate-css/index.ts
Updated dependencies and refactored code.
No
=> Updated dependencies and refactored code

packages/components/markdown/src/remark-ui-component.ts
Updated proxy target parameter name.
No
=> Updated proxy target parameter name

.changeset/yellow-lobsters-travel.md, packages/hooks/use-focus/src/index.ts
Closes #2307
Closes #2285
Fixed popover close issue on multiple opens.
No
=> Fixed popover close issue on multiple opens

docs/contents/components/forms/editable/index.ja.mdx, docs/contents/components/forms/editable/index.mdx
Updated invalid input documentation.
No
=> Updated invalid input documentation

docs/components/mdx/editable-code-block.tsx
=> fix: remove `UIComponents`

.changeset/wild-adults-punch.md, packages/components/layouts/src/stack.tsx
Closes #2313 
Fix typo in `Stack` component
=> Fix typo in `Stack` component

package.json, pnpm-lock.yaml
Related egoist/tsup/issues/1161
Description
Fixed version to 8.2.0.
No
=> Fixed version to 8.2.0

scripts/report-insights.ts
Fixed a bug where the numbers were not correct.
No
=> Fixed a bug where the numbers were not correct

.changeset/tall-walls-march.md, packages/components/calendar/src/calendar-utils.ts
Closes #2315 
Remove duplicate dates declaration in `getRangeDates` function
=> fix: remove duplicate dates declaration in getRangeDates function

packages/components/layouts/tests/layouts.test.tsx
Closes #2269 
Enhance Test Coverage for `@yamada-ui/layouts`
=> Enhance Test Coverage for `@yamada-ui/layouts`

.github/composite-actions/check-modified-files/action.yml, .github/workflows/quality.yml
Optimized output variable assignments.
No
=> Optimized output variable assignments

packages/components/breadcrumb/tests/breadcrumb.test.tsx
=> fix: improved test

.github/composite-actions/update-docs/action.yml
Updated GitHub action dependencies.
No
=> Updated GitHub action dependencies

docs/pages/api/github/observe/update-pull-requests.ts, docs/pages/api/github/webhook/pull-request/opened.ts
Expanded conditions for skipping pr actions.
No
=> Expanded conditions for skipping pr actions

.changeset/cuddly-mayflies-refuse.md, .changeset/fluffy-maps-bake.md, packages/components/icon/src/icon.tsx, packages/theme/src/components/icon.ts
Fixed a bug where `Icon`'s `baseStyle` was set to `defaultProps`.
No
=> Fixed a bug where `Icon`'s `baseStyle` was set to `defaultProps`

.changeset/proud-snakes-wave.md, .changeset/rare-pears-teach.md, packages/components/file-button/src/file-button.tsx, packages/core/src/components/component.types.ts, packages/core/src/components/use-component-style.tsx, packages/core/src/css/css.types.ts, packages/core/src/theme.ts, packages/theme/src/components/file-button.ts, packages/theme/src/components/index.ts
Closes #2210
Added theme support and refactored code.
No
=> Added theme support and refactored code

packages/hooks/use-event-listener/tests/index.test.ts
Closes #2077
Added cleanup function test.
No
=> Added cleanup function test

packages/components/dropzone/tests/dropzone.test.tsx
Closes #2063
Added tests for accept, reject, idle states.
No
=> Added tests for accept, reject, idle states

.changeset/little-students-itch.md, docs/theme/components/button.ts, docs/theme/components/mark.ts, packages/core/src/theme.types.ts
Updated type definitions and styles.
No
=> Updated type definitions and styles

.github/workflows/quality.yml
Added `changeset-release/docs` to CI triggers.
No
=> Added `changeset-release/docs` to CI triggers

.changeset/blue-crabs-pretend.md, .changeset/nervous-papayas-retire.md, .changeset/proud-snakes-wave.md, .changeset/six-dragons-grab.md, packages/components/button/src/button.tsx, packages/components/file-button/src/file-button.tsx, packages/core/src/components/use-component-style.tsx, packages/core/src/css/css.types.ts, packages/core/src/theme.ts, packages/core/src/theme.types.ts
Closes #2338
Update theming logic and props handling.
No
=> Update theming logic and props handling

docs/contents/styled-system/theming/component-styles.ja.mdx, docs/contents/styled-system/theming/component-styles.mdx
Updated Japanese and English documentation.
No
=> Updated Japanese and English documentation

docs/contents/components/data-display/carousel/index.ja.mdx, docs/contents/components/data-display/carousel/index.mdx
Updated terminology and added event handlers.
No
=> Updated terminology and added event handlers

.github/composite-actions/update-docs/action.yml, .github/workflows/release.yml
Updated token references in actions.
No
=> Updated token references in actions

.changeset/angry-tips-move.md, packages/components/select/src/use-select.ts
Closes #2365
Fixed selection issue in `Select` components.
No
=> Fixed selection issue in `Select` components

docs/contents/components/forms/file-button/accessibility.ja.mdx, docs/contents/components/forms/file-button/accessibility.mdx, docs/contents/components/forms/file-button/theming.ja.mdx, docs/contents/components/forms/file-button/theming.mdx
Updated documentation order for fileButton.
No
=> Updated documentation order for fileButton

.changeset/little-walls-build.md, packages/components/icon/src/icon.tsx, packages/components/image/src/image.tsx, packages/components/tag/tests/tag.test.tsx
Closes #2376
Fixed `fontSize` and `boxSize` handling.
No
=> Fixed `fontSize` and `boxSize` handling

.changeset/shaggy-lies-suffer.md, packages/components/color-picker/src/color-swatch.tsx, packages/components/color-picker/src/use-color-selector.ts
Closes #2390
Updated type definitions for color props.
No
=> Updated type definitions for color props

.changeset/breezy-garlics-jog.md, packages/components/autocomplete/src/autocomplete-list.tsx, packages/components/modal/src/modal.tsx, packages/components/motion/src/motion.tsx, packages/components/popover/src/popover-content.tsx, packages/components/select/src/select-list.tsx
Closes #2391
Corrected type definitions and props handling.
No
=> Corrected type definitions and props handling

.changeset/nice-clouds-rhyme.md, .changeset/witty-spiders-bathe.md, packages/components/color-picker/src/color-picker.tsx, packages/components/color-picker/src/use-color-picker.ts, stories/components/forms/color-picker.stories.tsx
Closes #2403
Closes #2399
Added `onClose` prop to children handling.
No
=> Added `onClose` prop to children handling

docs/constant/members.ts
Added Hinata Ohyama to members list.
No
=> Added Hinata Ohyama to members list

.changeset/dull-ghosts-beg.md, packages/theme/src/semantics.ts, packages/theme/src/tokens/spaces.ts
Closes #2401
Moved spaces to semantics tokens.
No
=> Moved spaces to semantics tokens

.github/workflows/insight-report.yml
Adjusted weekstart calculation in CI script.
No
=> Adjusted weekstart calculation in CI script

docs/pages/insights/user-chart.tsx
Added locale support to user names.
No
=> Added locale support to user names

docs/pages/insights/insights-header.tsx
Added period suggest to Insights page.
No
=> Added period suggest to Insights page

.changeset/spicy-mugs-doubt.md, packages/components/charts/src/bar-chart.tsx, packages/components/charts/src/chart.types.ts, packages/components/charts/src/index.ts, packages/components/charts/src/use-bar-chart.tsx
Added cell props to BarChart and updated types.
No
=> Added cell props to BarChart and updated types

docs/pages/insights/insights-header.tsx, docs/pages/insights/insights-utils.ts
Updated date handling and imports.
No
=> Updated date handling and imports

.changeset/six-buses-count.md, .changeset/sweet-maps-jam.md, packages/components/notice/src/notice.tsx, packages/components/snacks/src/use-snacks.tsx, packages/core/src/theme.types.ts, stories/hooks/use-notice.stories.tsx, stories/hooks/use-snacks.stories.tsx
Closes #2437
Added `closeStrategy`.
No
=> Added `closeStrategy`

.changeset/late-days-hug.md, packages/theme/src/tokens/shadows.ts
Fix a full-width space in the token to half-width space.
No
=> Fix a full-width space in the token to half-width space.

docs/.eslintrc.json, docs/package.json, docs/pages/api/github/observe/index.api.ts, docs/pages/api/github/observe/update-issues.test.ts, docs/pages/api/github/observe/update-issues.ts, docs/pages/api/github/observe/update-pull-request.test.ts, docs/pages/api/github/observe/update-pull-requests.ts, docs/pages/api/github/webhook/pull-request/review-request-removed.ts, docs/scripts/setup-test.ts, docs/utils/github.ts, docs/vitest.config.mts, package.json, pnpm-lock.yaml
=> Added api tests

lefthook.yaml
Update pre-commit and commit-msg hooks.
No
=> Update pre-commit and commit-msg hooks

docs/pages/examples/authentication/company.tsx, docs/pages/examples/cards/bookmark-card.tsx, docs/pages/examples/cards/notification-card.tsx, docs/pages/examples/dashboard/cards.tsx, docs/pages/examples/mail/detail.tsx
Closes https://github.com/yamada-ui/yamada-ui/issues/2494
- As the subject suggests, I have changed the deprecated size prop in the Icon component to fontSize.
- reference: [Corresponding code](https://github.com/yamada-ui/yamada-ui/blob/1473921f8aeb4e2040d0337aee3b101e78884749/packages/components/icon/src/icon.tsx#L17C6-L24)
- None
- None
- No
- None
=> refactor: Deprecated props are being used in the example pages. 

.changeset/silver-poets-happen.md, packages/components/popover/src/popover-content.tsx
Added `containerProps` to `PopoverContent`.
No
=> Added `containerProps` to `PopoverContent`

packages/components/loading/tests/loading-provider.test.tsx
Closes # 
#2355 
Add test for loading-provider force
No
=> Add test for loading-provider force

.github/composite-actions/sync-docs/action.yml, .github/workflows/docs.yml, .github/workflows/quality.yml, .github/workflows/release.yml, docs/pages/api/github/observe/update-pull-requests.ts, docs/pages/api/github/webhook/pull-request/opened.ts
Added create PR GitHub actions.
No
=> Added create PR GitHub actions

.changeset/wicked-tigers-rest.md, packages/core/src/components/use-component-style.tsx, packages/core/src/css/css.types.ts, packages/core/src/theme.types.ts
Updated type definitions and logic.
No
=> Updated type definitions and logic

stories/system/styles/interpolation.stories.tsx
Closes #2580
Add interpolation stories file.
No
=> Add interpolation stories file

docs/contents/components/forms/month-picker/index.ja.mdx, docs/contents/components/forms/month-picker/index.mdx
Closes #2424 
Update MonthPicker default type description
Default type is `year`.
Default type is `month`.
No
=> docs: Update MonthPicker default type description

.changeset/itchy-chefs-sniff.md, packages/core/src/components/should-forward-prop.ts
Closes #2563
Closes #2561
Simplified `shouldForwardProp` logic.
No
=> Simplified `shouldForwardProp` logic

docs/pages/examples/mail/sidebar.tsx, docs/pages/icons/icon-drawer.tsx, docs/pages/icons/list.tsx, docs/pages/icons/not-found.tsx, packages/components/dropzone/src/dropzone.tsx, packages/components/loading/tests/loading.test.tsx, stories/components/data-display/infinite-scroll-area.stories.tsx, stories/components/media-and-icons/avatar.stories.tsx
Closes #2507
Updated icon size properties to fontSize.
No
=> Updated icon size properties to fontSize

docs/components/mdx/select-package-managers.tsx, docs/contents/components/media-and-icons/fontawesome/index.ja.mdx, docs/contents/components/media-and-icons/fontawesome/index.mdx
Closes #2449
Updated package manager component logic.
No
=> Updated package manager component logic

.changeset/red-bugs-approve.md, packages/components/color-picker/src/use-color-selector.ts
Closes #2463
Optimize format handling logic.
No
=> Optimize format handling logic

.changeset/cool-years-begin.md, .changeset/giant-wombats-shake.md, packages/components/carousel/src/carousel.tsx, packages/core/src/config/calc.ts, packages/utils/src/assertion.ts, packages/utils/tests/assertion.test.ts, stories/system/styles/calc.stories.tsx
Closes #2600
Update value check to use `isNumeric` function.
No
=> Update value check to use `isNumeric` function

docs/pages/insights/insights-header.tsx
Simplified date manipulation logic.
No
=> Simplified date manipulation logic

.changeset/rotten-lemons-tap.md, packages/components/charts/src/chart.types.ts, packages/components/charts/src/donut-chart.tsx, packages/components/charts/src/index.ts, packages/components/charts/src/use-chart-label.ts, packages/components/charts/tests/donut-chart.test.tsx, packages/theme/src/components/donut-chart.ts, stories/components/data-display/donut-chart.stories.tsx
Closes #2625
Added ability to display `label` on `DonutChart`.
NIL
Text can now be displayed in the middle of the donut.
No
=> Added ability to display `label` on `DonutChart`

docs/components/mdx/color-palettes.tsx, docs/contents/styled-system/semantic-tokens.ja.mdx, docs/contents/styled-system/semantic-tokens.mdx, docs/contents/styled-system/theming/customize-theme.ja.mdx, docs/contents/styled-system/theming/customize-theme.mdx, docs/contents/styled-system/theming/default-theme.ja.mdx, docs/contents/styled-system/theming/default-theme.mdx, packages/utils/src/color.ts, stories/components.tsx
Closes #2465
Rename hue to tone in code and docs.
No
=> Rename hue to tone in code and docs

docs/contents/styled-system/cli.ja.mdx, docs/contents/styled-system/cli.mdx
Closes #2466
Update CLI documentation content and structure.
No
=> Update CLI documentation content and structure

docs/contents/components/data-display/table/index.ja.mdx, docs/contents/components/data-display/table/index.mdx
Closes #2438
Add row double click event handling guide.
No
=> Add row double click event handling guide

docs/contents/styled-system/cli.ja.mdx, docs/contents/styled-system/cli.mdx
=> Updated label

docs/contents/components/media-and-icons/image/props.ja.mdx, docs/contents/components/media-and-icons/image/props.mdx, docs/contents/components/media-and-icons/native-image/index.ja.mdx, docs/contents/components/media-and-icons/native-image/index.mdx, docs/i18n/content.en.json, docs/i18n/content.ja.json, docs/scripts/component/props.ts
Closes #2630
Added `NativeImage` documentation.
No
=> Added `NativeImage` documentation

docs/pages/insights/insights-utils.ts
Added validation for invalid date strings.
No
=> Added validation for invalid date strings

docs/contents/components/data-display/radial-chart/index.ja.mdx, docs/contents/components/data-display/radial-chart/index.mdx
Closes #2660
Updated radial chart endAngle in docs.
No
=> Updated radial chart endAngle in docs

docs/components/mdx/users.tsx, docs/constant/contributors.ts, docs/constant/emeriti.ts, docs/constant/index.ts, docs/constant/maintainers.ts, docs/constant/members.ts, docs/contents/community/team.ja.mdx, docs/contents/community/team.mdx, docs/scripts/content/contributors.ts
Add emeriti category and update lists.
No
=> Add emeriti category and update lists

docs/contents/components/data-display/donut-chart/index.ja.mdx, docs/contents/components/data-display/donut-chart/index.mdx
Closes #2683 
Add documentation about custom labels for DonutChart.
No
=> docs: add custom labels for DonutChart

docs/contents/components/other/motion/index.ja.mdx, docs/contents/components/other/motion/index.mdx, docs/contents/styled-system/animation.ja.mdx, docs/contents/styled-system/animation.mdx
Closes #2673 
Update text in non-hover element
No
=> docs: Update text in non-hover element

docs/utils/array.ts
Updated MixedArray type definition.
No
=> Updated MixedArray type definition

docs/contents/components/forms/index.mdx
Closes #2711
Update forms documentation title.
No
=> Update forms documentation title

docs/components/forms/copy-button.tsx
=> Add `zIndex` in CopyButton

.changeset/dirty-eagles-poke.md, packages/components/motion/src/factory.ts, packages/components/motion/src/motion-forward-ref.tsx, packages/components/motion/src/motion.tsx, packages/core/src/components/forward-ref.ts, packages/core/src/styled.ts
Closes #2707
Simplify motion component logic.
No
=> Simplify motion component logic

scripts/changelog.ts
Improved error handling in changelog reader.
No
=> Improved error handling in changelog reader

.github/workflows/docs.yml
=> Fixed docs workflow

docs/constant/contributors.ts, docs/constant/maintainers.ts, docs/constant/members.ts, docs/pages/insights/insights-utils.ts
Updated contributors and member details.
No
=> Updated contributors and member details

.changeset/swift-experts-unite.md, packages/core/src/config/animation.ts, packages/core/src/config/at-rule.ts, packages/core/src/config/index.ts, packages/core/src/config/utils.ts, packages/core/src/css/css.ts, packages/core/src/css/var.ts, packages/core/src/theme.ts, packages/core/src/theme.types.ts
Closes #2738
Fixed a bug where `$` could not be used within the theme.
No
=> Fixed a bug where `$` could not be used within the theme

packages/components/autocomplete/src/autocomplete.tsx, packages/components/transitions/src/collapse.tsx, packages/components/transitions/src/fade.tsx, packages/components/transitions/src/scale-fade.tsx, packages/components/transitions/src/slide-fade.tsx, packages/components/transitions/src/slide.tsx
Reorganize type definitions in files.
No
=> Reorganize type definitions in files

.changeset/sweet-toys-type.md, packages/core/src/components/should-forward-prop.ts, packages/core/src/css/css.ts, packages/core/src/pseudos.ts, packages/core/src/styles.ts, scripts/generate-css/styles.ts
Closes #2749
Update pseudo and attribute selectors.
No
=> Update pseudo and attribute selectors

.changeset/thin-singers-exercise.md, packages/components/switch/src/switch.tsx
Closes #2745
I modified the switch component to properly use the transition prop.
=> The Switch component type is wrong

.changeset/smooth-lizards-hang.md, packages/core/src/css/breakpoint.ts, packages/core/src/theme.types.ts
Closes #2751
Updated breakpoint base logic handling.
No
=> Updated breakpoint base logic handling

packages/components/color-picker/tests/alpha-slider.test.tsx
Added a test case for pointer events for AlphaSlider.
This time I am using userEvent instead of fireEvent.
No
=> test: add test for AlphaSlider component with pointer events

packages/components/select/tests/select.test.tsx
=> fix: delete commentout

.changeset/popular-singers-joke.md, packages/hooks/use-descendant/src/index.ts
Closes #2782
I refactored the code to use console.warn instead of throw Error.
=> refactor: change error handling in sortNodes to use console.warn

docs/scripts/content/styled-system.ts
Update data extraction and parsing logic.
No
=> Update data extraction and parsing logic

packages/components/color-picker/tests/color-picker.test.tsx
Related: https://github.com/yamada-ui/yamada-ui/issues/1967
Add test for ColorPickerEyeDropper cloning children
No
=> feat: add test for ColorPickerEyeDropper cloning children

docs/contents/components/forms/autocomplete/index.ja.mdx, docs/contents/components/forms/autocomplete/index.mdx
=> dosc: change type definition of items in autocomplete grouping example

.changeset/perfect-windows-cover.md, packages/components/calendar/src/use-month.tsx, packages/components/calendar/tests/calendar.test.tsx, packages/components/calendar/tests/date-picker.test.tsx, packages/components/calendar/tests/multi-date-picker.test.tsx, packages/components/calendar/tests/range-date-picker.test.tsx
Closes #2828
Corrected date-value in `useMonth`.
No
=> Corrected date-value in `useMonth`

docs/contents/getting-started/advanced.ja.mdx, docs/contents/getting-started/advanced.mdx, docs/contents/hooks/use-breakpoint-value.ja.mdx, docs/contents/hooks/use-breakpoint-value.mdx, docs/contents/styled-system/responsive-styles.ja.mdx, docs/contents/styled-system/responsive-styles.mdx, stories/hooks/use-breakpoint.stories.tsx
Closes #2775 
Add `2xl` breakpoint to useBreakpointValue example.
The display shows `2xl`, but  the color did not change.
At `2xl`, the color  changes.
No
=> Add 2xl breakpoint to useBreakpointValue example

.changeset/big-bottles-jog.md, .changeset/nervous-avocados-occur.md, packages/components/input/src/input-addon.tsx, packages/components/input/src/input-context.tsx, packages/components/input/src/input-element.tsx, packages/components/input/src/input-group.tsx, packages/core/src/config/vars.ts, packages/core/src/css/breakpoint.ts, packages/core/src/css/css.ts, packages/core/src/css/use-var.ts, packages/core/src/theme.ts, packages/core/tests/var.test.tsx
Closes #2706
Updated `Input` component handling.
No
=> Updated `Input` component handling

.github/workflows/docs.yml
Update pr condition and add checks.
No
=> Update pr condition and add checks

scripts/report-insights.ts
Closes #2833
- Fixed a bug where the date displayed on the terminal was -9 hours.
- Fixed a bug where the number of reviews and approvals was not being obtained correctly.
No
=> Fixed insight script

packages/components/input/src/input-context.tsx, packages/components/input/src/input-element.tsx, packages/components/input/src/input-group.tsx
Add fieldFontSize to input context and elements.
No
=> Add fieldFontSize to input context and elements

.changeset/fluffy-actors-eat.md, packages/components/breadcrumb/src/breadcrumb.tsx
Closes #2853  
Set `displayName` and `__ui__` after each component definition.
=> Set `displayName` and `__ui__` after each component definition.

.changeset/serious-camels-play.md, packages/components/skeleton/src/skeleton-circle.tsx, packages/components/skeleton/src/skeleton-text.tsx, packages/components/skeleton/src/skeleton.tsx
Closes #2902 
Set displayName and __ui__ for the Skeleton component
=> Set displayName and __ui__ for the Skeleton component 

.changeset/honest-dragons-trade.md, packages/components/visually-hidden/src/visually-hidden.tsx
Closes #2916
Added displayname and ui for visuallyhidden
On the inspect tab, the component name will be visible
No
=> feat: add display name for visually hidden elements

.changeset/flat-tools-hang.md, .changeset/moody-ravens-travel.md, packages/components/accordion/src/accordion-item.tsx, packages/components/carousel/src/carousel.tsx, packages/components/form-control/src/fieldset.tsx, packages/components/form-control/src/form-control.tsx, packages/components/modal/src/dialog.tsx, packages/components/modal/src/modal.tsx, packages/components/slider/src/range-slider.tsx, packages/components/slider/src/slider.tsx, packages/components/stat/src/stat.tsx, packages/components/tabs/src/tabs.tsx, packages/utils/src/react.tsx
=> Added `findChild`

packages/components/pagination/src/pagination.tsx, packages/components/pagination/src/use-pagination.ts, packages/components/skeleton/src/skeleton-text.tsx, packages/components/skeleton/src/skeleton.tsx
Updated variable bindings for clarity.
No
=> Updated variable bindings for clarity

.changeset/cuddly-frogs-heal.md, packages/components/radio/src/radio-group.tsx, packages/components/radio/src/radio.tsx
=> feat: set ui after each component definition

.changeset/beige-lamps-serve.md, packages/components/alert/src/alert.tsx
Closes #2849
add displayName and __ui__ to alert component.
=> fix: add displayName and __ui__ to alert component

.changeset/thick-games-pretend.md, packages/components/color-picker/src/alpha-slider.tsx, packages/components/color-picker/src/color-picker.tsx, packages/components/color-picker/src/color-selector-body.tsx, packages/components/color-picker/src/color-selector-channels.tsx, packages/components/color-picker/src/color-selector-eye-dropper.tsx, packages/components/color-picker/src/color-selector-sliders.tsx, packages/components/color-picker/src/color-selector-swatches.tsx, packages/components/color-picker/src/color-selector.tsx, packages/components/color-picker/src/color-swatch.tsx, packages/components/color-picker/src/hue-slider.tsx, packages/components/color-picker/src/saturation-slider.tsx
Closes #2861
Set `displayName` and `__ui__` for each component in the color picker.
=> feat: set displayName and __ui__ for color-picker

.changeset/ninety-boats-sniff.md, packages/core/src/components/component.types.ts, packages/utils/src/index.types.ts
Added `FunctionComponent` and `FC` type.
No
=> Added `FunctionComponent` and `FC` type

.changeset/brown-hairs-unite.md, packages/components/accordion/src/accordion-item.tsx, packages/components/accordion/src/accordion-label.tsx, packages/components/accordion/src/accordion-panel.tsx, packages/components/accordion/src/accordion.tsx
=> DisplayName set for the component of `accordion`

packages/components/calendar/tests/calendar.test.tsx
Added waitFor in calendar tests.
No
=> Added waitFor in calendar tests

docs/ignored-build-step.sh
Simplified branch condition checks in script.
No
=> Simplified branch condition checks in script

.changeset/eight-geese-help.md, packages/components/tabs/src/tab-list.tsx, packages/components/tabs/src/tab-panel.tsx, packages/components/tabs/src/tab-panels.tsx, packages/components/tabs/src/tab.tsx, packages/components/tabs/src/tabs.tsx
Closes #2909 
Set `displayName` and `__ui__`.
=> Set displayName and __ui__ at @yamada-ui/tabs

docs/contents/components/forms/file-input/index.ja.mdx, docs/contents/components/forms/file-input/index.mdx, docs/contents/components/forms/input/index.ja.mdx, docs/contents/components/forms/input/index.mdx, stories/components/forms/file-input.stories.tsx
Changed `isClick` to `isClickable`.
No
=> Changed `isClick` to `isClickable`

.changeset/honest-deers-notice.md, packages/components/carousel/src/carousel-control.tsx, packages/components/carousel/src/carousel-indicators.tsx, packages/components/carousel/src/carousel-slide.tsx, packages/components/carousel/src/carousel.tsx
Closes #2857
Set `displayName` and `__ui__` and import `FC` from @yamada-ui/core to do that.
=> Set `displayName` and ` __ui__ ` at `@yamada-ui/carousel`

.changeset/smooth-lemons-help.md, packages/components/close-button/src/close-button.tsx
Closes #2860 
set for the component of `@yamada-ui/close-button`
=> feat: set display name and UI for close-button

.changeset/fair-socks-reflect.md, packages/components/native-table/src/native-table.tsx, packages/components/native-table/src/table-caption.tsx, packages/components/native-table/src/table-container.tsx, packages/components/native-table/src/tbody.tsx, packages/components/native-table/src/td.tsx, packages/components/native-table/src/tfoot.tsx, packages/components/native-table/src/th.tsx, packages/components/native-table/src/thead.tsx, packages/components/native-table/src/tr.tsx
=> Set the `displayName` and `__ui__` for `@yamada-ui/native-table`

.changeset/odd-beers-tease.md, packages/components/native-select/src/native-select.tsx
=> Set the `displayName` and `__ui__` for `@yamada-ui/native-select`

.changeset/warm-buckets-build.md, packages/components/card/src/card.tsx
=> Set the `displayName` and `__ui__` for `@yamada-ui/card`

.changeset/lemon-beers-press.md, packages/components/modal/src/dialog-body.tsx, packages/components/modal/src/dialog-close-button.tsx, packages/components/modal/src/dialog-footer.tsx, packages/components/modal/src/dialog-header.tsx, packages/components/modal/src/dialog-overlay.tsx, packages/components/modal/src/dialog.tsx, packages/components/modal/src/drawer-body.tsx, packages/components/modal/src/drawer-close-button.tsx, packages/components/modal/src/drawer-content.tsx, packages/components/modal/src/drawer-drag-bar.tsx, packages/components/modal/src/drawer-footer.tsx, packages/components/modal/src/drawer-header.tsx, packages/components/modal/src/drawer-overlay.tsx, packages/components/modal/src/drawer.tsx, packages/components/modal/src/modal-body.tsx, packages/components/modal/src/modal-close-button.tsx, packages/components/modal/src/modal-content.tsx, packages/components/modal/src/modal-footer.tsx, packages/components/modal/src/modal-header.tsx, packages/components/modal/src/modal-overlay.tsx
Closes #2883 
Set `displayName` and `__ui__`. (`Drawer`, `Dialog`, `Modal` component)
=> Set displayName and __ui__ at `@yamada-ui/modal`

.changeset/nine-kings-hide.md, packages/components/alert/src/alert.tsx
=> Set `displayName` and `__ui__` in `@yamada-ui/alert`.

docs/constant/contributors.ts, docs/constant/emeriti.ts, docs/constant/maintainers.ts, docs/constant/members.ts
Update contributor and member lists.
No
=> Update contributor and member lists

.changeset/fluffy-jokes-behave.md, packages/components/autocomplete/src/autocomplete-create.tsx, packages/components/autocomplete/src/autocomplete-empty.tsx, packages/components/autocomplete/src/autocomplete-option.tsx
=> Fix component name in `@yamada-ui/autocomplete`

plop/component/package-multi/src/{{dashCase packageName}}.tsx.hbs, plop/component/package/src/{{dashCase packageName}}.tsx.hbs
=> fix: add `displayName` and `__ui__` in plop template

scripts/dependency-build.ts
Optimized package build process in script.
No
=> Optimized package build process in script

.changeset/many-horses-nail.md, packages/components/file-input/src/file-input.tsx
=> Set `displayName` and `__ui__` for `@yamada-ui/file-input`

.changeset/tricky-rice-move.md, packages/components/pin-input/src/pin-input.tsx
=> fix: displayName is not set for the component of "@yamada-ui/pin-input"

.changeset/three-taxis-sniff.md, packages/components/progress/src/circle-progress.tsx, packages/components/progress/src/progress.tsx
=> fix: displayName is not set for the component of "@yamada-ui/progress"

.changeset/strong-llamas-remember.md, packages/components/tag/src/tag.tsx
Rename close components to tag prefix.
No
=> Rename close components to tag prefix

.changeset/swift-gorillas-watch.md, packages/components/progress/src/circle-progress.tsx
Updated component structure and naming.
No
=> Updated component structure and naming

.changeset/great-adults-push.md, packages/components/dropzone/src/dropzone.tsx
Updated dropzone component names.
No
=> Updated dropzone component names

.changeset/mean-poems-turn.md, packages/components/file-button/src/file-button.tsx
Closes https://github.com/yamada-ui/yamada-ui/issues/2864
`displayName` is not set for the component of "@yamada-ui/file-button"
`displayName` is not set for the component as of now.
added `displayName` and `__ui__` properties
No
=> feat(file-button): add displayName and __ui__ properties

packages/components/snacks/package.json, packages/components/snacks/src/snacks.tsx, pnpm-lock.yaml
Simplified dependency and variable usage.
No
=> Simplified dependency and variable usage

docs/components/navigation/table-of-contents.tsx
Remove unused `useToken`, adjust padding logic.
No
=> Remove unused `useToken`, adjust padding logic

packages/core/src/css/var.ts
Closes #3065
Simplified condition in `createVar` function.
No
=> Simplified condition in `createVar` function

.changeset/plenty-shoes-run.md, .changeset/smart-rabbits-hide.md, examples/next/pages/pages/index.tsx, packages/components/slider/src/range-slider.tsx, packages/components/slider/src/slider.tsx
Closes #3071 
Closes #3070
Fixed `Slider` and `RangeSlider` components.
No
=> Fixed `Slider` and `RangeSlider` components

.changeset/kind-keys-tell.md, packages/components/carousel/package.json, packages/components/carousel/src/carousel-control.tsx, packages/components/carousel/src/carousel-indicators.tsx, packages/components/carousel/src/carousel-slide.tsx, packages/components/carousel/src/carousel.tsx, packages/components/carousel/src/use-carousel.ts, pnpm-lock.yaml
Updated package dependencies and code cleanup.
No
=> Updated package dependencies and code cleanup

.changeset/odd-adults-float.md, packages/next/src/image.tsx, packages/next/src/link.tsx
=> set the displayName and __ui__ of the Link component

docs/pages/examples/dashboard/header.tsx, docs/pages/examples/dashboard/index.tsx, docs/pages/examples/mail/detail.tsx, docs/pages/examples/mail/header.tsx, docs/pages/examples/mail/inbox.tsx, docs/pages/examples/music/sidebar.tsx
Standardize prop definitions to interfaces.
No
=> Standardize prop definitions to interfaces

examples/create-react-app/src/components/layouts/header.tsx, examples/hono/src/components/layouts/header.tsx, examples/next/app/components/layouts/header.tsx, examples/next/pages/components/layouts/header.tsx, examples/remix/app/components/layouts/header.tsx, examples/vite/src/components/layouts/header.tsx
Optimized imports and updated interfaces.
No
=> Optimized imports and updated interfaces

packages/components/avatar/src/avatar.tsx, packages/components/carousel/src/carousel.tsx, packages/components/color-picker/src/color-picker.tsx, packages/components/native-table/tests/native-table.test.tsx, packages/components/rating/src/rating-item.tsx, packages/components/select/src/option.tsx, packages/components/stepper/src/use-stepper.ts, packages/components/tabs/src/tabs-context.tsx, packages/components/toggle/src/toggle-group.tsx
Convert type aliases to interfaces.
No
=> Convert type aliases to interfaces

packages/theme/src/components/checkbox.ts, packages/theme/src/components/radio.ts
Updated hover and disabled styles.
No
=> Updated hover and disabled styles

.changeset/unlucky-llamas-add.md, packages/components/snacks/src/snacks.tsx, packages/components/snacks/src/use-snacks.tsx
=> Set `displayName` and `__ui__` for `@yamada-ui/snacks`

.changeset/chilly-pens-end.md, .changeset/fuzzy-apes-shake.md, packages/components/calendar/src/date-picker.tsx, packages/components/calendar/src/use-calendar-picker.ts, packages/components/calendar/src/use-date-picker.ts, packages/components/calendar/src/use-month-picker.ts, packages/components/calendar/src/use-multi-date-picker.ts, packages/components/calendar/src/use-range-date-picker.ts, packages/components/calendar/src/use-year-picker.ts, packages/components/color-picker/src/color-picker.tsx, packages/components/color-picker/src/use-color-picker.ts, packages/core/src/pseudos.ts, packages/theme/src/components/color-picker.ts, packages/theme/src/components/date-picker.ts
Closes #3090
Fixed `allowInput` style.
No
=> Fixed `allowInput` style

.changeset/sweet-deers-repair.md, packages/theme/src/components/input.ts
Update transition properties.
No
=> Update transition properties

.changeset/thick-horses-watch.md, docs/components/mdx/package-managers.tsx, packages/components/table/src/use-table.tsx
Closes #3115 
Closes #3102 
Related #3114
Related #3003
Update type imports and interfaces.
=> Update type imports and interfaces

.changeset/mean-monkeys-sell.md, packages/core/src/components/use-component-style.tsx
Closes #3140
Fixed undefined variant or size bug in styles.
No
=> Fixed undefined variant or size bug in styles

.changeset/moody-shirts-eat.md, cspell.json, packages/components/modal/src/dialog-close-button.tsx, packages/components/modal/src/drawer-content.tsx, packages/components/modal/src/modal-body.tsx, packages/components/modal/src/modal-close-button.tsx, packages/components/modal/src/modal-content.tsx, packages/components/modal/src/modal-context.ts, packages/components/modal/src/modal-header.tsx, packages/components/modal/src/modal-overlay.tsx, packages/components/modal/src/modal.tsx, packages/components/modal/tests/modal.test.tsx
Closes #3132
Added accessibility attributes to modal.
No
=> Added accessibility attributes to modal

.changeset/proud-lemons-beg.md, packages/components/motion/src/motion.tsx
=> displayName is not set for the component of "@yamada-ui/motion"

.changeset/strong-ducks-pay.md, packages/components/infinite-scroll-area/src/infinite-scroll-area.tsx
Closes #2873 
set the `displayName` and  `__ui__ ` of the `infinite scroll area` component
No
=> chore: set displayName for infinite-scroll-area

docs/contents/components/data-display/tag/accessibility.ja.mdx, docs/contents/components/data-display/tag/accessibility.mdx
Added accessibility info for Tag component.
No
=> Added accessibility info for Tag component

.changeset/tidy-starfishes-sort.md, packages/theme/src/components/button.ts
Added 2xl size to button styles.
No
=> Added 2xl size to button styles

docs/contents/components/overlay/context-menu/index.ja.mdx, docs/contents/components/overlay/context-menu/index.mdx, docs/contents/components/overlay/menu/index.ja.mdx, docs/contents/components/overlay/menu/index.mdx
Updated useRef type in component docs.
No
=> Updated useRef type in component docs

stories/hooks/use-window-event.stories.tsx
Add OS detection to `useWindowEvent` hook.
No
=> Add OS detection to `useWindowEvent` hook

.changeset/large-lions-film.md, .changeset/mean-pumas-smile.md, packages/components/loading/src/loading-provider.tsx, packages/core/src/theme.types.ts
Closes #3201
Implemented forwardRef in loading components.
No
=> Implemented forwardRef in loading components

.changeset/tame-ducks-clap.md, packages/components/reorder/src/reorder-item.tsx, packages/components/reorder/src/reorder-trigger.tsx, packages/components/reorder/src/reorder.tsx
=> feat(reorder): add `displayName` to components related with `Reorder`

docs/constant/contributors.ts, docs/constant/members.ts
Updated contributor and member lists.
No
=> Updated contributor and member lists

.changeset/cuddly-buckets-guess.md, packages/components/menu/src/context-menu-trigger.tsx, packages/components/menu/src/context-menu.tsx, packages/components/menu/src/menu-button.tsx, packages/components/menu/src/menu-divider.tsx, packages/components/menu/src/menu-group.tsx, packages/components/menu/src/menu-item.tsx, packages/components/menu/src/menu-list.tsx, packages/components/menu/src/menu-option-group.tsx, packages/components/menu/src/menu.tsx
=> feat(menu): add `displayName` to components related with `Menu`

docs/contents/components/typography/em/index.ja.mdx, docs/contents/components/typography/em/index.mdx, docs/contents/components/typography/em/theming.ja.mdx, docs/contents/components/typography/em/theming.mdx, docs/scripts/component/props.ts
Closes #3250
Added `Em` documentation.
No
=> Added `Em` documentation

docs/contents/components/typography/code/index.ja.mdx, docs/contents/components/typography/code/index.mdx, docs/contents/components/typography/code/props.ja.mdx, docs/contents/components/typography/code/props.mdx, docs/contents/components/typography/code/theming.ja.mdx, docs/contents/components/typography/code/theming.mdx
Closes #3251
Added `Code` documentation.
No
=> Added `Code` documentation

docs/contents/hooks/use-async-callback.ja.mdx, docs/contents/hooks/use-async-callback.mdx
Closes #3277
Added 'label: New' to useAsyncCallback docs.
No
=> Added 'label: New' to useAsyncCallback docs

docs/contents/components/typography/blockquote/index.mdx
Closes #3276
Updated `Blockquote` component docs and usage.
No
=> Updated `Blockquote` component docs and usage

.changeset/big-planes-admire.md, packages/components/button/src/button.tsx, packages/components/close-button/src/close-button.tsx, packages/components/pagination/src/pagination-item.tsx, packages/components/tabs/src/tab.tsx, packages/components/toggle/src/toggle.tsx
Closes #3281
Removed conditional ripple disable logic.
No
=> Removed conditional ripple disable logic

docs/contents/components/overlay/popover/index.ja.mdx, docs/contents/components/overlay/popover/index.mdx
=> Fix close button section for `@yamda-ui/popover`

docs/contents/components/data-display/table/index.ja.mdx, docs/contents/components/data-display/table/index.mdx
Closes https://github.com/yamada-ui/yamada-ui/issues/3037
In the documentation for the Table component, there is an error in the description of how to disable selection for specific rows. The property name is incorrectly stated as defaultSelectedRowIds instead of the correct disabledRowIds. Therefore, I have updated the documentation to reflect the correct property name.
=> fix(docs): fix usage section for Table component

docs/contents/components/forms/icon-button/accessibility.ja.mdx, docs/contents/components/forms/icon-button/accessibility.mdx
Closes #3151
[English]
[Japanese]
No
=> Added a11y doc for icon-button

.changeset/kind-geese-jam.md, packages/theme/package.json
Closes #3331
Error occurred on Next.js 15 when using yamada-ui components in `loading.tsx'.
Fixed bug by adding `"use client"` to theme files.
No
=> Added `"use client"` to theme

.changeset/soft-camels-marry.md, packages/components/resizable/src/resizable-item.tsx, packages/components/resizable/src/resizable-trigger.tsx, packages/components/resizable/src/resizable.tsx, packages/components/resizable/src/use-resizable.ts
=> feat(resizable): add `displayName` to `Resizable` and `ResizableItem`

.changeset/few-chairs-dream.md, packages/components/notice/src/notice-provider.tsx, packages/components/notice/src/notice.tsx
=> Set `displayName` and `__ui__` for `@yamada-ui/notice`

.changeset/lemon-dryers-own.md, stories/components/disclosure/accordion.stories.tsx
Closes #3387
Changes import of @yamada-ui/lucide in disclosure of Storybook to *Icon.
No
=> fix: change import of @yamada-ui/lucide in disclosure of Storybook to *Icon

.github/workflows/quality.yml, .github/workflows/sync-branch.yml
Added  workflow to sync branch `v2.0` to `main`.
No
=> Added sync branch workflow

docs/contents/components/layouts/index.mdx
Updated layout page title to plural.
No
=> Updated layout page title to plural

.changeset/hungry-students-rule.md, packages/components/menu/src/menu-button.tsx, packages/components/menu/src/menu-item.tsx, packages/components/menu/src/menu-list.tsx, packages/components/menu/tests/menu.test.tsx, packages/theme/src/components/menu.ts
Closes #1923
add necessary attributes and keyboard interactions to each component
No
=> Update `@yamada-ui/menu` accessibility

docs/contents/components/forms/segmented-control/index.ja.mdx, docs/contents/components/forms/segmented-control/index.mdx, stories/components/forms/segmented-control.stories.tsx
Replace FormControl with Fieldset.
No
=> Replace FormControl with Fieldset

docs/contents/components/forms/autocomplete/accessibility.ja.mdx, docs/contents/components/forms/autocomplete/accessibility.mdx, docs/contents/components/forms/multi-autocomplete/accessibility.ja.mdx, docs/contents/components/forms/multi-autocomplete/accessibility.mdx
Closes #1540
Added accessibility documentation for components.
No
=> Added accessibility documentation for components

.changeset/moody-cheetahs-rescue.md, packages/components/list/src/list.tsx
Fixed prop reflection in list component.
No
=> Fixed prop reflection in list component

.changeset/big-dodos-scream.md, packages/components/tooltip/src/tooltip.tsx
Updated props and Popper integration.
No
=> Updated props and Popper integration

.changeset/tricky-spiders-tease.md, packages/components/password-input/src/password-input-strength-meter.tsx
Added default value comment for `max`.
No
=> Added default value comment for `max`

docs/pages/examples/tasks/header.tsx
Closes #3627
Removed list style from header items.
No
=> Removed list style from header items

packages/components/for/DOCS.json, packages/components/format/DOCS.json, packages/components/password-input/DOCS.json, packages/components/status/DOCS.json
=> Added `DOCS.json`

docs/contents/components/forms/password-input/accessibility.ja.mdx, docs/contents/components/forms/password-input/accessibility.mdx, docs/contents/components/forms/password-input/index.ja.mdx, docs/contents/components/forms/password-input/index.mdx, docs/contents/components/forms/password-input/props.ja.mdx, docs/contents/components/forms/password-input/props.mdx, docs/contents/components/forms/password-input/theming.ja.mdx, docs/contents/components/forms/password-input/theming.mdx, docs/i18n/content.en.json, docs/i18n/content.ja.json, stories/components/forms/password-input.stories.tsx
Added `PasswordInput` documentation.
No
=> Added `PasswordInput` documentation

.changeset/fluffy-trees-appear.md, packages/components/portal/src/portal.tsx, packages/components/portal/tests/portal.test.tsx
Closes https://github.com/yamada-ui/yamada-ui/issues/3622
No
=> feat: rename is prefix in variables for portal

docs/contents/hooks/use-format-number.ja.mdx, docs/contents/hooks/use-format-number.mdx
Closes #3663
I have added documentation for `useFormatNumber` hook
=> Add docs for `useFormatNumber` hook

docs/contents/components/other/format-number/index.ja.mdx, docs/contents/components/other/format-number/index.mdx, docs/contents/components/other/format-number/props.ja.mdx, docs/contents/components/other/format-number/props.mdx, docs/contents/components/other/format-number/theming.ja.mdx, docs/contents/components/other/format-number/theming.mdx, docs/i18n/content.en.json, docs/i18n/content.ja.json, docs/scripts/component/props.ts
Closes #3465
Added documentation for `format-number` component.
N/A
N/A
No
N/A
=> Add documentation for `FormatNumber` component

.changeset/pretty-hotels-lay.md, packages/components/format/src/format-byte.tsx, packages/components/format/src/format-number.tsx
Updated component documentation descriptions.
No
=> Updated component documentation descriptions

docs/contents/components/forms/input/index.ja.mdx, docs/contents/components/forms/input/index.mdx
Replace `Fieldset` with `FormControl` in forms.
No
=> Replace `Fieldset` with `FormControl` in forms

docs/contents/components/other/format-byte/index.ja.mdx, docs/contents/components/other/format-byte/index.mdx, docs/contents/components/other/format-byte/props.ja.mdx, docs/contents/components/other/format-byte/props.mdx, docs/contents/components/other/format-byte/theming.ja.mdx, docs/contents/components/other/format-byte/theming.mdx
Closes #3466
I have added documentation for `FormatByte` component.
=> Add documentation for `FormatByte` component

examples/create-react-app/src/components/layouts/header.tsx, examples/hono/src/components/layouts/header.tsx, examples/next/app/components/layouts/header.tsx, examples/next/pages/components/layouts/header.tsx, examples/remix/app/components/layouts/header.tsx, examples/vite/src/components/layouts/header.tsx
Closes #3411  
Fixed import of lucide-icon in `header.tsx` in `example` folder.
=> fix: fix example's icon import

docs/constant/contributors.ts, docs/constant/maintainers.ts, docs/constant/members.ts, docs/i18n/content.en.json, docs/i18n/content.ja.json
Update contributor and maintainer lists.
No
=> Update contributor and maintainer lists

.changeset/tricky-mails-agree.md, packages/components/resizable/src/use-resizable.ts, stories/components/data-display/resizable.stories.tsx
Closes https://github.com/yamada-ui/yamada-ui/issues/3620
=> feat: rename is prefix in variables for resizable

.changeset/rude-monkeys-sin.md, packages/components/radio/src/use-radio-group.ts
Closes #3610
add `@deprecated` to the `isNative` prop
No
=> feat(radio): add `@deprecated` to the `isNative` prop

.changeset/tidy-teachers-shout.md, packages/components/progress/src/circle-progress.tsx, packages/components/progress/src/progress.tsx
Closes #3621
Removing all is prefix from is*
No
=> feat(progress): remove is prefix from props

.changeset/forty-starfishes-protect.md, packages/components/transitions/src/scale-fade.tsx
Closes #3791
Moved animate declaration for clarity.
No
=> Moved animate declaration for clarity

docs/contents/styled-system/theming/customize-theme.ja.mdx
=> fix: fixed to `extendBaseTheme`

.changeset/purple-pigs-stare.md, packages/hooks/use-disclosure/src/index.ts
Closes #3804
Removing all is prefix from is*.
No
=> feat(use-disclosure): remove is prefix from props

.changeset/cuddly-mugs-warn.md, docs/contents/components/forms/slider/index.ja.mdx, docs/contents/components/forms/slider/index.mdx, stories/components/forms/slider.stories.tsx
Closes #3792 
update "Control externally" example to use <ButtonGroup />
=> docs(slider): update "Control externally" example to use <ButtonGroup />

.changeset/gentle-paws-care.md, docs/components/navigation/breadcrumb.tsx, packages/components/breadcrumb/src/breadcrumb.tsx, stories/components/navigation/breadcrumb.stories.tsx
Closes #3796
Added `separatorProps` to components.
No
=> Added `separatorProps` to components

.changeset/tidy-islands-whisper.md, packages/components/password-input/tests/password-input.test.tsx
Closes #3829 
Enhanced Test Coverage for `@yamada-ui/password-input` up to 100%
`screen.findByRole` dosen't works correctly. So I used `screen.findByPlaceholderText` instead of it.
=> Enhance Test Coverage for `@yamada-ui/password-input`

packages/components/radio/tests/radio-card.test.tsx
=> Enhanced Test Coverage for `@yamada-ui/radio`

docs/contents/components/forms/file-input/index.ja.mdx, docs/contents/components/forms/file-input/index.mdx
Closes #3732
Fixed the repetition part in the `FileInput` documentation to use the `For` component.
No
=> Use <For/> in `FileInput` documentation 

docs/contents/components/data-display/list/index.ja.mdx, docs/contents/components/data-display/list/index.mdx
Closes #3744
Fixed the repetition part in the `List` documentation to use the `For` component.
No
=> Use <For/> in `List` documentation

docs/contents/components/layouts/separator/index.ja.mdx, docs/contents/components/layouts/separator/index.mdx
Closes #3699
Fixed the repetition part in the `Separator` documentation to use the `For` component.
No
=> Use <For/> in `Separator` documentation

docs/contents/components/layouts/simple-grid/index.ja.mdx, docs/contents/components/layouts/simple-grid/index.mdx
Closes #3700
Fixed the repetition part in the `SimpleGrid` documentation to use the `For` component.
No
=> Use <For/> in `SimpleGrid` documentation

.changeset/perfect-ads-burn.md, .changeset/perfect-rabbits-yawn.md, .changeset/pink-icons-talk.md, packages/components/autocomplete/src/autocomplete-option.tsx, packages/components/autocomplete/src/use-autocomplete-option.ts, packages/components/autocomplete/tests/autocomplete.test.tsx, packages/components/popover/src/popover.tsx, packages/components/select/src/multi-select.tsx, packages/components/select/src/option.tsx, packages/components/select/src/select-icon.tsx, packages/components/select/src/select.tsx, packages/components/select/src/use-select-list.ts, packages/components/select/src/use-select-option-group.ts, packages/components/select/src/use-select-option.ts, packages/components/select/src/use-select.tsx, packages/hooks/use-disclosure/src/index.ts
Closes https://github.com/yamada-ui/yamada-ui/issues/3619
=> feat: rename is prefix in variables for select

.changeset/ten-actors-punch.md, packages/components/menu/src/menu-button.tsx, packages/components/menu/src/menu-context.ts, packages/components/menu/src/menu-item.tsx, packages/components/menu/src/menu-option-group.tsx, packages/components/menu/src/menu.tsx
Closes #3594 
Remove is prefix
Before: isDisabled, isFocusable, isChecked
After: disabled, focusable, checked
No
=> `menu`: remove is from props

docs/contents/components/other/empty-state/index.ja.mdx, docs/contents/components/other/empty-state/index.mdx
Closes https://github.com/yamada-ui/yamada-ui/issues/3783
Fixed the repetition part in the `EmptyState`  documentation to use the `For` component.
No
=> Use <For /> in EmptyState documentation

docs/contents/components/typography/text/index.ja.mdx, docs/contents/components/typography/text/index.mdx
Closes https://github.com/yamada-ui/yamada-ui/issues/3707
Fixed the repetition part in the `Text` documentation to use the `For` component.
No
=> Use <For /> in Text documentation

docs/contents/components/typography/code/index.ja.mdx, docs/contents/components/typography/code/index.mdx
Closes #3704
use <For /> component when repeating a component in `Code` docs
No
=> Use <For /> in `Code` documentation

docs/contents/components/layouts/grid/index.ja.mdx, docs/contents/components/layouts/grid/index.mdx
Closes https://github.com/yamada-ui/yamada-ui/issues/3698
Fixed the repetition part in the`Grid` documentation to use the `For` component.
No
=> Use <For/> `Grid` documentation

docs/contents/components/layouts/wrap/index.ja.mdx, docs/contents/components/layouts/wrap/index.mdx
Closes https://github.com/yamada-ui/yamada-ui/issues/3702
Fixed the repetition part in the`Wrap` documentation to use the `For` component.
No
=> Use <For/> `Wrap` documentation

docs/contents/components/feedback/progress/index.ja.mdx, docs/contents/components/feedback/progress/index.mdx
Closes https://github.com/yamada-ui/yamada-ui/issues/3776
Use the `<For />` component in `Progress` docs
No
=> Use <For /> in Progress documentation

docs/contents/components/forms/month-picker/index.ja.mdx, docs/contents/components/forms/month-picker/index.mdx
Closes #3729 
Use the For component in MonthPicker docs
No
=> Use <For/> in `MonthPicker` documentation

docs/contents/components/feedback/status/index.ja.mdx, docs/contents/components/feedback/status/index.mdx
Closes https://github.com/yamada-ui/yamada-ui/issues/3774
Use the `<For />` component in `Status` docs
No
=> Use <For /> in Status documentation

packages/react/src/components/alert/alert.tsx, packages/react/src/theme/components/alert.ts
Closes https://github.com/yamada-ui/yamada-ui/issues/3875
Move static styles from alert component to theme.
Dynamic styles are not supported in this PR.
No
=> refactor: move styles to theme for alert

packages/react/src/components/bleed/bleed.tsx
Closes #4197 
This PR is to simply remove the `is` prefix from internal variables in `bleed` component
No
=> `bleed`: rename internal variables

packages/react/src/components/card/card.tsx, packages/react/src/theme/components/card.ts
Closes https://github.com/yamada-ui/yamada-ui/issues/3882
Migrate styles from components to themes.
Since component styles in themes inherit styles from other components using mergeStyle etc., duplicate styles should be removed.
=> refactor: move styles to theme for card

packages/react/src/components/data-list/data-list.tsx
Closes https://github.com/yamada-ui/yamada-ui/issues/3887
Removed CSSUIObject definitions due to the creation of headless UI components.
=> refactor: remove css ui object for data list

packages/react/src/components/autocomplete/autocomplete.stories.tsx
Closes #4192 
Related #3852 
Identified missing changes in autocomplete storybook example, this PR is to simply add the correct props to restore autocomplete storybook functionality 😓
No
=> Missing changes in `autocomplete` storybook

.changeset/plenty-kangaroos-cough.md, packages/components/close-button/src/close-button.tsx
Closes #4218
Related #4217 
Identified a missing deprecation update in `main` branch:
- This PR is to rename `isRounded` to `fullRounded` in `main` branch
No
=> `close-button`: rename isRounded to fullRounded

packages/react/src/components/file-button/file-button.stories.tsx, packages/react/src/components/file-button/file-button.test.tsx, packages/react/src/components/file-button/file-button.tsx
Closes #3865 
Removed `isDisabled`, `isInvalid`, `isReadOnly`, `isRequired` from `form-control` package
No
=> `file-button`: remove reprecated props

packages/react/src/components/focus-lock/focus-lock.tsx
Closes #3867 
Removed `isDisabled` prop
No
=> `focus-lock`: remove deprecated props

packages/react/src/components/color-picker/color-picker.tsx, packages/react/src/components/color-picker/color-selector-eye-dropper.tsx
Closes #4158  
Replaced `EyeDropperIcon` in `ColorPicker` and `ColorSelector`.
=> fix: replaced `EyeDropperIcon` in `ColorPicker` and `ColorSelector`.

packages/react/src/components/stack/z-stack.tsx
Closes #4268 
Closes #3950 
Removed `is` from variables
No
=> `stack`: rename variables

packages/react/src/components/pin-input/pin-input.stories.tsx, packages/react/src/components/pin-input/pin-input.tsx
Closes #3963 
Replaced `form-control` props in storybook
Renamed internal variables
No
=> `pin-input`: remove deprecated props

packages/react/src/components/rating/rating.stories.tsx, packages/react/src/components/rating/rating.test.tsx, packages/react/src/components/rating/use-rating.tsx
Closes #3968 
Renamed internal variables
Replaced `form-control` props
No
=> `rating`: remove deprecated props

.changeset/hungry-lies-visit.md, .changeset/red-crabs-pull.md, packages/components/motion/package.json, packages/components/motion/src/motion.tsx, packages/core/package.json, pnpm-lock.yaml
Closes yamada-ui/yamada-colors#108
Fixed render animation and updated dependencies.
No
=> Fixed render animation and updated dependencies

packages/react/src/components/radio/radio-card.stories.tsx, packages/react/src/components/radio/radio-card.tsx, packages/react/src/components/radio/radio-group.test.tsx, packages/react/src/components/radio/radio.stories.tsx, packages/react/src/components/radio/radio.test.tsx, packages/react/src/components/radio/radio.tsx, packages/react/src/components/radio/use-radio-group.ts, packages/react/src/components/radio/use-radio.ts
Closes #3967 
Removed `isNative`, `isChecked`, `defaultIsChecked` props
Replaced `form-control` props in storybook
No
=> `radio`: remove deprecated props

.changeset/pink-onions-move.md, packages/hooks/use-async-callback/src/index.ts
Closes #4288
Updated callback return type.
No
=> Updated callback return type

.changeset/rich-stingrays-fetch.md, packages/components/checkbox/src/checkbox-card-group.tsx, packages/components/checkbox/src/checkbox-group.tsx, packages/components/radio/src/radio-card-group.tsx, packages/components/radio/src/radio-group.tsx
Closes #4290
Closes #4289
Updated form control prop handling in UI components.
No
=> Updated form control prop handling in UI components

packages/react/src/components/accordion/accordion.style.ts
=> fix(accordion): correct rotation transformation for expanded state

.changeset/famous-dolls-smoke.md, packages/components/table/src/index.ts, packages/components/table/src/use-table.tsx
=> fix(table): added HeaderContext and TableMeta types to export

docs/contents/components/media-and-icons/image/index.ja.mdx, docs/contents/components/media-and-icons/image/index.mdx, stories/components/media-and-icons/image.stories.tsx
Closes #4322
Updated fallback image URLs in documentation.
=> Updated fallback image URLs in documentation

docs/contents/components/typography/highlight/index.ja.mdx, docs/contents/components/typography/highlight/index.mdx
Closes #4330 
Docs update: replace the deprecated props with new props
No
=> docs(highlight): replace with new props

docs/contents/components/forms/radio-card/index.ja.mdx, docs/contents/components/forms/radio-card/index.mdx
=> docs(radio-card): replace with new props

docs/contents/components/forms/textarea/index.ja.mdx, docs/contents/components/forms/textarea/index.mdx
=> docs(textarea): replace with new props

docs/contents/components/forms/radio/index.ja.mdx, docs/contents/components/forms/radio/index.mdx
=> docs(radio): replace with new props

docs/contents/components/forms/pin-input/index.ja.mdx, docs/contents/components/forms/pin-input/index.mdx
=> docs(pin-input): replace with new props

docs/contents/components/forms/password-input/index.ja.mdx, docs/contents/components/forms/password-input/index.mdx
=> docs(password-input): replace with new props

docs/contents/components/forms/checkbox/index.ja.mdx, docs/contents/components/forms/checkbox/index.mdx
=> docs(checkbox): replace with new props

docs/contents/components/forms/multi-select/index.ja.mdx, docs/contents/components/forms/multi-select/index.mdx
=> docs(multi-select): replace with new props

docs/contents/components/forms/select/index.ja.mdx, docs/contents/components/forms/select/index.mdx
=> docs(select): replace with new props

docs/contents/components/forms/native-select/index.ja.mdx, docs/contents/components/forms/native-select/index.mdx
=> docs(native-select): replace with new props

docs/contents/components/forms/toggle/index.ja.mdx, docs/contents/components/forms/toggle/index.mdx
=> docs(toggle): replace with new props

docs/contents/components/forms/checkbox-card/index.ja.mdx, docs/contents/components/forms/checkbox-card/index.mdx
=> docs(checkbox-card): replace with new props

docs/contents/components/forms/switch/index.ja.mdx, docs/contents/components/forms/switch/index.mdx
=> docs(switch): replace with new props

docs/contents/components/forms/month-picker/index.ja.mdx, docs/contents/components/forms/month-picker/index.mdx
=> docs(month-picker): replace with new props

docs/contents/components/forms/range-date-picker/index.ja.mdx, docs/contents/components/forms/range-date-picker/index.mdx
=> docs(range-date-picker): replace with new props

docs/contents/components/forms/year-picker/index.ja.mdx, docs/contents/components/forms/year-picker/index.mdx
=> docs(year-picker): replace with new props

docs/contents/components/forms/color-picker/index.ja.mdx, docs/contents/components/forms/color-picker/index.mdx
=> docs(color-picker): replace with new props

docs/contents/components/forms/multi-autocomplete/index.ja.mdx, docs/contents/components/forms/multi-autocomplete/index.mdx
=> docs(multi-autocomplete): replace with new props

docs/contents/components/forms/alpha-slider/index.ja.mdx, docs/contents/components/forms/alpha-slider/index.mdx
=> docs(alpha-slider): replace with new props

docs/contents/components/forms/hue-slider/index.ja.mdx, docs/contents/components/forms/hue-slider/index.mdx
=> docs(hue-slider): replace with new props

docs/contents/components/forms/range-slider/index.ja.mdx, docs/contents/components/forms/range-slider/index.mdx
=> docs(range-slider): replace with new props

docs/contents/components/forms/slider/index.ja.mdx, docs/contents/components/forms/slider/index.mdx
=> docs(slider): replace with new props

docs/contents/components/forms/dropzone/index.ja.mdx, docs/contents/components/forms/dropzone/index.mdx
=> docs(dropzone): replace with new props

docs/contents/components/forms/file-button/index.ja.mdx, docs/contents/components/forms/file-button/index.mdx
=> docs(file-button): replace with new props

docs/contents/components/forms/file-input/index.ja.mdx, docs/contents/components/forms/file-input/index.mdx
=> docs(file-input): replace with new props

docs/contents/components/forms/editable/index.ja.mdx, docs/contents/components/forms/editable/index.mdx
=> docs(editable): replace with new props

docs/contents/components/forms/segmented-control/index.ja.mdx, docs/contents/components/forms/segmented-control/index.mdx
=> docs(segmented-control): replace with new props

docs/contents/components/forms/rating/index.ja.mdx, docs/contents/components/forms/rating/index.mdx
=> docs(rating): replace with new props

docs/contents/components/forms/button/index.ja.mdx, docs/contents/components/forms/button/index.mdx
=> docs(button): replace with new props

packages/react/src/components/highlight/highlight.test.tsx
Closes https://github.com/yamada-ui/yamada-ui/issues/4512
Due to these changes, testing is no longer required.
https://github.com/yamada-ui/yamada-ui/commit/700185009a406c95c0bf7199fcfdfa46af1cdac4?w=1#diff-73aebb837fc68bc25b1fa43af48932040d181036abf4cafd16c266390b64ef22L47
=> test: fix failing tests for highlight component

packages/react/src/components/field/field.test.tsx
Closes https://github.com/yamada-ui/yamada-ui/issues/4468
=> test: fix failing tests for field component

docs/contents/components/navigation/pagination/index.ja.mdx, docs/contents/components/navigation/pagination/index.mdx
=> docs(pagination): replace with new props

docs/contents/components/transitions/airy/index.ja.mdx, docs/contents/components/transitions/airy/index.mdx, docs/contents/components/transitions/collapse/index.ja.mdx, docs/contents/components/transitions/collapse/index.mdx, docs/contents/components/transitions/fade/index.ja.mdx, docs/contents/components/transitions/fade/index.mdx
Closes #4393 
Closes #4394 
Closes #4395 
No
=> transitions(airy, collapse, fade): replace with new props

docs/contents/components/transitions/scale-fade/index.ja.mdx, docs/contents/components/transitions/scale-fade/index.mdx, docs/contents/components/transitions/slide-fade/index.ja.mdx, docs/contents/components/transitions/slide-fade/index.mdx, docs/contents/components/transitions/slide/index.ja.mdx, docs/contents/components/transitions/slide/index.mdx
Closes #4398 
Closes #4399 
Closes #4400 
No
=> transitions(scale-fade, slide, slide-fade): use new props

docs/contents/components/other/focus-lock/index.ja.mdx, docs/contents/components/other/focus-lock/index.mdx, docs/contents/components/other/ripple/index.ja.mdx, docs/contents/components/other/ripple/index.mdx
Closes #4401 
Closes #4402 
No
=> others(focus-lock, ripple): replace with new props

.github/workflows/quality.yml, packages/react/src/components/avatar/avatar.test.tsx, packages/react/src/components/button/button-group.test.tsx, packages/react/src/components/card/card.test.tsx, packages/react/src/components/container/container.test.tsx, packages/react/src/components/scroll-area/scroll-area.test.tsx, packages/react/src/components/textarea/textarea.test.tsx, packages/react/src/components/textarea/use-autosize.test.tsx, packages/react/src/components/visually-hidden/visually-hidden.test.tsx, packages/react/src/core/css/css.test.tsx
=> test: add a temporary `todo` for failing tests

packages/react/src/components/flex/flex.test.tsx
=> test: add accessibility and rendering tests for <Flex />

packages/react/src/components/icon/icon.test.tsx, packages/react/src/components/icon/lucide-icon.test.tsx
=> test: enhance icon component tests for accessibility and rendering

packages/react/src/components/loading/loading.test.tsx
=> test: enhance loading component tests for accessibility and rendering

packages/react/src/components/group/group.test.tsx, packages/react/src/components/group/group.tsx
=> test: add accessibility and rendering tests for <Group /> component

packages/react/src/components/heading/heading.test.tsx
=> test: add additional tests for <Heading /> component functionality

packages/react/src/components/infinite-scroll-area/infinite-scroll-area.test.tsx
=> test: add additional tests for InfiniteScrollArea component

packages/react/src/components/portal/portal.test.tsx, packages/react/src/components/portal/portal.tsx
=> test(portal): added displayName, className, and HTML tag checks

packages/react/src/components/for/for.test.tsx, packages/react/src/components/for/for.tsx
=> test: add displayName and __ui__ properties to For component

packages/react/src/components/motion/motion.test.tsx, packages/react/src/components/motion/motion.tsx
=> test: add accessibility and functionality tests for Motion component

packages/react/src/components/slide/slide-fade.test.tsx, packages/react/src/components/slide/slide.test.tsx
=> test(slide): add test for displayName, className, and HTML tag rendering

packages/react/src/components/input/input-group.tsx, packages/react/src/components/input/input.test.tsx
=> test: add tests for InputGroup displayName and className

packages/react/src/components/avatar/avatar.test.tsx
Closes https://github.com/yamada-ui/yamada-ui/issues/4462
I have fixed the test.
=> test: fix failing tests for avatar component

packages/react/src/components/card/card.test.tsx
Closes #4604
I used `getComputedStyle` to test the exact CSS rendered by the browser.
No
=> test: fix `Card`  component test

.changeset/sixty-apples-tie.md, packages/components/visually-hidden/src/visually-hidden.tsx, packages/components/visually-hidden/tests/visually-hidden.test.tsx, packages/test/src/accessibility.tsx
Updated `clip` to `clipPath` for hiding elements.
No
=> Updated `clip` to `clipPath` for hiding elements

.changeset/clear-horses-slide.md, packages/hooks/use-processing/src/index.ts
Renamed `isLoading` to `loading` in `useProcessing`.
No
=> Renamed `isLoading` to `loading` in `useProcessing`

packages/react/src/components/container/container.test.tsx
Closes #4618
Update `Container` component tests
No
=> test: update container component tests

packages/react/src/components/visually-hidden/visually-hidden.test.tsx
Closes https://github.com/yamada-ui/yamada-ui/issues/4621
=> test: update VisuallyHidden component tests

.changeset/itchy-carpets-type.md, packages/utils/src/react.tsx, packages/utils/tests/react.test.tsx
Closes #4590
Updated element comparison logic and tests.
Yes
=> Updated element comparison logic and tests

packages/react/src/components/number-input/use-number-counter.ts, packages/react/src/providers/i18n-provider/intl/en-US.ts, packages/react/src/providers/i18n-provider/intl/ja-JP.ts
=> Internationalize `aria-label` within the `NumberInput`

packages/react/src/components/password-input/use-password-input.tsx, packages/react/src/components/password-input/use-strength-meter.ts, packages/react/src/providers/i18n-provider/intl/en-US.ts, packages/react/src/providers/i18n-provider/intl/ja-JP.ts
=> feat(i18n): add translations for `password input` component

packages/react/src/components/resizable/resizable.test.tsx
Closes # 
fix `Resizable` component test
No
=> test(Resizable): enable rendering test and add aria attributes to Trigger

packages/react/src/core/components/props.ts
Added `useSplitProps` function for props management.
=> Added `useSplitProps` function for props management

packages/react/src/components/reorder/reorder.test.tsx
Closes https://github.com/yamada-ui/yamada-ui/issues/4662
Fixed the skipped reorder tests.
=> test: update reorder component tests

.changeset/twenty-apes-guess.md, packages/components/tabs/src/tab.tsx
=> fix(Tabs): set focusOnClick to false in Tab component

packages/react/src/components/scroll-area/scroll-area.test.tsx
Closes https://github.com/yamada-ui/yamada-ui/issues/4663
Fixed the skipped scroll area tests.
=> test: update scroll area component

packages/react/src/components/pagination/pagination.tsx, packages/react/src/components/progress/use-progress.ts, packages/react/src/providers/i18n-provider/intl/en-US.ts, packages/react/src/providers/i18n-provider/intl/ja-JP.ts
Update translation keys and improve progress label.
=> Update translation keys and improve progress label

packages/react/@types/@emotion/react.d.ts, packages/react/src/core/system/styled.tsx, packages/workspace/src/typescript/tsconfig.json, www/components/mdx/steps.tsx, www/data/index.ts
Update `withEmotionCache` typings for generics.
=> Update `withEmotionCache` typings for generics

packages/react/src/components/loading/background.tsx, packages/react/src/components/menu/menu.style.ts, packages/react/src/components/modal/modal.style.ts, packages/react/src/components/popover/popover.style.ts, packages/react/src/components/tooltip/tooltip.style.ts
Change bg to `"bg.panel"` for consistency.
=> Change bg to `"bg.panel"` for consistency

packages/react/src/components/bleed/bleed.stories.tsx
Adjust `blockStart` from `"md"` to `"lg"` in story.
=> Adjust `blockStart` from `"md"` to `"lg"` in story

www/contents/components/(components)/button.ja.mdx, www/contents/components/(components)/button.mdx
Related #4707 
Migrate `Button` documentation to v2.
=> Migrate `Button` documentation

packages/react/src/components/native-select/native-select.stories.tsx, packages/react/src/components/native-select/native-select.test.tsx, packages/react/src/components/native-select/props.json, packages/react/src/components/native-select/use-native-select.tsx, packages/react/src/components/select/namespace.ts, packages/react/src/components/select/props.json, packages/react/src/components/select/select.stories.tsx, packages/react/src/components/select/select.tsx, packages/react/src/components/select/use-select.tsx
Add includePlaceholder prop support.
=> Add includePlaceholder prop support

www/contents/components/(components)/color-swatch.ja.mdx, www/contents/components/(components)/color-swatch.mdx
Related #4707 
Migrate `ColorSwatch` documentation to v2.
=> Migrate `ColorSwatch` documentation

packages/cli/src/commands/init/index.ts, packages/cli/src/constant.ts
Delay adding `@yamada-ui/react` v2 dependency.
=> Delay adding `@yamada-ui/react` v2 dependency

www/contents/components/(components)/group.ja.mdx, www/contents/components/(components)/group.mdx
Related #4707 
Migrate `Group` documentation to v2.
=> Migrate `Group` documentation

www/contents/components/(components)/tag.ja.mdx, www/contents/components/(components)/tag.mdx
=> Migrate `Tag`documentation

www/contents/components/(components)/icon-button.ja.mdx, www/contents/components/(components)/icon-button.mdx
Related #4707 
Migrate `IconButton` documentation to v2.
=> Migrate `IconButton` documentation

packages/react/src/components/highlight/highlight.tsx
Closes #4824
Update rendering logic for fragments and text.
=> Update rendering logic for fragments and text

packages/react/src/components/field/field.tsx, packages/react/src/components/field/use-field-props.ts, packages/react/src/components/fieldset/fieldset.stories.tsx, packages/react/src/components/fieldset/fieldset.tsx, www/contents/components/(components)/fieldset.ja.mdx, www/contents/components/(components)/fieldset.mdx
Closes #4797
Incorporate fieldset context into field components.
=> Incorporate fieldset context into field components

www/contents/components/(components)/link-box.ja.mdx, www/contents/components/(components)/link-box.mdx
Related #4707 
Migrate `LinkBox` documentation to v2.
=> Migrate `LinkBox` documentation

www/contents/components/(animations)/loading.ja.mdx, www/contents/components/(animations)/loading.mdx
Related #4707 
Migrate `Loading` documentation to v2.
=> Migrate `Loading` documentation

www/contents/components/cli.ja.mdx, www/contents/components/cli.mdx, www/contents/get-started/cli.ja.mdx, www/contents/get-started/cli.mdx, www/contents/theming/cli.ja.mdx, www/contents/theming/cli.mdx
Closes # 
Add CLI documentations.
=> Add CLI documentations

www/contents/components/(components)/toggle.ja.mdx, www/contents/components/(components)/toggle.mdx
=> Migrate `Toggle` documentation

www/contents/components/(components)/status.ja.mdx, www/contents/components/(components)/status.mdx
=> Migrate `Status` documentation

packages/react/src/theme/styles/text-styles.ts, www/components/code-preview.tsx, www/components/mdx/code-block.tsx, www/contents/theming/styles/global-styles.ja.mdx, www/contents/theming/styles/global-styles.mdx, www/contents/theming/styles/layer-styles.ja.mdx, www/contents/theming/styles/layer-styles.mdx, www/contents/theming/styles/reset-styles.ja.mdx, www/contents/theming/styles/reset-styles.mdx, www/contents/theming/styles/text-styles.ja.mdx, www/contents/theming/styles/text-styles.mdx, www/libs/shiki.ts, www/utils/rehype-plugins/rehype-pre.ts, www/utils/remark-plugins/remark-code-block.ts
Closes #4915
Closes #4912 
Closes #4911  
Closes #4900
=> Add theming styles

www/contents/hooks/use-window-event.ja.mdx, www/contents/hooks/use-window-event.mdx
=> docs(use-window-event): migrate documentation

www/contents/hooks/use-resize-observer.ja.mdx, www/contents/hooks/use-resize-observer.mdx
=> docs(use-resize-observer): migrate documentation

www/contents/hooks/use-value.ja.mdx, www/contents/hooks/use-value.mdx
=> docs(use-value): migrate documentation

www/contents/hooks/use-theme.ja.mdx, www/contents/hooks/use-theme.mdx
=> docs(use-theme): migrate documentation

www/contents/components/(components)/password-input.ja.mdx, www/contents/components/(components)/password-input.mdx
=> docs(password-input): migrate documentation

packages/react/src/hooks/use-combobox/index.tsx
=> Simplify onOpenWithActiveDescendant calls

www/contents/components/(components)/pin-input.ja.mdx, www/contents/components/(components)/pin-input.mdx
=> docs(pin-input): migrate documetation

www/contents/hooks/use-animation.ja.mdx, www/contents/hooks/use-animation.mdx, www/contents/hooks/use-dynamic-animation.ja.mdx, www/contents/hooks/use-dynamic-animation.mdx, www/theme/index.ts
=> Initialize useAnimation without args

www/contents/components/(components)/stack.ja.mdx, www/contents/components/(components)/stack.mdx
=> docs(stack): migrate documentation

www/contents/components/(components)/timeline.ja.mdx, www/contents/components/(components)/timeline.mdx
=> docs(timeline): migrate documentation

www/contents/hooks/use-descendants.ja.mdx, www/contents/hooks/use-descendants.mdx
=> Add disabled state handling for descendants

www/contents/hooks/use-counter.ja.mdx, www/contents/hooks/use-counter.mdx
=> Add code-group tabs for usage examples

www/contents/components/(components)/dropzone.ja.mdx, www/contents/components/(components)/password-input.ja.mdx, www/contents/components/(components)/pin-input.ja.mdx, www/contents/components/(components)/radio.ja.mdx, www/contents/components/(components)/radio.mdx, www/contents/components/(components)/textarea.ja.mdx
=> docs(radio): migrate documentation

www/contents/components/(components)/checkbox.ja.mdx, www/contents/components/(components)/checkbox.mdx, www/contents/components/(components)/radio.ja.mdx, www/contents/components/(components)/radio.mdx
=> docs(checkbox): migrate documentation

www/contents/components/(components)/group.ja.mdx, www/contents/components/(components)/menu.ja.mdx, www/contents/components/(components)/menu.mdx, www/contents/components/(components)/popover.ja.mdx, www/contents/components/(components)/timeline.ja.mdx, www/contents/components/(utilities)/format-number.ja.mdx, www/contents/hooks/use-async-callback.ja.mdx, www/contents/hooks/use-format-number.ja.mdx
=> docs(menu): migrate documentation

www/contents/components/(components)/autocomplete.ja.mdx, www/contents/components/(components)/autocomplete.mdx, www/contents/components/(components)/native-select.ja.mdx
=> docs(autocomplete): migrate documentation

www/contents/components/(components)/alpha-slider.mdx, www/contents/components/(components)/autocomplete.ja.mdx, www/contents/components/(components)/autocomplete.mdx, www/contents/components/(components)/checkbox-card.ja.mdx, www/contents/components/(components)/checkbox-card.mdx, www/contents/components/(components)/checkbox.ja.mdx, www/contents/components/(components)/dropzone.ja.mdx, www/contents/components/(components)/editable.ja.mdx, www/contents/components/(components)/file-button.ja.mdx, www/contents/components/(components)/file-input.ja.mdx, www/contents/components/(components)/hue-slider.mdx, www/contents/components/(components)/input.ja.mdx, www/contents/components/(components)/native-select.ja.mdx, www/contents/components/(components)/native-select.mdx, www/contents/components/(components)/number-input.ja.mdx, www/contents/components/(components)/number-input.mdx, www/contents/components/(components)/password-input.ja.mdx, www/contents/components/(components)/pin-input.ja.mdx, www/contents/components/(components)/radio-card.ja.mdx, www/contents/components/(components)/radio-card.mdx, www/contents/components/(components)/radio.ja.mdx, www/contents/components/(components)/select.ja.mdx, www/contents/components/(components)/select.mdx, www/contents/components/(components)/tag.ja.mdx, www/contents/components/(components)/textarea.ja.mdx, www/contents/components/(components)/toggle.ja.mdx
=> docs(select): migrate documentation

www/contents/hooks/use-color-mode-value.ja.mdx, www/contents/hooks/use-color-mode-value.mdx, www/contents/hooks/use-color-mode.ja.mdx, www/contents/hooks/use-color-mode.mdx
Related #4954 
Related #4955 
Updated related color mode hooks documenation.
=> Updated related color mode hooks documenation

packages/react/src/components/portal/portal.stories.tsx
=> docs(portal): create storybook documentation

www/contents/styling/color-scheme.ja.mdx, www/contents/styling/color-scheme.mdx
=> Added Color Scheme documentation

www/contents/styling/cascade-layers.ja.mdx, www/contents/styling/cascade-layers.mdx
=> Add documentation on CSS cascade layers

www/contents/components/(components)/carousel.ja.mdx, www/contents/components/(components)/carousel.mdx, www/contents/components/(components)/infinite-scroll-area.ja.mdx, www/contents/components/(components)/infinite-scroll-area.mdx, www/contents/components/(components)/input.ja.mdx, www/contents/components/(components)/input.mdx, www/contents/components/(components)/number-input.ja.mdx, www/contents/components/(components)/number-input.mdx, www/contents/components/(utilities)/slot.ja.mdx, www/contents/components/styled.ja.mdx, www/contents/components/styled.mdx, www/contents/styling/index.ja.mdx, www/contents/styling/index.mdx
=> Correct prop references in documentation

www/i18n/routing.ts
Closes # 
Related #4772
I have reverted the changes I've made to `routing.ts`
=> refactor(routing): revert prefix changes in routing for i18n

www/contents/components/(components)/grid.ja.mdx, www/contents/components/(components)/grid.mdx
Closes #4975 
I've migrated the `Grid` documentation
=> docs(grid): migrate `Grid` documentation

www/contents/hooks/use-animation.ja.mdx, www/contents/hooks/use-animation.mdx, www/contents/hooks/use-dynamic-animation.ja.mdx, www/contents/hooks/use-dynamic-animation.mdx, www/contents/styling/animation.ja.mdx, www/contents/styling/animation.mdx, www/theme/index.ts
=> Add custom animations tokens to theme

www/contents/components/index.ja.mdx, www/contents/components/index.mdx, www/contents/hooks/index.ja.mdx, www/contents/hooks/index.mdx, www/data/doc-map.en.json, www/data/doc-map.ja.json
=> Add usage instructions for hooks and components

www/contents/get-started/advanced.ja.mdx, www/contents/get-started/advanced.mdx, www/contents/get-started/basics.ja.mdx, www/contents/get-started/basics.mdx, www/contents/hooks/use-loading.ja.mdx, www/contents/hooks/use-loading.mdx
=> Added "Learn the Basics" and "Learn the Advanced" documentation.

www/contents/hooks/use-dynamic-animation.mdx
=> Update documentation for use-dynamic-animation

www/app/[locale]/(examples)/examples/[example]/forms/account.tsx, www/app/[locale]/(examples)/examples/[example]/forms/appearance.tsx, www/app/[locale]/(examples)/examples/[example]/forms/display.tsx, www/app/[locale]/(examples)/examples/[example]/forms/form.tsx, www/app/[locale]/(examples)/examples/[example]/forms/header.tsx, www/app/[locale]/(examples)/examples/[example]/forms/index.tsx, www/app/[locale]/(examples)/examples/[example]/forms/notification.tsx, www/app/[locale]/(examples)/examples/[example]/forms/profile.tsx, www/app/[locale]/(examples)/examples/[example]/forms/sidebar.tsx
=> docs(example): migrate forms example
